### ISSUE TITLE
Invalid online tutorial address

### ISSUE THREAD

**Issue by yunjae2** [notable/notable#928] opened 2019-11-27 14:47 UTC
- **OS Version**: Ubuntu 18.04
- **Notable Version**: 1.8.1

### Current behavior

I wanted to see tutorial so I clicked `Help > Tutorial` in the top bar and a box opened.
I selected `Online Tutorial` in the box, but it opens a web page with invalid address (https://github.com/notable/notable/tree/v1.8.1/resources/tutorial/notes).

### Expected behavior

I expected a web page containing online tutorial to open.

**Comment by fabiospampinato** [comment] 2019-11-27 15:30
Duplicate of #900.

**Comment by fabiospampinato** [comment] 2019-11-27 15:30
For now go to [https://tutorial.notable.md](https://tutorial.notable.md).

**Closed by fabiospampinato** 2019-11-27 15:30 UTC

**Comment by yunjae2** [comment] 2019-11-27 15:32
Oops, it was in the closed issues. Thanks!
