### ISSUE TITLE
Support for document outline

### ISSUE THREAD

**Issue by bendem** [notable/notable#266] opened 2019-01-11 11:08 UTC
### Feature description

When showing a document with multiple headings, it would be interesting to allow the user to show the document outline with the possibility to jump to a specific section directly.

### Feature motivation

For long documents, it's pretty useful to have an overview and to be able to jump around in the document.

**Comment by fabiospampinato** [comment] 2019-01-11 13:20
Sounds like a good application for plugins #128. Perhaps once we switch to Monaco #203 you could enable the minimap.

**Comment by bytekeks** [comment] 2019-01-31 15:54
Another interesting approach could be a TOC within the document:

```
<!-- TOC -->
- [Notable Manual](#notable-manual)
  - [Notes](#notes)
      - [Syntax](#syntax)
      - [Syntax Plugins](#syntax-plugins)
  - [Attachments](#attachments)
  - [Tags](#tags)
      - [Syntax](#syntax-1)
      - [Special Tags](#special-tags)
      - [Collapse/Expand](#collapseexpand)
      - [Editing](#editing)
<!-- /TOC -->
```

It renders correctly in notable and e.g. github.

`right click` -> `generate/update TOC`

**Comment by Fastidious** [comment] 2019-01-31 16:03
@bytekeks isn't that exactly what @bendem requested? He called it outline, but I read it as a TOC.

**Comment by bytekeks** [comment] 2019-01-31 16:16
For my understanding, @bendem wanted a outline that is only displayed within notable. My idea was a outline/toc that is in the document ;)

**Comment by bendem** [comment] 2019-01-31 16:17
Yes, outline, TOC, same thing. I would have liked it as a separate pane though, so that I can jump around in the document without having to scroll back up all the time. I like how pdf readers do it, or QOwnNotes.

**Comment by fabiospampinato** [comment] 2019-01-31 18:51
> As far as I can tell; the intra-document anchors don't work in notable (but do outside via Git or VSCode markdown preview).

Could you open a separate issue about this with a sample note I can use to reproduce the problem?

**Comment by hctagalong** [comment] 2019-01-31 19:03
Done! https://github.com/fabiospampinato/notable/issues/396

**Comment by lmihalkovic** [comment] 2019-02-12 07:27
@fabiospampinato i switched to monaco and ended up disabling the minimap because it is too small. As a programmer i can see its value,  as a notes writter, it looks just weird.

**Comment by lmihalkovic** [comment] 2019-02-12 07:31
@bytekeks if memory serves ```[toc]``` is a known markdown extension that people use. Typically it is a pure render thing (the toc is not generated in the source)

**Comment by Fastidious** [comment] 2019-02-12 17:01
@lmihalkovic everything in markdown is a "pure render thing." 😄 Unless you export it (HTML, PDF, etc).

**Comment by lmihalkovic** [comment] 2019-02-12 19:21
@fastidious yes, it is. An issue arises if the original doc has to be altered live to maintain the toc contents up to date.. but generating the toc contents as a one-off render operation be it for live preview, export to html, or even as a intermediary step to gen a pdf is not an issue at all.
Sorry for my lack of clarity

**Comment by OnyxDelta** [comment] 2019-03-07 19:31
Now that Monaco has replaced CodeMirror, is it feasible to enable to the Minimap?

**Comment by fabiospampinato** [comment] 2019-03-07 20:18
@OnyxDelta pretty doable I'd say ;)

**Comment by fabiospampinato** [comment] 2019-03-09 17:07
I'm closing this as you can now toggle the minimap with a Alt+M, check [this demo](https://www.reddit.com/r/Notable/comments/az5fzv/preview_monaco_editor/).

Let's track the ability to jump to headers in the document [here](#529), and automatic table of contents [here](#530].

**Closed by fabiospampinato** 2019-03-09 17:07 UTC
Labels: enhancement
