### ISSUE TITLE
Note suddenly deleted

### ISSUE THREAD

**Issue by alexanderte** [notable/notable#669] opened 2019-05-21 12:14 UTC
- **OS Version**: Windows 10
- **Notable Version**: 1.4.0

### Current behavior

I’ve been working on a pretty long note/document. When I switched between different notes in different notebooks the note/document was suddenly gone. This is incredibly frustrating as I’ve lost several hours of work.

### Expected behavior

Not losing work.

**Comment by fabiospampinato** [comment] 2019-05-21 13:51
It sounds like a duplicate of #574, this particular issue should be fixed in v1.5.0 (the latest release currently available is v1.5.1).

We've also experienced some issues with the updater, maybe that's why you're still on v1.4.0? Not all of them are fixed yet probably, but as of v1.5.0 when an update fails the app prompts the user to update manually, which isn't ideal at all but it should mitigate these sorts of problems where users are running outdated versions.

**Closed by fabiospampinato** 2019-05-21 13:51 UTC

**Comment by alexanderte** [comment] 2019-05-21 14:02
I understand. Hopefully this isn’t an issue anymore.

Although I’m aware that there is a newer version, I haven’t upgraded yet. I don’t think I got any prompt about update, but I could be wrong.
