### ISSUE TITLE
Invalid markdown rendering for code snippets

### ISSUE THREAD

**Issue by omidkrad** [notable/notable#759] opened 2019-07-27 20:43 UTC
- **OS Version**: Windows 10 Pro (ver 1809)
- **Notable Version**: 1.6.2

### Current behavior

Use the following markdown:

```
```powershell
$BackupDir = "\\NAS\image\$ComputerName"
$BackupFileName = "$(Get-Date -Format yyyy-MM-dd) $ComputerName system-backup.vhdx"```
```

### Expected behavior

Since notable markdown rendering is based on *markdown-it* it should render the same way. Go to [markdown-it demo](https://markdown-it.github.io/) page and paste the above markdown. That should be the output you get in notable.

### Actual behavior

I get this:

```
$BackupDir = "\\NAS\image$ComputerName"
<span class="katex"><span class="katex-mathml"><math><semantics><mrow><mi>B</mi><mi>a</mi><mi>c</mi><mi>k</mi><mi>u</mi><mi>p</mi><mi>F</mi><mi>i</mi><mi>l</mi><mi>e</mi><mi>N</mi><mi>a</mi><mi>m</mi><mi>e</mi><mo>=</mo><mi mathvariant="normal">&quot;</mi></mrow><annotation encoding="application/x-tex">BackupFileName = &quot;</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.8888799999999999em;vertical-align:-0.19444em;"></span><span class="mord mathdefault" style="margin-right:0.05017em;">B</span><span class="mord mathdefault">a</span><span class="mord mathdefault">c</span><span class="mord mathdefault" style="margin-right:0.03148em;">k</span><span class="mord mathdefault">u</span><span class="mord mathdefault">p</span><span class="mord mathdefault" style="margin-right:0.13889em;">F</span><span class="mord mathdefault">i</span><span class="mord mathdefault" style="margin-right:0.01968em;">l</span><span class="mord mathdefault">e</span><span class="mord mathdefault" style="margin-right:0.10903em;">N</span><span class="mord mathdefault">a</span><span class="mord mathdefault">m</span><span class="mord mathdefault">e</span><span class="mspace" style="margin-right:0.2777777777777778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:0.2777777777777778em;"></span></span><span class="base"><span class="strut" style="height:0.69444em;vertical-align:0em;"></span><span class="mord">&quot;</span></span></span></span>(Get-Date -Format yyyy-MM-dd) $ComputerName system-backup.vhdx"
```

Notice on the first line the `\` before `$` sign is missing, and on second line it's rendered to some html.

**Comment by fabiospampinato** [comment] 2019-07-28 00:01
Duplicate of #727. This has been fixed already, the fix will be available in v1.7.

> Since notable markdown rendering is based on markdown-it it should render the same way. 

It is based on markdown-it, but we are implementing a few custom plugins on top of it. Nonetheless this was a bug in one of those plugins.

**Closed by fabiospampinato** 2019-07-28 00:01 UTC
