### ISSUE TITLE
Right Click -> Move to Trash deletes the wrong item

### ISSUE THREAD

**Issue by Croninja** [notable/notable#755] opened 2019-07-26 12:00 UTC
- **OS Version**: Windows 10 1903
- **Notable Version**: 1.6.2

### Current behavior

In Notes list, right click a note's Title -> Move to Trash. Notable moves the wrong Note to the trash - typically this appears to be the 3rd Note _before_ the desired note.

### Expected behavior

Correct deletion of a given note when right clicking + "Move to Trash"

**Comment by fabiospampinato** [comment] 2019-07-26 14:55
I can't reproduce.

Can you reproduce right after closing the app and re-opening it?

**Comment by Croninja** [comment] 2019-07-28 06:55
Yes - I was able to restart the app (even my computer) and have it happen again.

Unfortunately I can't seem to make it happen on my personal desktop. May have something to do with categories.. I'll report back if I'm able to get to the bottom of it.

**Comment by fabiospampinato** [comment] 2019-07-28 11:03
I'm attaching the default tutorial data directory, can you check if after switching to it you can still reproduce the issue?

[tutorial.zip](https://github.com/notable/notable/files/3439085/tutorial.zip)

**Comment by fabiospampinato** [comment] 2020-01-10 15:09
I'm going to assume this was caused by #794, as I don't know how to reproduce it otherwise.

If anybody can still reproduce this on v1.8.2 I'd be happy to reopen this.

**Closed by fabiospampinato** 2020-01-10 15:09 UTC
Labels: bug, needs more info
