### ISSUE TITLE
Support attachment from current folder of the file other than global "attachments" folder

### ISSUE THREAD

**Issue by ajit555db** [notable/notable#763] opened 2019-07-31 12:50 UTC
I organize a set of related notes inside a folder. That folder contains all the attachments too instead of keeping it in a global folder location.

### Feature description
The readme.md file references two images co-located in the readme.md file. The images does not show in notable app.
```md
# Hello World
Image 1 : A fabric image:
![](./fabric.png)

Image 2 : A trial image:
![](./trial.png)
```
Instead, I need to put these two images in "attachments" global folder and reference it like below:

```md
# Hello World

Image 1: A fabric image:  
![](@attachment/fabric.png)

Image 2:  A trial image:  
![](@attachment/trial.png)
```

### Feature motivation

This is more towards a truer markdown way of referencing files than using notable specific file referencing convention.

**Comment by fabiospampinato** [comment] 2019-08-01 12:24
I think this is actually a duplicate of https://github.com/notable/notable/issues/733, we supported this early on, then it broke in v1.6, then I fixed it but I haven't released v1.7 yet.

Feel free to reopen the issue if v1.7 doesn't actually fix this for you.

**Closed by fabiospampinato** 2019-08-01 12:24 UTC

**Comment by ajit555db** [comment] 2019-08-02 06:11
Thank you so much. In fact, I tried to search duplicate issue but somehow GitHub didn't suggest it.

Looking forward to check it out in v1.7.

My use case for Notable is as below:

1. Write and review the individual md content in VSCode.
2. Review all the md contents in Notable by tags, searching etc. 
3. Publish the content as a static site with templates from Hugo static site generator.

**Comment by fabiospampinato** [comment] 2019-08-03 12:41
@ajit555db that sounds like a relatively common use case, hopefully we'll be able to make it much better in the future, especially once we implement plugins #128.

Why are you writing the actual Markdown in VSCode rather than in Notable itself?

**Comment by ajit555db** [comment] 2019-08-04 04:38
Reasons not in particular order

-  I just discovered this wonderful product, Notable. Need to use it more to understand all the features.
- I hope that Notable would allow me to use all standard markdown features with all Notable specific frontmatter as optional. So creating new content or editing existing content in VSCode and viewing / editing it Notable would allow me to test that.
-  I already have tons of existing notes in markdown docs which gradually need to bring it into Notable, so need to get used to frontmatter conventions required for Notable. I have not yet explored the import functionality.
- I generally document along with code, so easier to do it in VSCode for primary, new docs creation. For non-code related or editing while previewing or changing the front matter contents (tags etc), Notable seems fine. Over a period of time, hopefully, would use Notable as a primary editor.

**Comment by fabiospampinato** [comment] 2019-08-05 09:18
> I hope that Notable would allow me to use all standard markdown features with all Notable specific frontmatter as optional.

The front matter isn't optional, as that's how we are storing metadata such as modification date and tags, but that should be relatively standard Markdown, meaning that modern Markdown renderers should support it too.

All "standard" Markdown features are supported, we have a few custom syntax plugins enabled, like for supporting LaTeX, but you don't have to use them.

> I have not yet explored the import functionality.

Importing Markdown notes would just copy over all their content and adding a front matter.

> Over a period of time, hopefully, would use Notable as a primary editor.

The app isn't feature complete yet, not by a long shot, but ideally it should provide a better note-taking experience than VSCode. 

Thanks for the feedback!
