### ISSUE TITLE
Keyboard shortcuts change depending on editor/preview mode

### ISSUE THREAD

**Issue by jsosulski** [notable/notable#683] opened 2019-06-07 10:15 UTC
- **OS Version**: Ubuntu 18.04
- **Notable Version**: 1.5.1

### Current behavior

In preview mode, Ctrl+Backspace is used to delete notes. In Edit/Split mode, Ctrl+Alt+Backspace is used.

### Expected behavior

Shortcuts stay the same, i.e. maybe Ctrl+Alt+Backspace for both?

**Comment by fabiospampinato** [comment] 2019-06-07 16:19
Duplicate of #532

**Closed by fabiospampinato** 2019-06-07 16:19 UTC
