### ISSUE TITLE
KaTeX parsing error

### ISSUE THREAD

**Issue by shutchinson** [notable/notable#748] opened 2019-07-19 23:02 UTC
- **OS Version**: Windows 10
- **Notable Version**: 1.6.2

### Current behavior

The following code block

```php
<?php
$a = array("foo" => 0, "bar" => 1);
foreach ($a as $key => $value) {
  // comment
  echo "{$key} => {$value}" . PHP_EOL;
}
```

produces

```
<?php
$a = array("foo" => 0, "bar" => 1);
foreach ($a as $key => $value) {
  // comment
  echo "{<p class="text-warning">[katex error: KaTeX parse error: Expected 'EOF', got '}' at position 4: key}̲ => {]</p>value}" . PHP_EOL;
}
```
because the parser thinks that the `$key` is trying to initiate an inline KaTeX syntax.

### Expected behavior

```php
<?php
$a = array("foo" => 0, "bar" => 1);
foreach ($a as $key => $value) {
  // comment
  echo "{$key} => {$value}" . PHP_EOL;
}
```

Issue #199 seems like it was supposed to fix this?

**Comment by fabiospampinato** [comment] 2019-07-19 23:07
Issue #199 was a closely related issue with a different solution.

It looks like we aren't able to detect the code block. I can't reproduce the issue when using fenced code blocks, the issue seem to occur only in unfenced code blocks, so perhaps for the time being use fenced code blocks instead.

Solving this reliably will most probably be tricky 🤔

**Comment by shutchinson** [comment] 2019-07-19 23:54
@fabiospampinato this was using fenced code blocks (i.e. three back ticks)

**Comment by fabiospampinato** [comment] 2019-07-20 00:02
@shutchinson Then I can't reproduce, can you attach a note that reproduces the issue for you?

**Comment by shutchinson** [comment] 2019-07-20 03:41
See attached. Uploaded as `.txt` as GitHub doesn't allow `.md`
[test.txt](https://github.com/notable/notable/files/3413209/test.txt)

**Comment by fabiospampinato** [comment] 2019-07-23 16:18
I fixed this issue when the code block is an unfenced code block.

But I'm still unable to reproduce the issue with fenced code blocks, not even in win10 (which shouldn't matter anyway) which is pretty strange.

I'm calling this fixed, but @shutchinson please do let me know if you'll still be able to reproduce the issue on v1.7 and I'll reopen this.

**Comment by fabiospampinato** [comment] 2019-07-23 16:19
Oh wait I can actually reproduce this if I'm using tildes for the fence (the provided notes uses backticks). Fix for this coming soon 👍

**Comment by fabiospampinato** [comment] 2019-07-23 16:22
And that's fixed too. Let me know if you'll still be able to reproduce the issue on v1.7 👍

**Closed by fabiospampinato** 2019-07-23 16:22 UTC
Labels: bug, katex

**Comment by shutchinson** [comment] 2019-07-23 16:24
Thanks.
Let me know when you push v1.7 up to the repo and I can test.

**Comment by fabiospampinato** [comment] 2019-07-23 16:27
@shutchinson I usually post a message on the [subreddit](https://www.reddit.com/r/notable) when I release a new version. Also you can watch for changes directly here on GitHub, just click the "Watch" button and then click "Releases only".
