### ISSUE TITLE
Find/search box inside a note

### ISSUE THREAD

**Issue by renanwillian** [notable/notable#916] opened 2019-11-18 20:03 UTC
### Feature description
Ctrl+F should be shortcut for opening an find/search box like in vscode:
![image](https://user-images.githubusercontent.com/30376796/69084546-3c4c7c00-0a23-11ea-8f34-c86616eea67a.png)

The find/replace box could be present as well:
![image](https://user-images.githubusercontent.com/30376796/69084982-12478980-0a24-11ea-9ce2-d91151fcdad1.png)

Selecting all results with Alt+Enter for multi-cursors edit would be awesome too.

Currently Ctrl+F is shortcut for the note search field and it could be changed for Ctrl+Shift+F.

### Feature motivation
Sometimes on big notes I have to copy its entire content and paste it into sublime text, just to be able to find something in it.

**Comment by fabiospampinato** [comment] 2019-11-19 00:43
Duplicate of #140.

This IMHO may be the single biggest obvious missing feature.

**Comment by fabiospampinato** [comment] 2019-11-19 00:43
> Sometimes on big notes I have to copy its entire content and paste it into sublime text, just to be able to find something in it.

That's not optimal, but you can just run a `Cmd+O` to get the note opened in your default text editor.

**Closed by fabiospampinato** 2019-11-19 00:43 UTC
