### ISSUE TITLE
auto complete in tags

### ISSUE THREAD

**Issue by bar4488** [notable/notable#846] opened 2019-10-01 14:08 UTC
## Feature description

i use this program for sometime and i love it.
one of the features that is the most important for me is the ability to tab complete while typing tags.

#### for example:
 if i have tags like "java/android/premissions"
i would like the program to show me avalible options and to navigate and complete them using arrows and tabs.

**Comment by fabiospampinato** [comment] 2019-10-01 14:09
Duplicate of #20

**Closed by fabiospampinato** 2019-10-01 14:09 UTC
