### ISSUE TITLE
Notable 1.8.3 doesn't install on Windows

### ISSUE THREAD

**Issue by kyldvs** [notable/notable#1021] opened 2020-01-21 19:40 UTC
- **OS Version**: Windows 10, Version 1809
- **Notable Version**: 1.8.3

### Current behavior

After updating to the latest version, or installing from a fresh download of the 1.8.3 installer I can no longer use notable. The exe is completely missing after the install.

In both cases I immediately got this dialog asking me to find the exe:

![Screenshot (28)](https://user-images.githubusercontent.com/1830497/72837034-a6131d00-3c42-11ea-9067-e5d3179523c7.png)

Then when browsing it looks in this location (but I also could not find an exe for notable anywhere else easily):

![Screenshot (30)](https://user-images.githubusercontent.com/1830497/72837069-b6c39300-3c42-11ea-9892-04a7918231c4.png)

### Expected behavior

Notable works.

---

(I was able to get notable working again by running the old 1.7.3 installer I had, I'll just hold off on updating again until this is resolved.)

**Comment by fabiospampinato** [comment] 2020-01-21 19:55
I think this is a duplicate of #1020, I'm crafting v1.8.4 right now.

**Closed by fabiospampinato** 2020-01-21 19:55 UTC

**Comment by fabiospampinato** [comment] 2020-01-21 20:16
Just released v1.8.4, it'd be great if you could confirm that the issue is fixed.

**Comment by kyldvs** [comment] 2020-01-21 20:19
Yes, I was able to install 1.8.4 successfully! Thanks for the quick fix

**Comment by fabiospampinato** [comment] 2020-01-21 20:20
Great, thanks for checking.
