### ISSUE TITLE
Blurry tags text when Notable is split screened.

### ISSUE THREAD

**Issue by spiral6** [notable/notable#595] opened 2019-04-03 08:09 UTC
Windows Version
- **Windows 10 17763**:
Notable Version
- **Notable 1.4.0**:

### Current behavior

Blurry tags and attachments text when Notable is split screened.
![image](https://user-images.githubusercontent.com/2887489/55463050-cabbdc80-55bd-11e9-8285-d31b7e227539.png)
![image](https://user-images.githubusercontent.com/2887489/55462966-a2cc7900-55bd-11e9-9720-68903b430bb0.png)

### Expected behavior

Clear tags and attachments text when Notable is split screened.
![image](https://user-images.githubusercontent.com/2887489/55463005-b4ae1c00-55bd-11e9-9472-32daa56a57f4.png)

**Comment by fabiospampinato** [comment] 2019-04-03 14:29
This sounds like a pretty obscure issue. The fact that the app might be in split-screen shouldn't matter, this is probably an Electron bug.

**Comment by evansan** [comment] 2019-04-03 19:52
Same issue on Linux.

**Comment by spiral6** [comment] 2019-04-06 03:32
It's not just on split-screen. It's just in normal Notable as well. Seems like a persistent issue.

**Comment by zenofx** [comment] 2019-04-12 05:35
I am experiencing the same problem on Fedora 30, but only in editing mode.

**Comment by fabiospampinato** [comment] 2019-05-03 00:34
Duplicate of #568, it should be fixed in master.

**Closed by fabiospampinato** 2019-05-03 00:34 UTC
Labels: bug
