### ISSUE TITLE
Ligatures in Markdown Preview

### ISSUE THREAD

**Issue by karbecker** [notable/notable#442] opened 2019-02-11 13:35 UTC
I think it would be nice to support ligatures like [Noty](https://github.com/fabiospampinato/noty) does, so we can write `->` and see an arrow glyph in the preview. It’s just an aesthetics thing, but since I’m using a lot of arrows it would be nice for me 😉

**Comment by RomanKornev** [comment] 2019-02-11 13:41
Already works by setting a custom `font-family` in devtools. 
Customization options for it #102 should come "soon" I hope.
![image](https://user-images.githubusercontent.com/5807561/52566790-b65c2e80-2e1b-11e9-95c0-3ba6710be822.png)

**Comment by fabiospampinato** [comment] 2019-02-11 16:34
Yeah let's close this as a duplicate of https://github.com/notable/notable/issues/102.

**Closed by fabiospampinato** 2019-02-11 16:34 UTC
