### ISSUE TITLE
An error occurred: Unexpected identifier

### ISSUE THREAD

**Issue by taneishamitchell** [notable/notable#804] opened 2019-08-29 09:39 UTC
- **OS Version**: darwin 17.7.0
- **Notable Version**: v1.5.1

```
/Applications/Notable.app/Contents/Resources/app.asar/node_modules/dagre-d3-renderer/lib/label/add-html-label.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import util from '../util'
                                                                                                                                                                  ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInThisContext (vm.js:314:10)
    at Module._compile (internal/modules/cjs/loader.js:742:26)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
```

**Comment by fabiospampinato** [comment] 2019-08-29 11:12
@taneipoo You should update to v1.7.3

It looks like this issue is somewhat related to Mermaid, did you have a Mermaid diagram in your note? If so can you post said note so that I can reproduce this?

**Comment by taneipoo** [comment] 2019-08-30 03:22
Hi @fabiospampinato all I did was compile the source for macOS & try to open one of the tutorial pages `05 - Notes` seem to be the problem child.

**Comment by fabiospampinato** [comment] 2019-08-30 10:15
@taneipoo Can you check if you can reproduce the issue on v1.7.3? I think this might be fixed already.

**Comment by fabiospampinato** [comment] 2020-01-12 13:59
Duplicate of #708

**Closed by fabiospampinato** 2020-01-12 13:59 UTC
Labels: needs more info
