### ISSUE TITLE
Application is not running

### ISSUE THREAD

**Issue by dector** [notable/notable#85] opened 2018-12-28 15:08 UTC
Hi. App isn't running on my machine. See some details below. Let me know if you'll need additional information.

Thanks.

---

**App version**: 1.0.1
**Build**: `Notable.1.0.1.AppImage`
**Environment**: Debian 9.5

**Actions**:
```
$ ./Notable.1.0.1.AppImage
```

Then pressed "Yes"/"No" (tried both ways) in AppImage dialog.

**Expected result**:
  - Notable app is displayed.
  - _(Probably some logs in terminal)_.

**Actual result**:
  - Notable app isn't displayed.
  - Terminal has:
```
Checking for update
Generated new staging user ID: d66242b8-8665-5f89-8410-c92525ee017a
Update for version 1.0.1 is not available (latest version: 1.0.1, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
```
  - Process is running.

---

**App version**: 1.0.1
**Build**: `notable_1.0.1_amd64.deb`
**Environment**: Debian 9.5

**Actions**:
```
# dpkg -i notable_1.0.1_amd64.deb
$ notable
```

**Expected result**:
  - Notable app is displayed.
  - _(Probably some logs in terminal)_.

**Actual result**:
  - Notable app isn't displayed.
  - Terminal has:
```
APPIMAGE env is not defined, current application is not an AppImage
```
  - Process is running.

---

**Comment by dector** [comment] 2018-12-30 18:13
Tried to build from sources

```
// git clone; cd notable

$ git rev-parse HEAD
2a8c7b21e509a2c0fa420cf3f82128d9a0fe1298

$ npm run build:linux
```

And run:
```
$ releases/Notable\ 1.0.1.AppImage
// (Process is running, app hasn't been started)

$ releases/linux-unpacked/notable
// (Process is running, app hasn't been started)
```

Tried to disable checking for autoupdate in `app.ts`. No luck either.

However, I've succeeded to run development version with
```
$ npm run dev
```

**Comment by anlutro** [comment] 2019-01-02 15:56
Same problem here.

**Comment by polak785** [comment] 2019-01-03 16:59
Same issue on `Ubuntu 18.04`

**Comment by fabiospampinato** [comment] 2019-01-03 17:08
I'm not sure how to fix this, if you guys can help pin-point the issue, or even better update the electron-builder configuration to fix this, I'd be great.

**Comment by dector** [comment] 2019-01-04 17:39
_Note: Seems that [router url](https://github.com/fabiospampinato/notable/blob/master/src/main/windows/route.ts#L27) isn't loading properly even if it is hardcoded._

**Comment by krankin** [comment] 2019-02-01 01:59
Does the app launch correctly if you run it from the Desktop (i.e. click on the AppImage) instead of running it from the terminal?  
We had this issue today with a different app and we were able to run from the command line by redirecting the terminal output and backgrounding the app
` $ ./yourApp.AppImage >/dev/null &`

**Comment by anlutro** [comment] 2019-02-03 23:42
For me this seems to be fixed in the most recent release(s), but I have no idea why.

**Comment by polak785** [comment] 2019-02-06 08:33
I tryied to open Notable from Application launcher and from the console and this now working. Thus I don't know since when. I'm still on Ubuntu 18.04 with latest updates.

I still have the message log `APPIMAGE env is not defined, current application is not an AppImage` when I start it from Application launcher and I also the message log `GtkDialog mapped without a transient parent. This is discouraged.`. I didn't have these when I start it from console.

**Comment by fabiospampinato** [comment] 2020-01-12 13:51
Can you guys still reproduce this? I think this might got fixed at some point by updating our `electron-builder` dependency.

**Comment by dector** [comment] 2020-01-13 05:50
@fabiospampinato 1.8.2 works for me, thanks.

**Closed** 2020-01-13 12:40 UTC
Labels: can't reproduce, help wanted, needs more info
