### ISSUE TITLE
Light arrows and borders for mermaid diagrams

### ISSUE THREAD

**Issue by Tauka** [notable/notable#843] opened 2019-09-28 12:05 UTC
### Feature description

Light arrows and borders for mermaid diagrams in dark mode

### Feature motivation

Currently, dark arrows in dark mode are hardly visible

![image](https://user-images.githubusercontent.com/15087247/65816133-e117bd80-e219-11e9-884f-5c035102438b.png)

Mermaid support in notable is great, as I use notable for taking notes from things I learn, I often find mermaid very helpful, however it is hard to use in dark mode

**Comment by Tauka** [comment] 2019-09-28 12:07
Don't think it's gonna be too hard, I probably can PR for this if it's welcome

**Comment by fabiospampinato** [comment] 2019-09-28 12:10
I'm closing this as a duplicate of #295. It's not difficult to fix this specific issue, but the general solution in theming the entirety of mermaid to our likings, if you'd like to help with that that'd be great.

**Closed by fabiospampinato** 2019-09-28 12:10 UTC
