### ISSUE TITLE
Paste multiple times after changing data directory

### ISSUE THREAD

**Issue by gregunz** [notable/notable#813] opened 2019-09-09 08:22 UTC
- **OS Version**: Windows 10 Pro
- **Notable Version**: 1.7.3

### Current behavior
After changing the data directory, whenever you paste something, it does it twice.

1. Open Notable
2. Notable > Change Data Directory
3. Paste anything (text or note) in a note

And if you repeat the second step n times, it will paste n+1 times what you copied.
This suggest there is sort of a duplicate instance of the editor running which could cause other bugs as well.

### Expected behavior
Paste should be done once only.

### Quick fix
Restart the app.

**Comment by fabiospampinato** [comment] 2019-09-09 12:25
Duplicate of #779.

Can you reproduce this reliably each time even after restarting the app?

**Closed by fabiospampinato** 2019-09-09 12:25 UTC

**Comment by gregunz** [comment] 2019-09-10 00:10
Sorry for the duplicate.

I was able to reproduce it. But not reliably.
