### ISSUE TITLE
Mac OS X 10.15.1 - cmd-v pastes text twice into editor

### ISSUE THREAD

**Issue by osmsnbey** [notable/notable#938] opened 2019-12-06 07:35 UTC
I love Notable on Mac, but it has a very annoying bug:

I copy a text (fe. an url from a browser f.e. https://opensource.com/article/19/10/building-container-images-ansible) and then paste it with CMD-V into the editor -> i get it twice (fe. https://opensource.com/article/19/10/building-container-images-ansiblehttps://opensource.com/article/19/10/building-container-images-ansible) instead of once.

Very annoying bug!

Thank you for working on it!

**Comment by liwangqiang** [comment] 2019-12-06 11:11
Seems duplicate of #779 .
To restart the app may fix this temporarily.

**Closed** 2019-12-11 15:43 UTC
