### ISSUE TITLE
Add localization

### ISSUE THREAD

**Issue by mHatsune** [notable/notable#1195] opened 2020-06-19 11:58 UTC
[Crowdin essentials free for public projects](https://crowdin.com/pricing#annual)
[Crowdin for awesome non-profit projects](https://crowdin.com/page/open-source-project-setup-request)

https://github.com/notable/notable/issues/126

**Comment by fabiospampinato** [comment] 2020-06-19 13:47
Duplicate of #126

**Closed by fabiospampinato** 2020-06-19 13:47 UTC
