### ISSUE TITLE
checkbox check and un-check action will shift page up

### ISSUE THREAD

**Issue by tundra2002** [notable/notable#554] opened 2019-03-15 14:56 UTC
- **OS Version**: macOS Majove 10.14.3 
- **Notable Version**: 1.4.0

### Current behavior
- Create a checkbox
```
- [ ]
```
- In view mode check or un-check the checkbox
- This action will take you to the top of the page

### Expected behavior
Checking and un-checking the checkbox in view mode should not shift the page up to top.

**Comment by fabiospampinato** [comment] 2019-03-15 15:34
Duplicate of #446.

**Closed by fabiospampinato** 2019-03-15 15:34 UTC
