### ISSUE TITLE
Unintended duplication of a note in a completely different note

### ISSUE THREAD

**Issue by Belz** [notable/notable#514] opened 2019-03-05 18:58 UTC
- **OS Version**: Windows 10
- **Notable Version**: 1.3.0

### Current behavior

Sometimes if you are in edit mode and click on many different notes, it is possible that the next note you click will be overridden with the content of the previous selected note, ending with complete loss of data. 
Can't even undo it.

### Expected behavior

When clicking on different notes in edit or preview mode nothing should be changed unless I specifically change it myself.

**Comment by fabiospampinato** [comment] 2019-03-05 19:03
Duplicate of https://github.com/notable/notable/issues/425#issuecomment-461461126.

It should be fixed in the master branch (new release coming hopefully later this week), it would very helpful if you could check if you can reproduce it from the master branch.

**Closed by fabiospampinato** 2019-03-05 19:03 UTC
