### ISSUE TITLE
Inconsistent List Indent Tab/Spaces

### ISSUE THREAD

**Issue by Philiphlop** [notable/notable#654] opened 2019-05-09 07:58 UTC
- **OS Version**: Windows 10, 1803, 17134.706
- **Notable Version**: 1.4.0

### Current behavior

This text

```
- New list
- Item 2
  - Sub1 1 tab space
  - Sub2 1 tab space
    - Sub 3 1 extra tab space
    - Sub 4 total of 2 tab spaces
```

Here you will see upon save that the list 2nd indent is not indented, despite having pressed tab twice and producing 4x spaces. 

![Here is a GIF of this too](https://i.imgur.com/MSEBYum.gif)
[Here is a GIF of this too](https://i.imgur.com/MSEBYum.gif).

### Expected behavior

Consistent multiplication of tabs or spaces to produce indented list. Instead we have to create this inconsistent tabs/spaces to produce the rendered indent.

```
- New list
- Item 2
  - Sub1 1 tab space
  - Sub2 1 tab space
      - Sub 3 2 extra tab space
      - Sub 4 total of 3 tab spaces
```

**Comment by fabiospampinato** [comment] 2019-05-09 11:20
Duplicate of #165, thanks for the detailed issue report 👍

**Closed by fabiospampinato** 2019-05-09 11:20 UTC
