### ISSUE TITLE
Auto-refresh changes from external editor

### ISSUE THREAD

**Issue by wookayin** [notable/notable#489] opened 2019-02-23 18:57 UTC
- **OS Version**: macOS Mojave
- **Notable Version**: Notable 1.3.0

A similar issue might be #150.

### Current behavior

* OK: Changes from Notable is automatically synchronized as the file is updated or saved (you can see Typora in the right automatically refreshes the file upon an event)
* Bug: Changes from external editor (Typora in the below screenshot, or any other editors such as vim, etc.) are not synchronized back. When (1) the file gets updated or (2) Notable gets window focus --- Notable does not refresh the file.

![Screenshot](https://user-images.githubusercontent.com/1009873/53290530-459a0800-3773-11e9-8f81-a1f955b12bcb.gif)

### Expected behavior

It should refresh the file, whenever file is updated (preferred), or at least whenever it gets a window focus. I think the behavior described in #150 is exactly what it should look like.

**Comment by fabiospampinato** [comment] 2019-02-23 19:23
This would be a bug, but the problem in your example is: are we sure Typora is actually updating the file? If you open it from the file explorer with a separate program will you see the changes?

**Comment by wookayin** [comment] 2019-02-23 19:26
Of course! In this example the default app for markdown files was Typora (i.e. <kbd>Cmd-O</kbd>) and you can see 'Edited' disappeared in its title bar because it saved the file. From the Finder, vim, etc., I can confirm that file is actually updated.

**Comment by fabiospampinato** [comment] 2019-02-23 19:49
I can't reproduce the problem:

![typora](https://user-images.githubusercontent.com/1812093/53291000-7ea29e80-37ac-11e9-990e-118226f18b72.gif)

**Comment by wookayin** [comment] 2019-02-23 20:16
That's interesting. Actually I found it is sometimes working (synchronized) -- after fresh restart --- and sometimes not working. I am not how to sure how to reproduce this, but my gut feeling is that when I do in a bidirectional manner (i.e. edit from Notable, then edit from Typora, then edit from Notable, and so on) it starts to happen.

**Comment by wookayin** [comment] 2019-02-23 20:20
I also found similar thing happens between Typora and Vim. So I suspect this might not be due to a bug of notable, but because of some weird things about filesystem event...

**Comment by fabiospampinato** [comment] 2019-02-23 20:24
@wookayin Could you check if an app like [Atom](https://atom.io) is able to detect the changes to the file? They are using a more advanced file system watcher then us, and I'm about switching to it at some point in the future.

**Comment by wookayin** [comment] 2019-02-24 02:26
I think Atom pretty does the job very well. Some additional features I'd like to suggest:

- If a change from outside is detected (hence potential risk of overwriting), Notable should give a warning (and ask a confirm).
- I wish there were a feature (say <kbd>Cmd-R</kbd>) to force-refresh and reopen the current note.

**Comment by fabiospampinato** [comment] 2019-02-24 02:31
> * If a change from outside is detected (hence potential risk of overwriting), Notable should give a warning (and ask a confirm).

This is implemented already in the master branch. A prompt is shown if there are unsaved changes that may be overwritten.

> * I wish there were a feature (say Cmd-R) to force-refresh and reopen the current note.

I think it would be better to fix the root cause and make the file system watcher more reliable.

**Comment by df-dev** [comment] 2019-03-02 18:58
I am using vs code for all editing, notable will not reflect the changes until I close and open it again.

**Comment by jeff9315** [comment] 2019-03-11 15:48
This is becoming **extremely** frustrating for me. Whenever I'm in Notable and use the default editor to make and save a change, and come back to Notable, the change is **not** there unless I close and reopen Notable. My default editor is [Ghostwriter](https://github.com/wereturtle/ghostwriter) which is much nicer for editing because it automatically continues bulleted or numbered lists and has keyboard shortcuts for bold, italics, etc. But it doesn't have some of the really nice features that Notable has for jumping around between documents.

So, my current workflow is to use Notable as an index to my documents and for simple edits ... and to use Ghostwriter for more detailed edits. I'm hoping that eventually Notable's editor will be enhanced to allow more capabilities or plugins, but until that occurs, I'm stuck with this workflow.

**Comment by fabiospampinato** [comment] 2019-03-11 15:52
@jeff9315 what OS are you on? File system watching might be less reliable on Windows I think.

All the features you mentioned are going to get implemented at some point, and plugins #128 I'm particularly exited about myself, I think they will become a big part of what Notable offers, but we aren't quite there yet.

**Comment by jeff9315** [comment] 2019-03-11 16:33
I'm on Windows 10. The file is on a network drive.

I'm excited when any product gets plugins because then not everything falls to the main developer to have to do.

**Comment by jeff9315** [comment] 2019-03-23 12:54
@fabiospampinato ... After updating Notable to 1.4.0, there is a somewhat improved behavior. Maybe this will give you more of a clue as to what is happening. The 1st time I edit a note using the external/default editor, save it, and come back to Notable, the change appears. However, reopening the external/default editor, making a 2nd change, saving it, and coming back to Notable ... the change is **not** reflected.

However, if I use the middle pane of Notable to go to a different document and then back to my previous one, the change from the external editor IS consistently reflected.

In addition, any YAML changes to tags or title through an external/default editor **are** immediately and consistently appear.

**Comment by fabiospampinato** [comment] 2019-03-23 14:48
@jeff9315 Good feedback, if the note is refreshed after if you switch to it later then we might have a bug somewhere else (not in filesystem watcher) in the codebase, thanks!

**Comment by fabiospampinato** [comment] 2020-01-10 21:23
A fixed a couple of bugs regarding this, I was occasionally able to reproduce the issue in question before but now I can't anymore, so I'm closing this issue.

I've also spotted another bug related to this that may lead to a similar behavior, but it can only be triggered under more complex scenarios so I don't think it was responsible for this issue, I'll take care of that too but it's quite a deep bug, I'll have to rewrite a significant portion of our state management library to fix it, which fortunately I was planning on rewriting anyway for different motives (performance mostly).

**Closed by fabiospampinato** 2020-01-10 21:23 UTC
Labels: bug

**Comment by 9z0** [comment] 2021-02-08 23:43
For some reason, change detection works in 1.8.4 but not 1.9.0 beta 1.

Windows 10

**Comment by fabiospampinato** [comment] 2021-04-01 20:03
@9z0 I think that's a known issue I haven't fixed yet!
