### ISSUE TITLE
Toggle Preview-Edit Mistake

### ISSUE THREAD

**Issue by infosisio** [notable/notable#524] opened 2019-03-08 18:40 UTC
When toggling from Preview to Edit mode in a long note, even though Preview scroll starts from the top of the page, as soon as the switch to edit has been made, it starts scrolling from way below. 

It looks like it's caching the scroll position of the edit mode but the worst thing is how the scroll bar is deceiving, showing it's at the start while it may be in the middle or in the end of the note.

Platform: Ubuntu 18.04 (installed from the .deb)

**Comment by fabiospampinato** [comment] 2019-03-09 00:29
> It looks like it's caching the scroll position of the edit mode

Yes, we are trying to preserve as much state as possible when toggling preview and edit mode.

> but the worst thing is how the scroll bar is deceiving, showing it's at the start while it may be in the middle or in the end of the note.

🤔 This should be fixed since our recent switch to Monaco #203. Let me know if you can still reproduce this issue in v1.4 (it's going to be released in a few days).

**Comment by infosisio** [comment] 2019-03-09 00:49
@fabiospampinato Thank you! I meant to say "the bad thing", not the worst :)

**Comment by fabiospampinato** [comment] 2019-05-03 00:22
I think this got fixed with the switch to Monaco #203

**Closed by fabiospampinato** 2019-05-03 00:22 UTC
Labels: bug, help wanted
