### ISSUE TITLE
Evernote notes with titles containing punctuation characters will not be correctly imported

### ISSUE THREAD

**Issue by Anzan** [notable/notable#470] opened 2019-02-20 05:48 UTC
- **OS Version**: Windows 10
- **Notable Version**: 1.3

### Current behavior

While you export notes from a notebook in Evernote to the .enx format and import it in Notable, if the title of a specific note contains invalid characters for a filename in Windows, such as colon, the export fail completely for that note and just leave an empty file with an incomplete filename.

### Expected behavior

Some punctuation or special characters found in titles that are invalid (or even uncommon) in filenames on most OS should be probably ignored in order to create a valid file.

**Comment by fabiospampinato** [comment] 2019-02-20 16:41
Duplicate of https://github.com/fabiospampinato/enex-dump/issues/5.

**Closed by fabiospampinato** 2019-02-20 16:41 UTC
