### ISSUE TITLE
Italics messes us exported pdf file

### ISSUE THREAD

**Issue by ay-shimizu** [notable/notable#1340] opened 2020-10-17 05:38 UTC
- **OS Version**: macOS Catalina
- **Notable Version**: 1.8.4

### Current behavior

I've noticed that whenever I have at least one instance of an italicized word in markdown (using `*` or `_` or `<i>`), the exported PDF file converts all the text into gibberish/garbled text. Text wrapped around code blocks is okay. 

Example screenshot of PDF file showing current behavior:
<img width="659" alt="italics_issue" src="https://user-images.githubusercontent.com/32444732/96329352-07bdb780-101a-11eb-91a5-1b33e68e076c.png">

To reproduce the issue, use italics in a file then export the file to a PDF. 

### Expected behavior

The markdown file should properly be exported into a pdf file without turning the text into a bunch of gibberish/garbled text.

**Comment by fabiospampinato** [comment] 2020-10-21 00:42
Duplicate of https://github.com/notable/notable/issues/1207.

**Closed by fabiospampinato** 2020-10-21 00:42 UTC
