### ISSUE TITLE
I do not get all Tutorial files created on Windows 10 on first launch

### ISSUE THREAD

**Issue by rluiten** [notable/notable#406] opened 2019-02-02 02:06 UTC
I am new to Notable having stumbled upon it last night.
I was confused at first till I figured out I wasn't getting all the tutorial files corretly.

- **OS Version**:
Windows 10 Version 1803.

- **Notable Version**:
Notable Version 1.3.0 
Unpacked and run from the Release https://github.com/fabiospampinato/notable/releases/download/v1.3.0/Notable-1.3.0-win.zip

### Current behavior

On first launch of Notable (there is no .notable.json file or .notable folder in my home directory)
It prompts me to ask for data directory.
I select the Use Default button, and it opens Notable.
Notable shows the default tutorial notes, but they are not all there they do not get created completely as in the following image capture.

![image](https://user-images.githubusercontent.com/670472/52158264-485c8c80-26e2-11e9-848a-17c987336742.png)

It is consistent if I start from no configuration I always get only these files no others.

If I select menu Help/Tutorial then select Import notes from prompt I then get all the files as show in the following image capture.

![image](https://user-images.githubusercontent.com/670472/52158280-73df7700-26e2-11e9-8515-a43821ffe5fb.png)

### Expected behavior

I expect all of the the initial tutorial to be setup on first launch.

**Comment by fabiospampinato** [comment] 2019-02-02 13:52
Sounds like a bug, can you give more details about your computer? Like is it particularly old perhaps?

**Comment by rluiten** [comment] 2019-02-02 22:57
The machine is 3 years old.
It has an Intel 6700K CPU, Nivia 970 GPU, a 1TB Samsung 960 Pro system drive, and 3 other multi terrabyte data drives, it has 64GB ram and is not overclocked, and is very stable.
The Win10 Operating System install is roughly a year old.

I have noticed another bug.

Using the 1.3 build whenever I start Notable and then Exit it it leaves behind 2 Notable.exe processes in the visible in task manager. I mainly noticed this because if I have started and stopped Notable once and left behind the 2 Notable.exe tasks that the next time i run Notable it takes a noticable longer time to  start and render the content of the initial loaded window, of the order of a second or so. Killing off the left over processes before launching Notable again means the next launch starts at a normal speed.

As a test I started and stopped notable 4 times and it had left behind 8 Notable.exe tasks, so there is a shutdown cleanup issues somewhere as well. This is entirely repeatable and consistene on my system.

I've been a developer for 30 years, and done a lot of javascript typescript react redux bootstrap with node build tools and webpack tools in the last 3 years, though I havn't targetted atom only browsers before.

I have pulled the notable source repository, I may poke around a bit to see if I can figure out what is happening. However the default setup for dev and build does not just work on windows.

I get an error as `npm install` wants node-gyp for this install `ttf2woff2@2.0.3 install D:\Dev\test\notable\node_modules\ttf2woff2`.  I do not have this system setup with full compiler tool chain for native node_modules, but that hasnt been an issue in the last few years, This error may not matter much in terms of getting a local dev build going, as it does launch `npm run dev` suffficiently to get things going, though by deafult the dev build does not attempt to install tutorial documents due to
another problem as the step `npm run tutorial` fails on my machine because I do not have a command line tool `zip` anywhere on my system (windows users commonly will not have these tool even if they have git for windows installed which comes with a number of unix command line tools). Again i can just work around this as needed, but make debugging for tutorial install one further step away. I will probably just grab the tutorial.zip file from my unpacked Notable-1.3.0-win folder to test temporarilly. 

I have 2 other windows 10 machines one of which is an almost unmodified Windows 10 Pro on a stable Dell notebook with 32GB of ram it was clean reinstalled a few months ago. I plan to see if it behaves differently in the near future.

**Comment by fabiospampinato** [comment] 2019-02-02 23:13
@rluiten Thanks for looking into this!

> Using the 1.3 build whenever I start Notable and then Exit it it leaves behind 2 Notable.exe processes in the visible in task manager

I can't reproduce this under macOS. I'll try to reproduce it under a VM.

> I get an error as npm install wants node-gyp for this install ttf2woff2@2.0.3 install D:\Dev\test\notable\node_modules\ttf2woff2

I don't think I have node-gyp installed in my Windows VM and I haven't seen that error 🤔 

> npm run tutorial fails on my machine because I do not have a command line tool zip anywhere on my system

Yeah that's another problem. I already spent some time crafting that script, unfortunately making all the build steps totally cross-platform just isn't a priority for now. In a normal situation, where one's not trying to debug a problem with the tutorial notes, the lack of the tutorial archive shouldn't matter.

> Ok I tested with a dev build launch and it does the same partial install of tutorial files once I copied the the release 1.3.0 tutorial.zip into the right place in the dist folder.

Weird. You might want to put a few `debugger` statements [here](https://github.com/fabiospampinato/notable/blob/2bb14e86633681735882da5d74d7d2d9d89d8fc4/src/renderer/containers/main/tutorial.ts#L36-L39) and maybe [here](https://github.com/fabiospampinato/notable/blob/2bb14e86633681735882da5d74d7d2d9d89d8fc4/src/renderer/utils/watcher.ts#L85) as well.

**Comment by rluiten** [comment] 2019-02-03 05:08
Tried it on my Win 10 Pro notebook.
It leaves behind 2 Notable.exe processes when you exit Notable and for a previously not run notable state the set of tutorial files which are created can be seen in following attached capture. It is a different set to my desktop Win10 PC and not complete either.

![image](https://user-images.githubusercontent.com/670472/52172916-520af080-27c5-11e9-971a-8acf9eae6ce6.png)

**Comment by rluiten** [comment] 2019-02-05 11:09
A possible fix for class `Tutorial` method `import` could be.
I did this to minify the places changed in the code to check behaviour and appears to resolve my issue.

```js
  import = async () => {

    const cwd = Config.cwd;

    if ( !cwd ) return Promise.resolve();

    const tutorialPath = path.join ( __static, 'tutorial.zip' );

    try {
      return await pify ( unzip ) ( tutorialPath, { dir: cwd });
    }
    catch (e) {
      
      Dialog.alert ( 'Failed to import the tutorial notes, please report the issue' );

      throw Promise.reject( new Error( 'Failed to import the tutorial notes, please report the issue' ) );
    }
  }
```

I think I would move the Dialog.alert back to the class `CWD` method `set` so that it setups error catch of the import() to raise the Dialog.

**Comment by fabiospampinato** [comment] 2019-02-05 12:42
@rluiten nice debugging, I'll include a fix for this in the next release!

**Closed** 2019-02-09 17:14 UTC
Labels: bug
