### ISSUE TITLE
render markdown while typing 

### ISSUE THREAD

**Issue by 3d4m-vladimir** [notable/notable#1568] opened 2022-01-11 17:32 UTC
Render and edit markdown at the same time. For example, look at https://typora.io/ . 

I found it very useful and intuitive. 
The advantage is that users do not need to change modes constantly and renderer can render notes partially.

**Comment by MMK21Hub** [comment] 2022-01-21 17:17
Duplicate of #284

**Closed** 2022-01-21 19:46 UTC
