### ISSUE TITLE
Drag and Drop to rearrange tasks

### ISSUE THREAD

**Issue by bkonia** [notable/notable#1404] opened 2020-12-07 04:25 UTC
I'd like to be able to rearrange tasks in a task list using drag and drop in the Preview window. [This feature is supported by Github](https://github.blog/2016-05-27-drag-and-drop-tasks-in-markdown-task-lists/) and would be extremely useful in Notable.

![e911b800-2422-11e6-8204-568f61456675](https://user-images.githubusercontent.com/2266423/101309478-882eb680-381a-11eb-89db-5979fc7f473a.gif)

**Comment by fabiospampinato** [comment] 2020-12-07 22:22
Duplicate of https://github.com/notable/notable/issues/288

**Closed by fabiospampinato** 2020-12-07 22:22 UTC
