### ISSUE TITLE
Support for back / forward buttons (Notes history)

### ISSUE THREAD

**Issue by KewlCat** [notable/notable#558] opened 2019-03-15 23:50 UTC
### Feature description

"back" and "forward" buttons in the button bar and/or keyboard shortcuts (alt+left and alt+right) and/or support for mouse back/forward buttons, in order to navigate through the notes you opened before ("history")

### Feature motivation

I navigate a lot between notes, and I intend to use Notable to create a knowledge base / wiki since internal links are super handy. Under these circumstances it's difficult to go back to the page you were before clicking a link, or navigate forward if you were editing a note and want to check again the cheatsheet you had under your eyes right before going back to writing your note... (yes, I kept a few pages from the tutorial)

Please ? :-)

**Comment by fabiospampinato** [comment] 2019-03-16 00:46
Duplicate of #144.

**Closed by fabiospampinato** 2019-03-16 00:46 UTC
