### ISSUE TITLE
Error report: Cannot read property 'source-url' of undefined

### ISSUE THREAD

**Issue by jindrichjindrich** [notable/notable#1091] opened 2020-03-21 14:51 UTC
- **OS Version**: win32 10.0.18362
- **Notable Version**: v1.8.4

```
TypeError: Cannot read property 'source-url' of undefined
    at EnexNote.getMetadata (file:///C:/Users/jindrich/AppData/Local/Programs/notable/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:185842)
    at async EnexNote.get (file:///C:/Users/jindrich/AppData/Local/Programs/notable/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:3578)
    at async EnexProvider.dump (file:///C:/Users/jindrich/AppData/Local/Programs/notable/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:3469)
    at async Object.dump (file:///C:/Users/jindrich/AppData/Local/Programs/notable/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:201681)
    at async import_Import.import (file:///C:/Users/jindrich/AppData/Local/Programs/notable/resources/app.asar/renderer/renderer.js:2:24287)
```

**Comment by fabiospampinato** [comment] 2020-03-21 14:52
Duplicate of https://github.com/notable/dumper/issues/30

**Closed by fabiospampinato** 2020-03-21 14:52 UTC
