### ISSUE TITLE
Follow selected bullets, numbering and enhancement to common symbols

### ISSUE THREAD

**Issue by mHatsune** [notable/notable#1223] opened 2020-07-04 21:14 UTC
When user start to write a list using bullets or other guide using numbers; unfortunately notable doesn't make our work easy but other note taking softwares usually suggest the next bullet or number. 
That also belong to common symbols similar brackets (eg: auto close the bracket)

**Comment by fabiospampinato** [comment] 2020-07-05 13:49
Duplicate of #88

**Closed by fabiospampinato** 2020-07-05 13:49 UTC
