### ISSUE TITLE
Clicking another note while editing overwrites clicked note

### ISSUE THREAD

**Issue by hyatt-e** [notable/notable#459] opened 2019-02-15 17:07 UTC
- **OS Version**: windows
- **Notable Version**: 1.3.0

### Current behavior

In Edit mode on a note (let's call it note-1)
Click on a note (note-2) in the sidebar
Note-1 (note being edited) will overwrite note-2 (note clicked on in sidebar)

### Expected behavior

Note-1 saves, and then note-2 is now focused
OR
Some warning or pop-up saying that you're note isn't saved/you're in edit mode and can't switch notes
Maybe even hide the sidebar while in edit mode?

This looks similar to [#322](https://github.com/notable/notable/issues/322) just without creating a new note. 
Seems like something that would've been caught before, so I'm sorry if this is a repeat but I can't find an issue that matches this.

**Comment by moqs001** [comment] 2019-02-18 14:01
I think the simpliest solution would be, to just disable edit mode when focus leaves the edit area.

**Comment by fabiospampinato** [comment] 2019-02-18 14:07
@moqs001 We don't want to do that, as some people might prefer to just be in edit mode most of the time.

**Comment by zakariamehbi** [comment] 2019-02-18 16:39
Had the same issue a few minutes ago, lost a big file.

**Comment by OndrejMarsalek** [comment] 2019-02-19 11:40
This just happened to me with version 1.3.0 on Linux. I had the data on Dropbox and thus was able to recover the deleted file.

**Comment by hyatt-e** [comment] 2019-02-19 14:12
Honestly forgot I had my notes saved in dropbox until you said that. Was able to recovery my file as well.
Thanks for the reminder @OndrejMarsalek !

**Comment by GeorgeHicks1** [comment] 2019-02-20 10:26
I have the same issue

**Comment by Anzan** [comment] 2019-02-21 02:42
on Windows 10, Notable 1.3, it just happened to me too, a note was in editing mode, I just browsed around and it overwrote 4-5 notes with the content of that note. It's a dangerous bug!

**Comment by erisman20** [comment] 2019-02-22 22:25
Lost a lot of notes due to this issue as well

**Comment by fabiospampinato** [comment] 2019-02-23 21:14
Closing as duplicate of #425 (https://github.com/notable/notable/issues/425#issuecomment-461461126)

**Closed by fabiospampinato** 2019-02-23 21:14 UTC
Labels: bug
