### ISSUE TITLE
Encryption or Locked notes

### ISSUE THREAD

**Issue by maximo30** [notable/notable#1328] opened 2020-10-04 23:49 UTC
I just saw your project for the first time and it is pretty good, imagine having the ability to lock notes with a password, the same way Mac notes does. So the files saved will be encrypted, independently from where you are storing them for syncing. As you say Dropbox, you will be the only one with access to your data.  

Let me know what do you think, maybe I can contribute.

**Comment by fabiospampinato** [comment] 2020-10-05 00:04
Duplicate of #7

**Closed by fabiospampinato** 2020-10-05 00:04 UTC
