### ISSUE TITLE
Remember split-view

### ISSUE THREAD

**Issue by lsascha** [notable/notable#490] opened 2019-02-24 15:00 UTC
### Feature description

Currently when i open the split-view and close the app, the setting that i want to use split-view is not remembered and i only see the preview again at the next start.

### Feature motivation

So i can see the source and preview at the same time always without switching back and forth

**Comment by fabiospampinato** [comment] 2019-02-24 15:03
Duplicate of #339

**Closed by fabiospampinato** 2019-02-24 15:03 UTC
