### ISSUE TITLE
Auto updater: missing setting for disabling it

### ISSUE THREAD

**Issue by jpsnyder** [notable/notable#746] opened 2019-07-17 12:54 UTC
I'm using notable on a machine not connected to the internet. Every morning I see notifications stating that it failed to resolve the update server and it opens up a browser tab to your github homepage. 

Needless to say this is becoming annoying. https://github.com/notable/notable/issues/350 seems to indicate there is a way to disable it, but I can't find it in the menu bar and there is no mention of it in the tutorial.

Could you point me in the right direction?

**Comment by jpsnyder** [comment] 2019-07-17 12:57
I just realized this is probably a duplicate to https://github.com/notable/notable/issues/742. Sorry about that. But it would be useful to have the ability to turn it off completely instead of it trying to check for an internet connection since this machine will never be connected to the internet.

**Comment by fabiospampinato** [comment] 2019-07-24 20:14
> Needless to say this is becoming annoying. #350 seems to indicate there is a way to disable it, but I can't find it in the menu bar and there is no mention of it in the tutorial.

I just added a switch for it, but it isn't user-facing yet, as we have no settings yet #476.

> I just realized this is probably a duplicate to #742.

Yeah it seems that would also fix your issue, without requiring any settings to be set. Anyway I've fixed that yesterday so I'm closing this one too.

**Comment by fabiospampinato** [comment] 2019-07-24 20:15
Actually let me keep this open as a reminder to myself to add a setting for this once settings are implemented.

**Comment by jpsnyder** [comment] 2019-07-25 13:06
Sounds great. Looking forward to it!

**Comment by fabiospampinato** [comment] 2019-07-27 11:14
Closing as a duplicate of #612

**Closed by fabiospampinato** 2019-07-27 11:14 UTC
Labels: enhancement
