### ISSUE TITLE
Recent Notes  - Back and Forward Buttons ? 

### ISSUE THREAD

**Issue by amitn322** [notable/notable#1129] opened 2020-04-27 22:49 UTC
### Feature description
Ability to switch back and forward between notes would greatly enhance the usability of notable.

 When working on a note, if you need to reference another note, you have to search for that note and then to come back, search for the note that you were currently on again. Instead if there was a back/forward button, after referencing another note for a quick glance, a back button would take right to the note one was before going to that note for a quick information. 
### Feature motivation

I currently use Notable as my go to Note Taking tool and have a lot of notes. Sometimes i need to take a quick look at another note for example , i will find that and now i will have to search again to find the note i was earlier on. Just having a back button that took you to the previous note sounds like could be very useful.

**Comment by fabiospampinato** [comment] 2020-04-27 22:54
duplicate of #144 (I've already implemented tabs, which mostly solves this issue I think, they are coming in v1.9)

**Closed by fabiospampinato** 2020-04-27 22:54 UTC
