### ISSUE TITLE
Notes being overwritten with touch screen

### ISSUE THREAD

**Issue by MizarcDev** [notable/notable#615] opened 2019-04-18 05:20 UTC
- **OS Version**: Windows 10 (1809)
- **Notable Version**: 1.4.0

### Current behavior
This is an easily reproducible bug using a laptop with a touch screen.

While editing a note, using the touch screen to switch to another note causes the selected note to be overwritten by the note being edited. This essentially removes the note and causes the note being edited to be duplicated.

### Expected behavior
Selecting another note should save the note currently being edited and switch to the other note without any modifications.

**Comment by fabiospampinato** [comment] 2019-04-18 11:42
And you can reproduce this only when switching via the touchscreen but not when switching via the mouse or shortcuts? 🤔

**Comment by jeff9315** [comment] 2019-04-18 12:31
If it's happening with the mouse or keyboard (like it is mine), then I've been assuming it's related to https://github.com/notable/notable/issues/574. So I haven't reported it. For me, it sometimes overwrites the note with the contents of another note, sometimes creates a zero length file and sometimes deletes the file.

It's really frustrating. I've actually gone so far as to create a scheduled task that uses `Robocopy /MON:1` for my notes directory. It runs constantly and keeps a backup copy ... but I need to make sure it's always running. Even then, if it creates a zero length file, I've lost my data because my backup gets overwritten with a zero length file and I've got to recover the file from the previous night's full-disk backup.

**Comment by MizarcDev** [comment] 2019-04-19 01:35
After further testing, it appears that the issue may occur when switching with a mouse or keyboard, though the occurrence is rare. It is much easier to reproduce with a touch screen as it occurs 100% of the time.

**Comment by fabiospampinato** [comment] 2019-04-19 09:35
Thank you, that's very useful information!

**Comment by fabiospampinato** [comment] 2019-04-28 15:49
I'm closing this as a duplicate of #574, let's track the resolution of the issue there.

**Closed by fabiospampinato** 2019-04-28 15:49 UTC
Labels: bug
