### ISSUE TITLE
Sidebar scaling not saved

### ISSUE THREAD

**Issue by jnor** [notable/notable#1083] opened 2020-03-11 06:19 UTC
After using Notable for a about a year this one, small thing is driving me nuts. Almost made me switch back to Boostnote.

Problem: 
Every time I open Notable I have to scale the width of the sidebar, because when Notable is closed and re-opened the sidebar is back to default width. I tend to open and close Notable many times during work. This is insanely annoying.

If anyone would have the time to fix this bug it would make me so so so happy! Thanks a million

**Comment by fabiospampinato** [comment] 2020-03-11 14:05
Duplicate of #339. Hang in there a little while longer, I plan to address this in v1.9.

**Closed by fabiospampinato** 2020-03-11 14:05 UTC
