### ISSUE TITLE
Back references

### ISSUE THREAD

**Issue by reddec** [notable/notable#1293] opened 2020-08-26 02:57 UTC
### Feature description

A way to see all notes linked to the current notes (backref).

Maybe panel at the bottom.

Example:

* Note 1 links to `Node A` and `Note B`
* Note 2 links to `Node B` and `Note C`

So in `Note B` will be great to see automatic links to `Note 1` and `Note 2`.

### Feature motivation

Useful to navigate between notes and find related information. Also, it can reveal unexpected notes relation.

**Comment by fabiospampinato** [comment] 2020-09-30 18:52
Duplicate of #1076

**Closed by fabiospampinato** 2020-09-30 18:52 UTC
Labels: enhancement
