### ISSUE TITLE
Support plugins for export, e.g. Confluence

### ISSUE THREAD

**Issue by grexe** [notable/notable#905] opened 2019-11-13 16:21 UTC
I'd like to add support for exporting my notes to Wikis like Confluence.
It would make sense to offer some kind of export plugin API for features like these to be added by interested developers.

I've collected some notes on a conference and want to push them to our team Wiki, and existing solutions are limited since they do not correctly map Notable's header, e.g. in a Wiki export plugin, I'd add support for correctly adding tags etc.

**Comment by fabiospampinato** [comment] 2020-01-10 23:48
I'm closing this as a duplicate of #128.

**Closed by fabiospampinato** 2020-01-10 23:48 UTC
Labels: enhancement, plugin candidate
