### ISSUE TITLE
"Are you sure you want to close this window?", Why?

### ISSUE THREAD

**Issue by stevezero1** [notable/notable#1060] opened 2020-02-15 13:11 UTC
### Feature description
Removing the lock-in "Are you sure you want to close this windows?"
### Feature motivation
Why not removing the message that comes up when closing the app? In my opinion it can improve the UX, yes it does in a very little way, but i think that it's redundant as long the app has the auto-save module.

**Comment by fabiospampinato** [comment] 2020-02-15 13:14
Duplicate of #791

**Closed by fabiospampinato** 2020-02-15 13:14 UTC
