### ISSUE TITLE
LaTeX: display math and whitespace

### ISSUE THREAD

**Issue by wookayin** [notable/notable#484] opened 2019-02-22 18:13 UTC
Hi, I find this app fantastic. Thanks!

Regarding LaTeX syntax, it seems that display blocks (`$$`..`$$`) would not work if an actual math block content follows `$$` in the next line:

```markdown
# Test Note

$$
E = mc^2     
$$            <!-- not working -->

$$E=mc^2$$    <!-- working -->
```

I see some note from a tutorial:

> Note: In order to minimize conflicts there mustn't be spaces at the beginning and end of a formula, and the ending $ character musn't be followed by a digit. If you need to you can escape the $ character with a backslash.

Well, but this syntax is supported in most of markdown-based apps and renderers that support LaTeX. It would be greater if this could be improved and supported!

**Comment by fabiospampinato** [comment] 2019-02-22 19:40
Duplicate of #431.

@wookayin The problem here is that multi-line expressions just aren't supported. In the mean time you can instead wrap your multi-line expression in a "katex" codeblock (I don't actually remember if this is already supported din v1.3, but it's supported on the master branch and will be supported in v1.4).

**Closed by fabiospampinato** 2019-02-22 19:40 UTC

**Comment by wookayin** [comment] 2019-02-22 22:29
Sorry for not finding the duplicate issue. Thanks for your response!

**Comment by fabiospampinato** [comment] 2019-02-22 22:30
Don't worry it was easy to miss, its title is very generic.
