### ISSUE TITLE
Import html: An error occurred: e.parser is not a constructor

### ISSUE THREAD

**Issue by msbentley** [notable/notable#775] opened 2019-08-12 08:30 UTC
- **OS Version**: linux 4.18.0-18-lowlatency
- **Notable Version**: v1.7.1

I just installed the latest version (AppImage) and exported some notes from EverNote in HTML to test the import feature, For both individual and multiple notes, I landed here :) 

```
TypeError: e.parser is not a constructor
    at htmlParser (file:///tmp/.mount_NotablSYHIik/resources/app.asar/chunk.b2bf0d0b1d0ebd17b6b3.js:1:39358)
    at new RootNode (file:///tmp/.mount_NotablSYHIik/resources/app.asar/chunk.b2bf0d0b1d0ebd17b6b3.js:1:39371)
    at TurndownService.turndown (file:///tmp/.mount_NotablSYHIik/resources/app.asar/chunk.b2bf0d0b1d0ebd17b6b3.js:1:42918)
    at Object.html2markdown [as default] (file:///tmp/.mount_NotablSYHIik/resources/app.asar/chunk.b2bf0d0b1d0ebd17b6b3.js:1:33523)
    at Object.convert (file:///tmp/.mount_NotablSYHIik/resources/app.asar/chunk.b2bf0d0b1d0ebd17b6b3.js:1:1939)
    at HTMLNote.formatContent (file:///tmp/.mount_NotablSYHIik/resources/app.asar/chunk.b2bf0d0b1d0ebd17b6b3.js:1:56800)
    at HTMLNote.get (file:///tmp/.mount_NotablSYHIik/resources/app.asar/chunk.b2bf0d0b1d0ebd17b6b3.js:1:2883)
    at async HTMLProvider.dump (file:///tmp/.mount_NotablSYHIik/resources/app.asar/chunk.b2bf0d0b1d0ebd17b6b3.js:1:2706)
    at async Object.dump (file:///tmp/.mount_NotablSYHIik/resources/app.asar/chunk.b2bf0d0b1d0ebd17b6b3.js:1:57972)
    at async import_Import.import (file:///tmp/.mount_NotablSYHIik/resources/app.asar/renderer.js:1:21709)
```

**Comment by fabiospampinato** [comment] 2019-08-12 09:21
Duplicate of #774, fix coming soon!

**Closed by fabiospampinato** 2019-08-12 09:21 UTC
