### ISSUE TITLE
Relative links to notes

### ISSUE THREAD

**Issue by ramtinsoltani** [notable/notable#665] opened 2019-05-17 09:20 UTC
I have a notebook with two sub-categories:

Notebook A:
  - Sub-category A:
    - Note A
  - Sub-category B
    - Note B

What I'm trying to do is to link from Note A to Note B. I've tried the following links but none of them work:  
`@note/../Sub-category B/Note B.md`  
`@note/Notebook A/Sub-category B/Note B.md`  
`@note/Note B.md`

Is this possible?

**Comment by fabiospampinato** [comment] 2019-05-17 11:25
It's possible but I'd have to see the file system structure to write the right code to link to "Note B", can you share a sample data directory that reproduces the problem?

**Comment by ramtinsoltani** [comment] 2019-05-17 11:57
I created a repository reproducing the problem. Please read **Note A** where I have left you a few lines describing the problem and the expectations.

**Comment by ramtinsoltani** [comment] 2019-05-17 12:12
Per my observations, categories under notebooks are not actual directories, therefore, if I have two notes by the same name under different categories it would be hard to link to them since the one that is created last will have ` (2)` appended to its name. This could complicate my proposed solution (which is inside the repo I provided.)

**Comment by fabiospampinato** [comment] 2019-05-18 20:25
@ramtinsoltani 

> I'm expecting attempt #1 to work the way it is

It can't, we are interpreting that as a relative filepath, which is not relative to the current tags or notebooks, but relative to the note's filesystem location.

> attempt #2 to work but using a different syntax to mark the link as absolute (maybe //?)

I don't think we can implement this, as otherwise there will still be a problem if for some reason there's a note with whatever you put after `@note/` in its title.

>  and attempt #3 to work and link to Note B in Category A.

We are actually considering the filename of the note for this, it's not a coincidence that you have to write the extension too. There's only one note named `Note B.md` and that's in "Category B", not "Category A". 

Even if we used titles this link would be ambiguous.

> Therefore, .. should refer to the parent directory/category/notebook where using it would allow navigating through the data directory to link to notes at any depths (not just forward.)

`..` actually refers to the parent _directory_, you could link to attachments via `../attachments/foo.jpeg`, or go up in the hierarchy `../../../etc`.

> It would also be helpful to have the ability to use absolute links since having a complex nesting structure in the data directory could make it hard for the user to write relative links with many  ..s.

Absolute links are provided via the `@notes/*` syntax, or via wiki-style links `[[foo]]`.

---

You can link to the other note via `[Note B](@note/Note B (2).md)`, which isn't great at all.

This problem will be fixed properly once we have a unique id for each note (so that there are no ambiguities) #538, and once we have proper autocomplete #20, so that you won't have to write the uuid/filename by hand.

**Closed by fabiospampinato** 2019-05-18 20:25 UTC
Labels: needs more info

**Comment by ramtinsoltani** [comment] 2019-05-18 20:45
Now I understand how you're handling the notes file system. I would have gone with each category as a separate directory under their notebooks (also directories) so relative paths would have worked the way users expect them to work, that way there would have been no ambiguities with notes having the same name under different categories, though that design choice is not up to me. Thanks for following up with the issue, and really good work with Notable, I'm loving it!

**Comment by fabiospampinato** [comment] 2019-05-18 20:47
>  I would have gone with each category as a separate directory under their notebooks (also directories) so relative paths would have worked the way users expect them to work, that way there would have been no ambiguities with notes having the same name under different categories, though that design choice is not up to me. 

This has been discussed at length here #54, I think it actually is unimplementable they way you're thinking about it because a note could be put inside multiple notebooks, where should we store it then?

> Thanks for following up with the issue, and really good work with Notable, I'm loving it!

I'm glad you're linking it, and thanks for your feedback!
