### ISSUE TITLE
Notes on Notable Usage

### ISSUE THREAD

**Issue by NikEyX** [notable/notable#1151] opened 2020-05-13 23:00 UTC
Hi Fabio,

been using Notable quite a lot, and just wanted to give you a breakdown of some of the issues I faced / features that I think would be useful. Since there are so many points I haven't looked at previous feature requests to see if it's a duplicate, so feel free to discard any of these bullets that have already been raised. Just thought it's good to give you some thoughts, rather than no feedback at all.

1. If I am IN a note, I would like to search within the note using ctrl+f. However, right now it searches across all notes, which isn't exactly the normal use case I think.
2. Option to disable matching brackets
3. Ctrl+A when in the note-selection menu (the middle one, as well as the side bar), allowing to select all notes. Right now that does nothing.
4. Batch operations (like adding tags to many notes) should be possible when right-clicking notes in the note-selection menu, not just as extra GUI operation in the middle. 
5. The batch-tagging operation doesn't work if you enter a tag and press enter, as that doesn't seem to do anything/fails silently. Currently it requires entering a tag and then using the mouse to click the "Add tags" button in order to make it work.
6. When reopening Notable it should remember the position of side bar, middle bar, edit bar, and split-view bar (if activated). Generally remember all positions! It should also remember the screen position and the monitor (it always opens on the wrong one)
7. After opening with ctrl+o it should immediately go to edit mode (if in split-edit view), but nothing works, not even ctrl+e.
8. Selecting several tags should only show the notes that make up the UNION of the selected tags. For example I can have notes with "diary" tag and they can be on different subjects, so I'd add additional tags such as "private" and "work". However, if I want to see all _diary_ notes for _work_ only, I currently cannot do that. Ideally I should just be able to select the _diary_ and _work_ tag on the left side (with ctrl+click) to see all the relevant notes in the middle bar.
9. If you are on a note and press NEW NOTE, it should have ALL the tags from that note, not just the one from the selected tag group. (Otherwise what's the point of tags if they behave like folders after all). If that's not ideal, then maybe raise a dialog to ask if you want to copy all the tags for the new note?

**Comment by fabiospampinato** [comment] 2020-05-14 15:13
@NikEyX Hey, thanks for your feedback. There's a "request for feedback" post in the [subreddit](https://www.reddit.com/r/Notable/), you might to provide some additional feedback there too or in general keep on eye on the subreddit as there will be future "request for feedback" discussions.

> If I am IN a note, I would like to search within the note using ctrl+f. However, right now it searches across all notes, which isn't exactly the normal use case I think.

Duplicate of #140, this is the single biggest missing feature for me personally, unless I encounter some major roadblock along the way I want to implement this before shipping v1.9.

> Option to disable matching brackets

This can be added, but I thought this was pretty much always handy, when isn't it so?

> Ctrl+A when in the note-selection menu (the middle one, as well as the side bar), allowing to select all notes. Right now that does nothing.

This is tricky, in principle I agree with you, however the issue here is the focus, in order for this to work you need to focus on the middlebar, currently this is actually impossible as in order to be able to scroll the preview with the keyboard even immediately after clicking on a note in the middlebar the middlebar can't be focused. This can be changed, but then how would you switch focus to the middlebar? You'd have to click on an empty space, or the currently active note if there's only one, or we would have to provide a shortcut for doing that explicitly. I'm not sure the change is worth it. 

Currently there's a global shortcut for this, `Ctrl+Alt+A`, and it doesn't require you to think about the focus at all.

> Batch operations (like adding tags to many notes) should be possible when right-clicking notes in the note-selection menu, not just as extra GUI operation in the middle.

For v1.9 I've actually already exposed all of the multi-note editor actions in a special context menu too, except for adding/removing tags, as I lacked a few ingredients for implementing that, namely a way to prompt the user for a string and a standalone way to select which tag to remove, but that's implementable now 👍 I'll probably add this in v1.10.	

> The batch-tagging operation doesn't work if you enter a tag and press enter, as that doesn't seem to do anything/fails silently. Currently it requires entering a tag and then using the mouse to click the "Add tags" button in order to make it work.

I hadn't really though of that, it should probably work like you describe, this can be changed, I'll probably fix this in v1.10 too.

> When reopening Notable it should remember the position of side bar, middle bar, edit bar, and split-view bar (if activated). Generally remember all positions!

Duplicate of #339. I didn't have the right tools for properly implementing this in v1.8, now I do and this should be coming in v1.9 too.

> It should also remember the screen position and the monitor (it always opens on the wrong one)

For v1.9 I've rewritten the library that takes care of that, so maybe this is fixed already, but probably not. I'll take a closer look at this after v1.9 is out, unfortunately I don't have another monitor to try this with, I'll figure something out 🤔 are you in the [chat](https://chat.notable.md)? Maybe worst case scenario I could try to fix this blindly and then I could send you a patched version of the app so you could tell me if it is actually fixed or not.

> After opening with ctrl+o it should immediately go to edit mode (if in split-edit view), but nothing works, not even ctrl+e.

I don't think the state of the editor should be changed when you switch notes 🤔 say you actually always want to edit notes in split mode, this change would require you to keep going back and forth between split and regular mode when switching notes, which I don't think would be great.

`Ctrl+E` should probably exit split mode at least, I'll take a closer look at this before shipping v1.9 👍 

> Selecting several tags should only show the notes that make up the UNION of the selected tags. For example I can have notes with "diary" tag and they can be on different subjects, so I'd add additional tags such as "private" and "work". However, if I want to see all diary notes for work only, I currently cannot do that. Ideally I should just be able to select the diary and work tag on the left side (with ctrl+click) to see all the relevant notes in the middle bar.

Duplicate of #398, this I actually implemented already, it will be in v1.9.

> If you are on a note and press NEW NOTE, it should have ALL the tags from that note, not just the one from the selected tag group. (Otherwise what's the point of tags if they behave like folders after all). If that's not ideal, then maybe raise a dialog to ask if you want to copy all the tags for the new note?

🤔 A dialog for every new note created would be too noisy, a setting for enabling/disabling that dialog would probably be too granular. I'm not sure about this, on one hand I think a newly created note has more to do with the active tags than with the active note, on the other hand removing tags is much easier to do than adding tags so maybe we should switch to the behavior you are describing. 

I'm not sure, I'll have to think more about this, right now I'm thinking the current behavior is more correct, and if you want things to work the way you are describing maybe you should duplicate the current note and then just replace its content, does that not work well for you? 

---

I'll keep this issue open until I'll extract actionable issues from it, thanks for the feedback 👍 If you have more I'd be happy to hear it.

**Closed** 2020-05-14 15:22 UTC
