### ISSUE TITLE
Collapsible outlines/sections in Preview

### ISSUE THREAD

**Issue by bkonia** [notable/notable#1405] opened 2020-12-07 06:18 UTC
In the Markdown editor, we have disclosure triangles to expand/collapse sections and outlines. I'd like to have the same disclosure triangles available in the Preview.

**Comment by fabiospampinato** [comment] 2020-12-07 22:20
Duplicate of https://github.com/notable/notable/issues/1384

**Closed by fabiospampinato** 2020-12-07 22:20 UTC
