### ISSUE TITLE
Failing to export to PDF

### ISSUE THREAD

**Issue by Mepy** [notable/notable#954] opened 2019-12-23 00:41 UTC
- **OS Version**:MacOS10.14.5
- **Notable Version**:1.8.2

### Current behavior
When I export my .md file (with picture attachments) to .pdf file,It export a folder with only attachments,which means that it doesn't export the .pdf file!

By the way,It's my first issue,forgive my little mistakes.

**Comment by fabiospampinato** [comment] 2020-01-07 15:05
@Mepy Could you send me an `.md` file that I can use to reproduce the issue? You can email it to me at fabio@notable.md

**Comment by fabiospampinato** [comment] 2020-01-16 15:44
I think this is a duplicate of: #979

**Closed by fabiospampinato** 2020-01-16 15:44 UTC
Labels: bug, exporting, needs more info
