### ISSUE TITLE
tutorials have broken attachments in linux

### ISSUE THREAD

**Issue by k1nghat** [notable/notable#394] opened 2019-01-31 17:18 UTC
- **OS Version**:
Operating System: KDE neon 5.14
KDE Plasma Version: 5.14.5
Qt Version: 5.11.2
KDE Frameworks Version: 5.54.0
Kernel Version: 4.15.0-44-generic
OS Type: 64-bit
- **Notable Version**:
1.3.0
### Current behavior
download appimage and run. set data dir and run. default installed tutorials have broken image attachments. there is no `attachments` directory created.

![image](https://user-images.githubusercontent.com/16073360/52071985-bc176180-2549-11e9-9611-69b8a612287a.png)
### Expected behavior
image/attachments should work. should have an `attachments` directory created.
these might be related:
https://github.com/fabiospampinato/notable/issues/343
https://github.com/fabiospampinato/notable/issues/187

**Comment by k1nghat** [comment] 2019-01-31 17:36
> Does the `attachments` folder have `icon_small.png` and `icon.png`?
> Can you check the URL of the file it's trying to open using devtools?

i should probably have noted that. i dont even have an attachments directory. it wasnt created. only a notes directory.

**Comment by RomanKornev** [comment] 2019-01-31 17:44
That definitely should not happen. Thanks for reporting it!

**Comment by fabiospampinato** [comment] 2019-02-09 13:20
I think this might be a duplicate of #406 🤔

**Comment by fabiospampinato** [comment] 2019-02-09 17:15
I'm closing this as a probable duplicate of #406, since I can't reproduce it under my Lubuntu VM.

@k1nghat I'd be happy to re-open the issue if you could reproduce it again on the next release.

**Closed by fabiospampinato** 2019-02-09 17:15 UTC
Labels: bug
