### ISSUE TITLE
Notable 1.3 - start and stop it leaves behind 2 processes on Windows 10 (1803)

### ISSUE THREAD

**Issue by rluiten** [notable/notable#445] opened 2019-02-12 01:43 UTC
- **OS Version**: Windows 10 1803
- **Notable Version**: I tested all versions realeased only 1.3 has this behaviour.

### Current behavior

Start Notable then exit it, 2 Notable.exe processes are left behind.
This is repeatable every time you start and exit Notable it leaves behind 2 more processes.

They are visible in task manager, these left behind processes appear to affect Notable if I start it again as it starts slower if there is at least a pair of these processes left behind.

### Expected behavior

When I start and then exit Notable there should be no Notable.exe processes left behind after a short dealy. 

In 1.0, 1.0.1, 1.1, 1.2 exiting Notable does not leave behind processes.
This behaviour is only happening in 1.3.

I spent some time try to diagnose this on my machine but have not managed to get any traction in either research or just experimenting with main thread and the event handlers.

**Comment by fabiospampinato** [comment] 2019-02-12 01:51
There's already an issue about this but I can't find it anymore.

> In 1.0, 1.0.1, 1.1, 1.2 exiting Notable does not leave behind processes.
> This behaviour is only happening in 1.3.

Very interesting, I've just checked and we updated electron in v1.2, so that's not the problem. I'm not sure what could cause this 🤔

**Comment by rluiten** [comment] 2019-02-12 02:54
I mentioned in the other issue i raised about tutorial file creation.
I learned about the version stuff, and thought it made sense to create its own issue, as I got no traction trying to dig into it myself yet.

**Comment by amelandri** [comment] 2019-02-12 07:44
I confirm the bug.

![immagine](https://user-images.githubusercontent.com/140700/52619603-61173000-2ea2-11e9-9657-bd1868ba1e13.png)

**Comment by rluiten** [comment] 2019-02-12 08:30
I did notice something extra in Notable versions prior to 1.3 so 1.0 through to 1.2 when you run Notable you get 2 Notable.exe processes (both go away when you exit), but 1.3 actually has 3 processes (2 of which appear to stay behind on exit at the moment). This may not matter but I thought I would mention it in case its a clue to what might be happening.

**Comment by Arecsu** [comment] 2019-02-12 17:48
Happens to me too

**Comment by dvergeylen** [comment] 2019-02-15 13:24
I have the same problem, running **Linux** (Debian).

Launching Notable from the command line and then quitting via its GUI makes it to hang in the CLI.

`ps aux` shows multiple entries:

```bash
$ ps aux | grep -i notable
222:dv       25726  5.5  0.9 943284 119156 pts/2   Sl+  14:22   0:01 /opt/Notable/notable
223:dv       25728  0.1  0.3 211188 40092 pts/2    S+   14:22   0:00 /opt/Notable/notable --type=zygote --no-sandbox
224:dv       25752  2.0  1.1 378992 140484 pts/2   Sl+  14:22   0:00 /opt/Notable/notable --type=gpu-process --enable-features=SharedArrayBuffer --no-sandbox --gpu-preferences=KAAAAAAAAACAAABAAQAAAAAAAAAAAGAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=17122299515320006008
229:dv       25879  0.0  0.0   6224   884 pts/3    S+   14:22   0:00 grep --color=auto --line-number -i notable
```

When I hit Ctrl + c, all processes are terminated.

**Comment by fabiospampinato** [comment] 2019-02-15 14:35
It looks like the app isn't quit properly on Linux and Windows, since I can't reproduce this on macOS. I'll try to get this fixed before the next release.

**Comment by dvergeylen** [comment] 2019-02-22 13:51
The app is closed nicely when quitting via "Notable" → "Quit" (or <kbd>Ctrl</kbd> + <kbd>Q</kbd>)

**Comment by amelandri** [comment] 2019-02-22 16:34
> The app is closed nicely when quitting via "Notable" → "Quit" (or Ctrl + Q)

I confirm this.

I also just noticed that when Notable starts it creates three different processes

![immagine](https://user-images.githubusercontent.com/140700/53256305-d3b8b480-36c7-11e9-8430-5cc2a357670b.png)

![immagine](https://user-images.githubusercontent.com/140700/53256357-f6e36400-36c7-11e9-844b-a0f22d259d38.png)

But when you close the app with close button, two processes are left behind

![immagine](https://user-images.githubusercontent.com/140700/53256388-06fb4380-36c8-11e9-9f32-0094640a6ee8.png)

**Comment by fabiospampinato** [comment] 2019-02-22 19:41
> I also just noticed that when Notable starts it creates three different processes

It's normal that there are multiple processes in an Electron app.

**Comment by fabiospampinato** [comment] 2019-02-23 00:02
> The app is closed nicely when quitting via "Notable" → "Quit" (or Ctrl + Q)

I can also reproduce this, I'll see what's the difference between closing the window and closing the app from the menu 👍

**Comment by rluiten** [comment] 2019-02-23 00:32
Just to confirm on Windows, if i use Exit in the File Menu no processes are left behind.

**Closed** 2019-02-23 19:41 UTC
Labels: bug
