### ISSUE TITLE
Pasting from clipboard while text is highlighted does not replace highlighted text

### ISSUE THREAD

**Issue by qagoose** [notable/notable#817] opened 2019-09-12 10:33 UTC
- **Ubuntu 18.04.1 LTS**:
- **1.7.3**:

### Current behavior

When you highlight text and paste over it from the clipboard, it does not remove the highlighted text before pasting the value from the clipboard.

E.g. if the words "I am some text" are highlighted, and "more text" is in the clipboard, when I paste it becomes "I am some textmoretext" instead of just "more text".

- Type some text into a note
- Copy some text to your clipboard
- Highlight the text in the note
- Paste

### Expected behavior

The pasted text should replace the highlighted text.

**Comment by fabiospampinato** [comment] 2019-11-17 01:26
I can't reproduce this, if anybody has any reliable reproduction steps to offer it'd be great.

**Comment by qagoose** [comment] 2019-11-21 10:26
It hasn't happened again and I spent a couple of hours specifically trying to cause it, so it's probably safe to close this.

**Comment by fabiospampinato** [comment] 2020-01-09 23:06
I'm closing this as I can't reproduce it and you can't anymore either. I'm not sure how it could have happened in v1.7.3 🤔

**Closed by fabiospampinato** 2020-01-09 23:06 UTC
Labels: bug, help wanted
