### ISSUE TITLE
Triple-pasting from clipboard

### ISSUE THREAD

**Issue by thisfro** [notable/notable#779] opened 2019-08-14 15:27 UTC
- **OS Version**: MacOS 10.14.4 (18E226)
- **Notable Version**: 1.7.2

### Current behavior
My clipboard has the string "test" stored. When I `CMD+V` or `right click>paste`, it inserts the string "testtesttest" in any document of notable.

### Expected behavior
Inserting string "test"

### Notes
It works fine in other applications (e.g. Firefox, Finder, ...).
It does not matter if copied from within Notable or another application (text only).
**Sometimes** restarting the app resolves the problem temporarily.

**Comment by chtison** [comment] 2019-08-15 19:32
Same for me but it was double-pasting "only", and a restart fixed the problem.

**Comment by fabiospampinato** [comment] 2019-08-15 23:14
It looks like the "paste" event is being handled multiple times or something, I'll probably get this fixed in v1.7.3 👍

**Comment by fabiospampinato** [comment] 2019-08-21 17:46
I haven't been able to reproduce this reliably yet, can you guys provide a set of steps to take to reproduce this?

So far I've learned this much:

1. If I disable the `paste` event handler then I can't even paste, so this event handler is probably somehow involved in the issue, or maybe the cause of the multiple pastes didn't manifest itself during those times I tried pasting with the event handler disabled.

2. If I avoid cleaning up the `paste` event handler when reloading the app with `F5` then I get the behavior you guys are describing. Did you guys happen to reload the app via `F5`?

3. I don't see how point 2 can happen on its own, and checking manually (`document.__cashEvents.paste.length`) I see only 1 event handler attached for the `paste` event, so I don't think point 2 is likely to be the issue here.

4. Maybe the `paste` event is being triggered twice for some reason, but that would most probably be a Chrome bug, which is probably unlikely.

5. Maybe there's another event handler coming from the editor for the `paste` event, which sometimes kicks in before our and sometimes it doesn't. I think this is not the case as I've explicitly instructed the editor to do nothing on `paste`.

Being able to reproduce this reliably would be very useful.

**Comment by chtison** [comment] 2019-08-23 19:53
It happened right after starting the app for the first time after installing it with `brew cask install notable` but not since.

**Comment by mtibbi** [comment] 2019-08-25 21:32
I am having duplicated "paste" in Windows10, Notable 1.7.3. 
It happens all the time in the first run of Notable.
The problem disappears if I exit and restart the program.

**Comment by thisfro** [comment] 2019-08-27 09:50
> It seems the problem is triggered after changing data directory using Ctrl+Shift+X shortcut.

Yup, this breaks it. I have "double" paste then, maybe triple is caused by something else? Couldn't recreate though...

**Comment by fabiospampinato** [comment] 2019-08-27 13:47
> It happens all the time in the first run of Notable.

> It seems the problem is triggered after changing data directory using Ctrl+Shift+X shortcut.

These don't reproduce the issue for me, do you guys see the issue every time when doing this?

**Comment by thisfro** [comment] 2019-08-28 08:46
> These don't reproduce the issue for me, do you guys see the issue every time when doing this?  

I have tried it 4 times and it happend 4 times.

I have also updated my notable to `1.7.3`. But I haven't seen triple pastes anymore, only double. Has something changed in that matter from `1.7.2`

**Comment by AldieNightStar** [comment] 2019-08-29 09:36
I have the same bug. It is unusable to paste code.

**Comment by fabiospampinato** [comment] 2019-08-29 11:12
@AldieNightStar Does it happen every single time for you? Even after restarts? What OS are you on?

**Comment by laajila** [comment] 2019-09-02 14:14
I had the same bug but I can't reproduce it after I restarted my pc.

**Comment by micmorris** [comment] 2019-09-05 18:59
Just wanted to chime in that I had this problem as well, installed via `.dmg` onto `Mac Mojave 10.14.5 (18F132)`, Cmd-V would double-paste the clipboard contents (although it was a single event because using Cmd-Z would remove it all).

Restarting the Mac fixed it though. Hope this helps, and thanks again for making such an awesome app! ❤️

**Comment by tamnguyenchi93** [comment] 2019-09-06 03:03
Double pasting `Ctrl+V`
  + OS Version: Windows 10
  + Notable Version: 1.7.3

Sometime after refresh windows with shortcut `F5`.

**Comment by mtibbi** [comment] 2019-09-08 02:24
Notable version 1.7.3.
OS: Windows10

The duplicate copy-paste issue reappeared after the procedure I explain below:
1. In Firefox I downloaded a PNG image from a website.
2. I opened the PNG file with Paint.Net in order to edit the image size.
3. After the image was resized, I selected a rectangular area and applied Ctrl+C.
4. Next, I opened a note in Notable with Ctrl+E.
5. I placed the cursor at a desired position within the note text and pressed Ctrl+V.
6. The result obtained was as follows:
! [ ] (@ attachment / Clipboard_2019-09-07-17-59-42.png)! [ ] (@ attachment / Clipboard_2019-09-07-17-59-42 (2) .png)
After this first event, all following Copy/Paste operations, even with other contents in other notes, resulted in duplicate copies.
I even changed the data directory many times with Ctrl+Shift+X, but the problem persisted.
The problem only disappeared after closing and reopening Notable.

**Comment by mtibbi** [comment] 2019-09-08 02:35
I forgot to mention that pasting data into an external text editor you get only one copy. So, that means the content in clipboard is not duplicated by itself.

**Comment by mtibbi** [comment] 2019-09-12 00:40
I don't know if it has anything to do with the problem but, just by chance, I found that Notable 1.7.1 was still installed in my Windows 10, although I have migrated to version 1.7.3 since its release. 
I am manually uninstalling version 1.7.1. as it makes no sense to have both versions installed.

**Comment by mtibbi** [comment] 2019-09-12 01:46
By uninstalling version 1.7.1, version 1.7.3 was also uninstalled. Apparently both records pointed to the same executable block. No problem, I'm reinstalling version 1.7.3

**Comment by weltenwort** [comment] 2019-09-23 22:53
I experienced this as well with the 1.7.3 appimage. While I wasn't able to reproduce it beyond the one occurrence, I can confirm that there were two identical event handlers attached to the `paste` event on the `document` (according to the devtools).

**Comment by fabiospampinato** [comment] 2019-09-23 23:10
> I can confirm that there were two identical event handlers attached to the paste event on the document where the usually is only one (according to the devtools).

That's interesting, thanks! Do you remember if you reloaded the window or did something in particular before starting to experience this bug?

**Comment by Yoschey** [comment] 2019-09-24 13:06
So with me the problem occurs when I reload with F5. For every time I reload with F5 there is an additional insertion process. For example, if I reloaded 3 times with F5, the text is also inserted 3 times.

But I can't reproduce it safely. 
It occurs rather sporadically. 
And after a restart it is normal again.

**Comment by weltenwort** [comment] 2019-09-24 15:25
> Do you remember if you reloaded the window or did something in particular before starting to experience this bug?

I was unable to reproduce it, but I did change the data directory during that session. I'll try to run with source maps for a few days in case it happens again.

**Comment by gunt3001** [comment] 2019-09-24 18:29
I managed to trigger it on 1.7.3, W10 by randomly refreshing. No consistent method yet.

Some observations while glitch is happening:

1. `document.onpaste` is only fired once per paste
2. `document.__cashEvents.paste.length` returns 1
3. Duplicates only happen on the code editor. Duplicate paste does not happen on search box or tag editor textbox
4. Happens regardless of paste method (Ctrl + V, Shift + Insert, Right click + Paste)

**Comment by fabiospampinato** [comment] 2019-09-24 18:42
@gunt3001 Thanks for the help, it sounds like I might not be cleaning up some event handlers related to pasting on the editor, or maybe sometimes for some reason the app doesn't override the editor's default action on paste. I'll have to take a closer look at this, last time I did I couldn't narrow the issue down but we can't allow these sorts of bugs to exist.

**Comment by ajit555db** [comment] 2019-11-01 23:56
@fabiospampinato  

Windows 10 + Notable v1.7.3

Getting the double pasting of clipboard text. Here is the recording. On top, pasting the content in Notepad++ and bottom, pasting the same content in Notable, but getting double pasted.

![Notable-Copy-paste-two-times](https://user-images.githubusercontent.com/38309794/68062523-d7a9d580-fd30-11e9-9d07-c5d4407022c3.gif)

**Comment by fabiospampinato** [comment] 2019-11-29 13:07
Finally I can reproduce this reliably! Fix coming soon 👍

**Comment by Hugo-X** [comment] 2019-11-30 03:42
Double pasting

OS Version: Windows 10  1809
Notable Version: 1.8.2

**Comment by Sentient07** [comment] 2019-11-30 19:45
Here to affirm double pasting in 

OS: OSX 10.12 
Notable Version 1.8.2

**Comment by HynUx** [comment] 2019-12-03 07:15
double pasting in

mac os 10.14.2
notable 1.8.2

**Comment by elico** [comment] 2019-12-04 22:10
Double pasting in:
Windows
Notable Version 1.8.2

Despite the bug it's a wonderful software!!!

**Comment by fabiospampinato** [comment] 2019-12-11 15:54
Sorry for the delay guys, I recently relocated to London and getting things sorted took forever, I already found the cause of this issue I just needed to take care of other things in real life first, I'd hope to release v1.8.3 next week.

**Comment by fabiospampinato** [comment] 2019-12-11 19:32
I just fixed this, the fix will be available in the next release.

This was a pretty deep issue, with a solution that consisted in deleting 1 line of code essentially, if you're curious here's the line I'm talking about: https://github.com/kenwheeler/cash/commit/9362d8ea140f27c8fe2afbcad9557f9ee0e2b903#diff-a8d47922af66c801c63647f13561c261L18 The TL;DR is that under some circumstances attached events would get kind of forgotten so it was impossible to remove them afterwards.

**Closed by fabiospampinato** 2019-12-11 19:32 UTC
Labels: bug, help wanted
