### ISSUE TITLE
How to close update?

### ISSUE THREAD

**Issue by wanghuijz** [notable/notable#1014] opened 2020-01-20 06:56 UTC

**Comment by fabiospampinato** [comment] 2020-01-20 14:26
What do you mean? You don't want the app to auto-update itself?

**Comment by wanghuijz** [comment] 2020-01-21 07:40
> What do you mean? You don't want the app to auto-update itself?

Yes, Please

**Comment by fabiospampinato** [comment] 2020-01-21 13:01
Then this is a duplicate of #612

**Closed by fabiospampinato** 2020-01-21 13:01 UTC
Labels: needs more info
