### ISSUE TITLE
Separate note and attachment folders for different notebooks

### ISSUE THREAD

**Issue by KraxelHuber** [notable/notable#1022] opened 2020-01-21 22:30 UTC
It would be helpful to assign a designated data directory to individual notebooks.

I use to have different notebooks. Notes within these notebooks may have PDF attachments that have exactly the same file name, but are different from a content point of view, i.e. they are not equal. Right now, if I attach a PDF to a note where the same filename already exists in the attachment directory, the filename will automatically be incremented by a number (1). I wish to keep the filenames unchanged.

**Comment by fabiospampinato** [comment] 2020-01-21 22:52
> It would be helpful to assign a designated data directory to individual notebooks.

Just have multiple data directories.

If the issue is being able to edit multiple data directories at once then this is a duplicate of #60.

This may actually be a duplicate of the more general #54.

**Closed by fabiospampinato** 2020-01-21 22:52 UTC
