### ISSUE TITLE
Notebooks/Tag names autocomplete on edit.

### ISSUE THREAD

**Issue by esturniolo** [notable/notable#858] opened 2019-10-11 14:31 UTC
### Feature description
Would be great that when you edit a tag or notebook name, Notable recognize it and starts to autocomplete it with the pre existent ones to avoid to type manually all the names.

### Feature motivation
This is useful when you have larges names and notebooks nested.

**Comment by fabiospampinato** [comment] 2019-10-11 14:32
Duplicate of #20

**Closed by fabiospampinato** 2019-10-11 14:32 UTC
