### ISSUE TITLE
Process still runs in the background after closing app

### ISSUE THREAD

**Issue by yuchangxiaowen** [notable/notable#463] opened 2019-02-17 05:30 UTC
- **OS Version**: Windows 10
- **Notable Version**: v1.3.0

### Current behavior

After closing notable in win10, there are two processes running background.

This is what is shown in task manager after closing notable:
![bug](https://user-images.githubusercontent.com/36097774/52908794-b777da80-32b7-11e9-9153-2fe4822c2f9f.png)

### Expected behavior

There should be no process running background.

**Comment by fabiospampinato** [comment] 2019-02-17 15:32
Duplicate of #445.

**Closed by fabiospampinato** 2019-02-17 15:32 UTC
