### ISSUE TITLE
UI based editing, not code based

### ISSUE THREAD

**Issue by samislam** [notable/notable#1452] opened 2021-02-28 12:36 UTC
### Feature description

Notable should have a graphical user interface way to create tables, change text colors, adding background colors to text, something similar to word.
Joplin have a graphical user interface where you can insert tables and do other things simply by using the mouse.
however it doesn't have all the features such as changing colors.
Notable doesn't have any of these features (by using the mouse, the way most of the humans are comfortable with).
You have to try Joplin to see what I mean.

**Comment by 9z0** [comment] 2021-03-04 00:31
FYI, what you are describing is called a [WYSIWYG](https://en.wikipedia.org/wiki/WYSIWYG) editor (What You See Is What You Get).

**Comment by fabiospampinato** [comment] 2021-04-01 20:02
duplicate of #284

**Closed by fabiospampinato** 2021-04-01 20:02 UTC
