### ISSUE TITLE
Data corruption bug

### ISSUE THREAD

**Issue by gramster** [notable/notable#605] opened 2019-04-08 21:43 UTC
OS Version: 10.14.4
Notable Version: 1.4.0

### Current behavior

This one is fairly minor: I hit enter at the end of a note title and it duplicated the last word of the title on the next line.

So I went from:

    # Understand the big picture

to:

    # Understand the big picture
    picture

by just hitting ENTER.

### Expected behavior

Don't add junk text.

**Comment by fabiospampinato** [comment] 2019-04-09 12:06
I can't reproduce this, could you perhaps post a GIF of this happening?

**Comment by gramster** [comment] 2019-04-09 13:14
It happens sporadically. I don’t have a reliable repro. I’ve had it happen few times and it was never serious enough to worry me but yesterday after I lost several files I filed all the issues I saw.

**Comment by fabiospampinato** [comment] 2019-11-04 22:19
I haven't been able to reproduce this, and nobody else has reported this issue.

@gramster would you be able to try again a more recent version and see if you can reproduce? It might have been an issue with the editor itself which got fixed along the way.

**Comment by gramster** [comment] 2019-11-04 22:26
Sorry, I long ago gave up and switched to Mweb. Not really interested.

**Comment by fabiospampinato** [comment] 2019-11-04 22:32
@gramster I understand, thanks anyway for opening the issue. 

I'm closing it as in the past few months nobody else reported experiencing the same issue and I'm unable to reproduce it, there's a chance it might have been an issue with the editor itself which got fixed at some point.

I'd be happy to reopen if anybody else can reproduce this.

**Closed by fabiospampinato** 2019-11-04 22:32 UTC
Labels: needs more info
