### ISSUE TITLE
Code Block may something wrong

### ISSUE THREAD

**Issue by wenxiang-Li** [notable/notable#908] opened 2019-11-14 07:30 UTC
- **Windows 10 x64 **:
- **1.8.1**:

###in code block with c or csharp keyword,  the  double quotation marks (" ") always rendered to single  quotation marks (' ').

**Comment by vallentin** [comment] 2019-11-14 12:47
*Extending.*

If the code block doesn't specify a language, then `"` and `'` are rendered correctly.

However if a code block specifies any language, invalid or not. Then `"` are always replaced with `'`. As in if the language is `c`, `rust`, `abc`, `wrong`, etc. Then `"` is always replaced with `'`.

I have a lot of Rust snippets, with funky highlighting due to this.

**Comment by fabiospampinato** [comment] 2019-11-14 13:45
Duplicate of https://github.com/notable/notable/issues/896

**Closed by fabiospampinato** 2019-11-14 13:45 UTC
