### ISSUE TITLE
Task reminder for notable

### ISSUE THREAD

**Issue by mHatsune** [notable/notable#1194] opened 2020-06-19 11:53 UTC
Add task reminder feature for notable using simple way as recognize from specific markdown. That helps to avoid use another task reminder software on computer.

- Add simple way to enable task reminder for particular note and extendable options for remind multiple times.
- Display missed tasks and closer tasks in quick view window and click on each bring user to particular note

**Comment by fabiospampinato** [comment] 2020-06-19 13:47
Duplicate of #391

**Closed by fabiospampinato** 2020-06-19 13:47 UTC
