### ISSUE TITLE
Open the file with the md extension separately 

### ISSUE THREAD

**Issue by FZ-Miaoyang** [notable/notable#1662] opened 2023-02-21 02:39 UTC
### Feature description

I hope it can open the file with the md extension separately like Typora

### Feature motivation

Because there're many md file at different directory in my disk, I have to switch working directories constantly, which is very inconvenient

Thanks

**Comment by MMK21Hub** [comment] 2023-02-26 13:10
Duplicate of #940 (see #1070, "open Markdown files outside of the data directory")

**Closed** 2023-03-08 01:34 UTC
