### ISSUE TITLE
search on page

### ISSUE THREAD

**Issue by openstep** [notable/notable#845] opened 2019-09-29 07:49 UTC
### Feature description

It would be useful to have an in-page search feature. For example when there are many files and the existing search finds them (like now) but when you click on the file it does not show the matched text on the page. It could work as when you CTRL+F on a webpage or search within a text editor.

**Comment by openstep** [comment] 2019-09-29 07:55
Sorry  I just found this:
https://github.com/notable/notable/issues/140
It is discussing this feature also.

**Comment by fabiospampinato** [comment] 2019-09-29 10:30
Duplicate of #140 and #596

**Closed by fabiospampinato** 2019-09-29 10:30 UTC
