### ISSUE TITLE
Inconsistently overwriting notes with "Untitled" new ones

### ISSUE THREAD

**Issue by mtib** [notable/notable#425] opened 2019-02-06 21:01 UTC
- **OS Version**: Ubuntu 18.10, Mac OSX 10.14

- **Notable Version**: 1.3.0 on both, bug existed in earlier versions too

### Current behavior

This bug might be related to #219 or #175 , because when trying to reproduce it for the video sometimes the #219 bug happens, but if it doesn't and you delete the untitled note, it will instead delete the note you had in focus last.

[Video of this happening](https://youtu.be/SG6PM4vNzzU)

@IdaWhoCantCode who is using the app on OSX, also reports that this happens without deleting the new "Untitled" document, though I only experienced different, but still weird behaviour. (Clones of "Untitled"s, etc.)

### Expected behavior

The note currently in focus should be deleted.

Edit: language

**Comment by mtib** [comment] 2019-02-06 21:11
Put in less techy terms:

> On creation the currently focussed note and the newly created note become the same, basically deleting the content of the old one.

**Comment by mtib** [comment] 2019-02-06 21:20
Sometimes it is just visual: [video](https://youtu.be/b-IhOe4xdNI). Then a restart fixes it. But I've had it now too, where the original file gets outright overwritten.

**Comment by fosslinux** [comment] 2019-02-07 00:18
I can reproduce

**Comment by gpspake** [comment] 2019-02-07 15:11
I can reproduce this. 
You can very easily, irreversably overwrite any note. In fact, it's kind of difficult to avoid. Before I realized this was a recurring problem, I lost hours of work I had typed in a note that just disappeared. This app is just perfect but it's unusable until this is fixed.

[OSX]

**create note A**
- click pencil to enter edit mode
- type "A" in the edit field
- click pencil to exit edit mode.

**Create note B**
- create note,
- click pencil to enter edit mode
- type "B" in the edit field
- click pencil to exit edit mode.

**Overwrite note B with note A**
- click on note A and click on the pencil to enter edit mode
- click on note B (while note a is still in edit mode)
- B will appear selected in the notes list but the contents being edited are still for note a
- click pencil to exit edit mode
- not B will be overwritten with note A and now there will be two note A's

"As a user, if I am editing a note and I switch to a different note, changes should be saved and edit mode should exit before switching to the different note."

**Comment by gpspake** [comment] 2019-02-07 20:37
Same issue as #401

**Comment by rdipietro** [comment] 2019-02-11 14:21
Has anyone isolated exactly what the problem is that causes this (or #401)?

This happened to me, too, but I was luckily using Dropbox and could revert.

In #401 there seems to be some speculation about title formatting being a potential problem but this issue suggests otherwise.

**Comment by rdipietro** [comment] 2019-02-11 15:14
@fabiospampinato I just want to emphasize how crucial this bug is (e.g. in comparison to the KaTeX stuff we chatted about).

I'm on MacOS High Sierra with Notable 1.3.0, and I reproduced this bug with a different sequence of equally harmless actions:

- I created a new notebook dir for testing
- I created a new note called Important
  - Note that unlike above I did not even leave edit mode here
- I hit Cmd + N to create a new note
- This did not create a new note as intended. Instead:
  - The Title bar showed "Untitled", suggesting a new note, but this conflicted with the actual contents of the file, which were duplicated from the Important note
  - After about 1 second of delay, the Title bar updated to reflect this fact, now showing two notes both named "Important"
- Now I edited this file. After this, the content on disk is actually as expected: There is an `Important.md` with old content and `A New Note.md` with new content.
- Now for the crucial bug leading to data loss: I am still in edit mode, and all I do is click on Important, to switch back to that note.
  - Now `Important.md` and its content is entirely gone. Instead, there exists `A New Note.md` and `A New Note (2).md`, both containing the 'new' content that should be in `A New Note.md`.

**Comment by fabiospampinato** [comment] 2019-02-11 15:26
@rdipietro it is very crucial, and I'd like to get it fixed once and for all in the next release.

**Comment by ShaneG** [comment] 2019-02-12 21:24
This is happening in Windows 10 as well, and just cost me an important document that I spent about an hour writing in Notable. When I tried to create a second note there are now 2 versions of the second note, and the important first note is completely gone without a way to recover it.

**Comment by sq-zhang** [comment] 2019-02-13 10:00
I have the same problem. 
// Why I did not see this issue earlier!! I lost my work entirely. soooooo sad.

**Comment by fabiospampinato** [comment] 2019-02-23 21:20
Can somebody still reproduce this from the master branch? I can reproduce a few other bugs, but not this one, I think it might be fixed already in the master branch 🤔

**Comment by fabiospampinato** [comment] 2019-02-23 21:54
@gpspake's steps reproduce this every time from the v1.3.0 commit (https://github.com/notable/notable/commit/7e969ce7498eceba090551eef075dfaa517b085d), but they don't for the current version, so I'm calling this fixed 👍 If anybody can still reproduce this let me know and I'll work on that pronto.

**Comment by CaoZhenggg** [comment] 2019-03-06 01:59
Could you please make a release.

**Closed** 2019-03-06 10:37 UTC
Labels: bug

**Comment by fabiospampinato** [comment] 2019-03-06 10:39
@CaoZhenggg I'm working on it, the switch to Monaco editor isn't quite complete yet (there are some shortcuts to reimplement), and a few more bugs to fix (one of the data loss bugs was linked to CodeMirror, our previous editor, I believe, so I had to replace it and that took a while).

**Comment by nicomazz** [comment] 2019-03-14 18:47
Sadly, I'm loosing notes every day due to that 😢 Since I don't want to change editor, a quick fix with a minor release would be greatly appreciated!

**Comment by fabiospampinato** [comment] 2019-03-14 18:49
@nicomazz I should make a new release today, there's just one issue left to fix for this iteration: https://github.com/notable/notable/milestone/1

**Comment by mikaelmello** [comment] 2019-03-22 13:41
I'm sad to say this is not fixed.

I lost an entire note yesterday but thought it was because of bad sync (I was using ODrive, which is not officially supported, on a bad connection). I then decided to use notable outside of any synced folders, only local files, and lost my notes from an entire lesson after switching back and forth to another note.

I still can't quite reproduce but this is the second time that this happens

**Comment by fabiospampinato** [comment] 2019-03-22 14:44
@mikaelmello I'm sorry to hear that. Since you opened a new issue for this #574 let's track the resolution of this there.
