### ISSUE TITLE
how to update changes edited outside?

### ISSUE THREAD

**Issue by arcturus140** [notable/notable#520] opened 2019-03-07 13:14 UTC
hello, 
How can I see the changes I made outside of notable?

thank you!

**Comment by fabiospampinato** [comment] 2019-03-07 13:20
Hi, are you editing a note with a third-party program and the changes aren't being reflected in Notable? 🤔

**Comment by arcturus140** [comment] 2019-03-08 12:15
I am using the latest version (is there a way to confirm the version from the application?)
on Linux Ubuntu. 

Yes, it is a third-party application. First of all I tried to replicate and everything worked as expected:

Editing an old note externally works
Editing a new note after save works

but, creating a new note and editing it externally **before saving** does not seem to work. 

# Steps to replicate

1. create new note
2. **do not** save the note
3. smash the "Open in Default App" Icon
4. edit & save markdown file in third-party application
5. back to notable, what is next?

I am a first time user

![third-party](https://user-images.githubusercontent.com/44707562/54027983-51d28c00-419b-11e9-991f-bd7c8b06d8d8.gif)

**Comment by arcturus140** [comment] 2019-03-08 12:23
possible duplicate of  #489. I believe my test case is not described there.

**Comment by fabiospampinato** [comment] 2019-05-03 00:20
Closing as duplicate of #489. This specific issue possibly got fixed already, since we are currently saving notes when the editor is blurred and we are also asking the user if he/she wants to preserve unsaved changed when the file gets modified on disk.

**Closed by fabiospampinato** 2019-05-03 00:20 UTC
Labels: bug
