### ISSUE TITLE
How can notable users change the fonts easily?

### ISSUE THREAD

**Issue by gongjianhy** [notable/notable#1283] opened 2020-08-11 09:00 UTC
### Feature description

There is no proper way for users to chagne the fonts when editing.

### Feature motivation

Could you provide the button for users to change the fonts easily?

**Comment by fabiospampinato** [comment] 2020-08-11 09:16
Not yet, but I'll add a setting for that.

Duplicate of #102

**Closed by fabiospampinato** 2020-08-11 09:16 UTC
