### ISSUE TITLE
Uncaught Exception upon opening (if already open)

### ISSUE THREAD

**Issue by joseph-henry** [notable/notable#1101] opened 2020-03-29 19:56 UTC
- **OS Version**: macOS 10.15.4
- **Notable Version**: 1.8.4

### Current behavior

(This has only happened once)

Opening Notable after sleep. Dot next to Notable icon is present, indicating that Notable is already running. Upon clicking, the following error is repeated twice.

```
Uncaught Exception:
Error: The 'screen' module can't be used before the app 'ready' event
    at Object.module.<computed> [as getAllDisplays] (electron/js2c/browser_init.js:6805:30)
    at ensureWindowVisibleOnSomeDisplay (/Applications/Notable.app/Contents/Resources/app.asar/main/main.js:2:111796)
    at validateState (/Applications/Notable.app/Contents/Resources/app.asar/main/main.js:2:112914)
    at e.exports (/Applications/Notable.app/Contents/Resources/app.asar/main/main.js:2:112956)
    at window_Window.make (/Applications/Notable.app/Contents/Resources/app.asar/main/main.js:2:320281)
    at window_Window.initWindow (/Applications/Notable.app/Contents/Resources/app.asar/main/main.js:2:308391)
    at window_Window.init (/Applications/Notable.app/Contents/Resources/app.asar/main/main.js:2:308260)
    at app_App.load (/Applications/Notable.app/Contents/Resources/app.asar/main/main.js:2:324168)
    at App.__activate (/Applications/Notable.app/Contents/Resources/app.asar/main/main.js:2:321959)
    at App.emit (events.js:203:13)
```

### Expected behavior

Notable should start successfully or restart itself to remove it from this state.

### Resolution

Forcibly closing Notable and restarting it.

### P.S.

Great software, other than this single issue it never gives me any trouble and I love it. Nice work!

**Comment by fabiospampinato** [comment] 2020-03-30 16:38
Duplicate of https://github.com/notable/notable/issues/1051

**Closed by fabiospampinato** 2020-03-30 16:38 UTC
