### ISSUE TITLE
new update not functional on windows

### ISSUE THREAD

**Issue by chad-bennett** [notable/notable#724] opened 2019-07-09 13:34 UTC
windows 10 ver 1903
notable 1.60

notable opens and menus are active. cannot create a new document. cannot open a new data folder. cannot close except for using task manager. 

updated over old version. thought that was problem. did clean wipe of everything and then tried fresh install. still doesn't work. 

moving back to old version for now.

**Comment by fabiospampinato** [comment] 2019-07-09 13:48
> did clean wipe of everything and then tried fresh install. still doesn't work.

Did you deleted the `~/notable.json` file also? 

I think this issue might be a duplicate of https://github.com/notable/notable/issues/723

**Comment by fabiospampinato** [comment] 2019-07-09 14:01
Just released v1.6.1: https://github.com/notable/notable/releases/tag/v1.6.1

Can you check if that fixes the issue?

**Comment by ymjonline** [comment] 2019-07-09 14:19
> Just released v1.6.1: https://github.com/notable/notable/releases/tag/v1.6.1
> 
> Can you check if that fixes the issue?

much better, menus work fine
_but_ the meta-data is shown for some of the notes

e.g. 
![image](https://user-images.githubusercontent.com/46528969/60895069-3cae5c80-a264-11e9-943b-1e1ac664036e.png)
and therefore it also shows up as "No Tag"

The common denominator I see is: happens with notes that only have one "Notebook tag" (Notebooks/mytopic) and no other tag.
It does not occur with notes with only one, non-Notebook, tag.

If I add a new tag to those notes, then the former meta-data section becomes part of the body and a new meta-data section is created.

Thanks for your responsiveness !

**Comment by fabiospampinato** [comment] 2019-07-09 14:23
@ymjonline can you post here a note that reproduces the issue?

**Comment by energetic-it** [comment] 2019-07-09 14:25
I had the same issue, just fixed my two notes and went on. I only had one tag on them with nothing else. Don't have an example anymore :(

**Comment by ymjonline** [comment] 2019-07-09 14:30
> @ymjonline can you post here a note that reproduces the issue?


[new project.md.txt](https://github.com/notable/notable/files/3373429/new.project.md.txt)

**Comment by ymjonline** [comment] 2019-07-09 14:39
> > @ymjonline can you post here a note that reproduces the issue?
> 
> [new project.md.txt](https://github.com/notable/notable/files/3373429/new.project.md.txt)

But I've found exceptions

- notes with that single Notebook tag that display well
- or after editing the .md file manually and adding new tags and also reloading Notable, it still display badly...  
not much time right now to get deeper than that I'm afraid

**Comment by chad-bennett** [comment] 2019-07-09 15:14
the update works for me now! noticeably quicker already. 

amazing turnaround time on getting the updated fix out. great job!

**Comment by fabiospampinato** [comment] 2019-07-09 15:30
@ymjonline I can reproduce the issue with the note you provided, I think this might be an issue originating from Windows' weird usage of "\r\n" as a new line delimiter rather than just "\n", not entirely sure yet.

Anyway I'm working on a fix right now, hopefully I should get v1.6.2 ready today.

**Comment by fabiospampinato** [comment] 2019-07-09 17:03
Just fixed this, update coming later today (there are a few more issues to address first).

**Closed by fabiospampinato** 2019-07-09 17:03 UTC
Labels: bug
