### ISSUE TITLE
Allow image size syntax

### ISSUE THREAD

**Issue by tarheels100** [notable/notable#824] opened 2019-09-18 18:32 UTC
#### Specify image size
Add the ability to specify an image's size in pixels.  Assuming that Notable is using markdown-it as the renderer, there is already a plugin that adds this feature: [markdown-in-imsize](https://www.npmjs.com/package/markdown-it-imsize).  This adds the following syntax: 
```markdown
![test](image.png =100x200)
```
which is interpreted as:
```html
<p><img src="image.png" alt="test" width="100" height="200"></p>
```

#### Secondary suggestion: change default image size behavior
By default, images appear to fill the available width of the screen.  Could we change the default behavior such that images are displayed at "actual size" unless a specific size is specified?

### Feature motivation

Stretching images to fill the available width can make small images appear much too large and prevents images being placed side-by-side.

**Comment by fabiospampinato** [comment] 2019-09-22 15:03
> Add the ability to specify an image's size in pixels. 

Sounds like a good idea 👍 

> Could we change the default behavior such that images are displayed at "actual size" unless a specific size is specified?

That's already how it works for me, are you sure the image you're testing this with isn't just that big? Can you post a snippet that reproduces this issue?

**Comment by tarheels100** [comment] 2019-09-23 01:40
@fabiospampinato Based on your suggestion, I did a bit more testing.  I can confirm what you see, which is that Notable does not stretch images to fit, it only scales them down.  However, the confusion was coming from the fact that what Notable thinks is the "actual size" of images is not quite right (i.e., it doesn't match the size shown in Paint and other image viewers).  Perhaps it's an issue with high DPI screens (I use a Surface Pro 4)?

Here's an example.  This is a screenshot of a note with the builtin "icon.png" attachment shown using `![](@attachment/icon.png)`:
![image](https://user-images.githubusercontent.com/29213686/65397817-bab8d480-dd78-11e9-811d-00c17927de3e.png)
Note the title bar at top for scale.

**Comment by fabiospampinato** [comment] 2019-09-23 11:03
> Perhaps it's an issue with high DPI screens (I use a Surface Pro 4)?

Maybe, I'm not sure.

The attached icon is quite large actually, maybe that's why you're seeing it so big?

**Comment by tarheels100** [comment] 2019-09-23 14:19
@fabiospampinato 

> The attached icon is quite large actually, maybe that's why you're seeing it so big?

That's also a good idea to check.  Unfortunately, it looks like the image size is truly inconsistent.  In the screenshot below, I'm showing the same note as before with `![](@attachment/icon.png)` and with the same image open in Paint at 100% zoom level.  
![image](https://user-images.githubusercontent.com/29213686/65433481-b4f7d900-dde2-11e9-8935-ec0c41098e05.png)

**Comment by fabiospampinato** [comment] 2019-09-23 14:22
🤔 I'll have to take a closer look at this.

**Comment by fabiospampinato** [comment] 2020-01-19 18:30
Reference: https://www.npmjs.com/package/markdown-it-imsize

**Comment by KristinnGodfrey** [comment] 2020-03-06 00:53
Has this been implemented?

**Comment by fabiospampinato** [comment] 2020-03-06 00:54
No, if I had implemented it already I would have closed this issue.

**Comment by fabiospampinato** [comment] 2020-03-21 15:25
I'm taking a closer look at this now, the reference implementation for markdown-it is so weird.

**Comment by fabiospampinato** [comment] 2020-03-21 17:47
Implemented.

My implementation is like 100x shorter than one based on markdown-it's internals. Hopefully it shouldn't be 100x slower or 100x less reliable 🤔

**Closed** 2020-03-21 17:47 UTC
Labels: enhancement
