### ISSUE TITLE
Markdown Cheatsheet shows highlighter errors

### ISSUE THREAD

**Issue by rwiesenfarth** [notable/notable#923] opened 2019-11-23 15:30 UTC
- **OS Version**: Windows 10 1903
- **Notable Version**: 1.8.1

### Current behavior

Open Markdown Cheatsheet. All sections below and including "Code" show
"[highlighter error: this._embeddedModes.hasOwnProperty is not a function]" instead of the code to be used.

### Expected behavior

Sections should show "source code" for the mentioned sections.

**Comment by fabiospampinato** [comment] 2019-11-26 18:48
Duplicate of https://github.com/notable/notable/issues/902. In the meantime you can find the cheatsheet at [https://cheatsheet.notable.md](https://cheatsheet.notable.md).

**Closed by fabiospampinato** 2019-11-26 18:48 UTC
