### ISSUE TITLE
Error report: Cannot read property 'source-url' of undefined

### ISSUE THREAD

**Issue by 5472qaywsx** [notable/notable#1196] opened 2020-06-19 14:24 UTC
- **OS Version**: linux 5.4.46-1-lts
- **Notable Version**: v1.8.4

```
TypeError: Cannot read property 'source-url' of undefined
    at EnexNote.getMetadata (file:///opt/Notable/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:185842)
    at async EnexNote.get (file:///opt/Notable/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:3578)
    at async EnexProvider.dump (file:///opt/Notable/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:3469)
    at async Object.dump (file:///opt/Notable/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:201681)
    at async import_Import.import (file:///opt/Notable/resources/app.asar/renderer/renderer.js:2:24287)
```

**Comment by fabiospampinato** [comment] 2020-06-19 14:32
Duplicate of https://github.com/notable/dumper/issues/30

**Closed by fabiospampinato** 2020-06-19 14:32 UTC

**Comment by 5472qaywsx** [comment] 2020-06-19 15:28
Sorry, didn't double-check that it was already addressed; I was sent here automagically from within "Notable".
Keep up the good work!

**Comment by fabiospampinato** [comment] 2020-06-19 15:36
Yes it hasn't been fixed yet, thanks for opening up this issue.
