### ISSUE TITLE
Error report: Cannot read property 'source-url' of undefined

### ISSUE THREAD

**Issue by vanguard737** [notable/notable#1218] opened 2020-07-02 22:36 UTC
Hi,

I exported my Evernote data to a .enex file (~200 notes, ~58MB).  I then tried to import this in Notable via File...Import.  That produced this bug report.  In Notable, I see that 6 of my notes successfully imported before this error broke the import.  Happy to provide more info if necessary.

- **OS Version**: win32 10.0.19577
- **Notable Version**: v1.8.4

```
TypeError: Cannot read property 'source-url' of undefined
    at EnexNote.getMetadata (file:///C:/Users/cjbro/AppData/Local/Programs/notable/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:185842)
    at async EnexNote.get (file:///C:/Users/cjbro/AppData/Local/Programs/notable/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:3578)
    at async EnexProvider.dump (file:///C:/Users/cjbro/AppData/Local/Programs/notable/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:3469)
    at async Object.dump (file:///C:/Users/cjbro/AppData/Local/Programs/notable/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:201681)
    at async import_Import.import (file:///C:/Users/cjbro/AppData/Local/Programs/notable/resources/app.asar/renderer/renderer.js:2:24287)
```

**Comment by fabiospampinato** [comment] 2020-07-02 22:59
Duplicate of https://github.com/notable/dumper/issues/30

**Closed by fabiospampinato** 2020-07-02 22:59 UTC
