### ISSUE TITLE
Note Corrupt

### ISSUE THREAD

**Issue by infosisio** [notable/notable#526] opened 2019-03-08 20:13 UTC
I faced a weird edge case when while in the edit mode of an entry, I clicked on another entry and its contents got copied all over to the other note, erasing what was in it before.

Platform: Ubuntu 18.04 (installed from the .deb)

**Comment by mustakimali** [comment] 2019-03-08 22:45
Yeah I lost some very important notes at work, and then stopped using this app. I really wish there was a easy way to recover those notes. I think the app starts behaving like this if kept open for a very long time.

**Comment by fabiospampinato** [comment] 2019-03-09 00:25
@infosisio I believe this is a duplicate of https://github.com/notable/notable/issues/425#issuecomment-461461126, which should be fixed in the master branch (I can't reproduce it anymore), it would be great if you could check this.

@mustakimali I'm sorry to hear about the data loss 😞

**Closed by fabiospampinato** 2019-03-09 00:25 UTC

**Comment by mustakimali** [comment] 2019-03-09 00:47
Thanks for fixing this, I love your app and I'd give it another try while being careful 🤞.

**Comment by infosisio** [comment] 2019-03-09 00:48
Thanks from me as well! Should we wait for 1.4 deb to get the fix?

**Comment by fabiospampinato** [comment] 2019-03-09 00:56
@mustakimali I'll try to fix any data-loss related bugs promptly in the future, hopefully there won't be any major bugs again. I'm currently fixing those that have already been found already, but unfortunately in order to fix one of them I had to change the editor, so I replaced it with Monaco #203, and that is taking forever. After v1.4 and a few more release where I implement some important features like autocomplete #20 I plan to refactor the project so that it can more easily be managed and properly tested.

@infosisio Yes, we'll have to wait a few more days probably until I ultimate the switch to Monaco and I fix the remaining data-loss-related issues.
