### ISSUE TITLE
Deep link to #id

### ISSUE THREAD

**Issue by francjsca** [notable/notable#914] opened 2019-11-18 13:22 UTC
Hi Fabio,
I want to ask you if it's possible to link an anchor to a part of another note. 
For example, in note A there's a paragraph or another element with a particular #id. In note B I want to open this note directly to this #id, not to the title of the note A.

Thanks,

Francesca

**Comment by fabiospampinato** [comment] 2019-11-18 14:32
Hey Francesca,

This is not possible at the moment, but it seems a useful and perhaps relatively easy feature to implement 👍 How do you think that should look like? Like one would just need to specify an id like so?:

```markdown
[my link](@note/Foo.md#id)
```

**Comment by Optics** [comment] 2019-12-09 15:57
Would be nice to see this type of feature. I would like to link another notes into one so I can directly jump to the other notes.

**Comment by Optics** [comment] 2019-12-09 16:03
Would be nice to see this feature. At the moment it is only possible to link notes without spaces between every word.

**Comment by fabiospampinato** [comment] 2019-12-11 15:41
> At the moment it is only possible to link notes without spaces between every word.

What do you mean? If a note's title or filename contains spaces you should still be able to link to it 🤔

**Comment by Optics** [comment] 2019-12-11 17:18
Okay, that's exactly what I meant. I can link "Test.md" but have problems with "Test test.md".
I am doing it like that [my link](@note/Test test.md).
What am I doing wrong?

**Comment by fabiospampinato** [comment] 2019-12-11 17:19
@Optics Is your note actually named `Test test.md` on disk?

**Comment by Optics** [comment] 2019-12-11 17:21
yes it is

**Comment by fabiospampinato** [comment] 2019-12-11 17:22
Strange, could you zip me up a data directory that reproduces the issue?

**Comment by Optics** [comment] 2019-12-12 07:47
Okay now it works for "Test test.md" for a reason I don't know why.
But a problem that I can also reproduce now are filenames like "Lt.: Test test.md", I think because of the punctuation characters.

**Comment by francjsca** [comment] 2019-12-12 10:21
> Hey Francesca,
> 
> This is not possible at the moment, but it seems a useful and perhaps relatively easy feature to implement 👍 How do you think that should look like? Like would one just need to specify an id like so?:
> 
> ```gfm
> [my link](@note/Foo.md#id)
> ```

Yes, I think it's correct. Thanks

**Comment by Optics** [comment] 2019-12-13 09:35
@fabiospampinato : 
1. Do you know a fix for my problem and are you able to reproduce it?
2. Do you know when you will implement the feature to link to IDs inside a note?

**Comment by fabiospampinato** [comment] 2019-12-14 03:01
@Optics 

1. I can reproduce, the issue you're having is that the title you wrote is not the same as the file name you have on disk. At first look you may not see the difference, but `'꞉' !== ':'`. The thing is some characters aren't safe to be used in file names, so we are replacing them with similarly-looking ones. As a temporary workaround just copy the file name and use that when linking. The proper fix will be to reference notes by their UUIDs (https://github.com/notable/notable/issues/538) rather than by their title.
2. No idea, it should be relatively easy to implement but currently there are other priorities.

**Comment by fabiospampinato** [comment] 2020-01-11 00:23
Duplicate of #697

**Closed by fabiospampinato** 2020-01-11 00:23 UTC
Labels: enhancement
