### ISSUE TITLE
Integrated system's keyboard shortcuts for text and markdown

### ISSUE THREAD

**Issue by semiopat** [notable/notable#703] opened 2019-06-24 14:22 UTC
### Feature description

Notable has no text and mardown keyboard shorcuts, which ends to be annoying. the application would be much more useful and could be recommended to several training groups if it integrated the system's text keyboard shortcuts, such as FSNotes or MarkText (see screenshots below)

### Feature motivation

I use keyboard shortcuts everytime and teach them to my students when it comes to use markdown editors or code editors. I'm about to choose one markdown editor for the next year and try to find the one that reach my goals.

**Comment by fabiospampinato** [comment] 2019-06-24 14:36
I believe this is a duplicate of https://github.com/notable/notable/issues/153? This is definitely a planned feature, maybe I could implement this during next month's iteration.

**Closed by fabiospampinato** 2019-06-24 14:36 UTC
