### ISSUE TITLE
Online Tutorial link is broken

### ISSUE THREAD

**Issue by kscheel** [notable/notable#917] opened 2019-11-18 21:03 UTC
- **OS Version**: Windows 10 1903 (Build 18362.476)
- **Notable Version**: 1.8.1

### Current behavior

Select "Help" from the menu and click "Tutorial". A window appears asking the user to choose between "Online Tutorial" or "Import Notes".

When choosing "Online Tutorial" the following URL is opened, showing a 404 error:
https://github.com/notable/notable/tree/v1.8.1/resources/tutorial/notes

### Expected behavior

This would probably be the correct URL:
https://notable.md/static/pdfs/tutorial/1.8.1.pdf

**Comment by fabiospampinato** [comment] 2019-11-19 00:40
Duplicate of #900.

> This would probably be the correct URL:
> notable.md/static/pdfs/tutorial/1.8.1.pdf

The url I'm using now in the development branch is actually `https://tutorial.notable.md/[version]`, which redirects you to the appropriate pdf, there's also `https://tutorial.notable.md`, which just redirects you to the latest one.

By the way how did you found that file? 🤔

**Closed by fabiospampinato** 2019-11-19 00:40 UTC

**Comment by kscheel** [comment] 2019-11-19 12:25
> Duplicate of #900.

oh sorry, I didn't search closed issues...

> > This would probably be the correct URL:
> > notable.md/static/pdfs/tutorial/1.8.1.pdf
> 
> The url I'm using now in the development branch is actually `https://tutorial.notable.md/[version]`, which redirects you to the appropriate pdf, there's also `https://tutorial.notable.md`, which just redirects you to the latest one.
> 
> By the way how did you found that file? 🤔

https://notable.md/ > More Features > Built-in tutorial > click :)

**Comment by fabiospampinato** [comment] 2019-11-19 12:55
Oh right I updated the website as well, I had forgotten about it.
