### ISSUE TITLE
Persistent tag tree folding

### ISSUE THREAD

**Issue by Armagedoom** [notable/notable#686] opened 2019-06-09 16:31 UTC
### Feature description

Folded / unfolded tags and sub-tags in the tag tree should remain as such even after app restart.

### Feature motivation

There is no need for having to fold all the unused notebooks whenever restarting Notable app.
The tags should remain as they were when Notable was closed.
This is more time consuming the more notebooks one has.

**Comment by fabiospampinato** [comment] 2019-06-09 16:40
Duplicate of #339 (your specific use case is mentioned there).

**Closed by fabiospampinato** 2019-06-09 16:40 UTC

**Comment by PeterlitsZo** [comment] 2020-11-25 11:41
Well, but... It do not remember it even now... :cry:
