### ISSUE TITLE
Toggle state and positions are not honored on restart

### ISSUE THREAD

**Issue by anantshri** [notable/notable#861] opened 2019-10-15 05:33 UTC
- **OS Version**: Ubuntu 18.04
- **Notable Version**: 1.7.3

### Current behavior

1. Start notable
2. Toggle Sidebar 
3. Resize file view on right side.
4. exit 
5. start again. (sidebar is back and file view is back to old size)

### Expected behavior

Over restarts the application should retain the UI changes done by user. 
Sidebar should be hidden and file view specific to the size

**Comment by fabiospampinato** [comment] 2019-10-15 11:42
Duplicate of #339

**Closed by fabiospampinato** 2019-10-15 11:42 UTC
