### ISSUE TITLE
How about... Adding an armhf/armv64 version for Linux? 

### ISSUE THREAD

**Issue by hardwareadictos** [notable/notable#1165] opened 2020-05-25 20:01 UTC
Add armv64/armhf .deb packages 

Because it will expand application support for Chromebooks and Microboards like RPis.

Some people studies and works with ChromeOS, wich has a big arm catalog. Adding support to armv64/armhf will also expand the app into the little board market like Raspberry Pi. 

Thanks into advance for taking into consideration this propose :)

Best regards.

**Comment by fabiospampinato** [comment] 2020-05-25 20:14
Duplicate of https://github.com/notable/notable/issues/1062

**Closed by fabiospampinato** 2020-05-25 20:14 UTC
