### ISSUE TITLE
Emoji Suggestions

### ISSUE THREAD

**Issue by amerchia-mw** [notable/notable#1143] opened 2020-05-08 06:05 UTC
### Feature description
Similar to Slack, allow us to autofill the emoji picker
<img width="355" alt="Screen Shot 2020-05-07 at 11 04 20 PM" src="https://user-images.githubusercontent.com/62902947/81375811-25741180-90b7-11ea-8ccd-b08d38fdcf7b.png">

### Feature motivation
It's too hard to search for emojis and get the code exactly right.

**Comment by fabiospampinato** [comment] 2020-05-08 10:29
Duplicate of #103.

Although it isn't really a replacement for proper autocomplete in v1.9 there will be a searchable palette for emojis:

<img width="720" alt="Screen Shot 2020-05-08 at 11 28 25" src="https://user-images.githubusercontent.com/1812093/81397394-20e34380-911f-11ea-8606-eb187848da4d.png">

**Closed by fabiospampinato** 2020-05-08 10:29 UTC

**Comment by amerchia-mw** [comment] 2020-05-08 16:09
That looks great! Roughly when will v1.9 be released?

**Comment by fabiospampinato** [comment] 2020-05-08 16:19
Unless I encounter too many unforeseen issues or I squeeze in even more features or grossly underestimate the amount of work that's left to do (which I often do) I'd say v1.9 will be released within May.
