### ISSUE TITLE
Highlight the searched keywork.

### ISSUE THREAD

**Issue by evansan** [notable/notable#596] opened 2019-04-03 19:50 UTC
### Feature description
Highlight the searched keyword, and a navigation box  for previous and next occurrence.

### Feature motivation
Currently, it's hard to see when the keyboard is in the document with no highlighting. And hard to navigate when there are multiple matched results.

**Comment by fabiospampinato** [comment] 2019-04-04 09:41
Duplicate of #243

**Closed by fabiospampinato** 2019-04-04 09:41 UTC
