### ISSUE TITLE
Data corruption: Notes disappear

### ISSUE THREAD

**Issue by Armagedoom** [notable/notable#653] opened 2019-05-08 16:16 UTC
I read all the data corruption bugs but none of them seems to describe this situation.

- **OS Version**: Windows 10
- **Notable Version**: 1.4

### Current behavior

This happened several times, but I didn't detect a specific way to reproduce.
When using the middle pane to switch between notes, sometimes a note will be erased and replaced by a copy of the note we are switching to, so you end up with 2 copies of the note being navigated to, and you loose the original note.
My closest guess to reproduce is switching between big notes after scrolling (and possibly before the scroll ends). Not sure though.
I feel this is related to edition being on, so I will just use external editor from now on and see if this happens again.

### Expected behavior

Not deleting / Cloning notes randomly.

**Comment by fabiospampinato** [comment] 2019-05-08 16:19
It sounds like a duplicate of #574, which got fixed in master, feel free to reopen if that's not the case or you will be able to reproduce in v1.5 👍

**Comment by fabiospampinato** [comment] 2019-05-08 16:19
I posted a beta for Windows there, perhaps you could try that 🤔

**Closed by fabiospampinato** 2019-05-08 16:19 UTC

**Comment by Armagedoom** [comment] 2019-05-08 16:21
Thanks, will do!
