### ISSUE TITLE
Notable's Future

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#135] opened 2018-12-30 15:49 UTC
The community's response to this project has been amazing, all supportive comments and suggestions have blown me away, I'd like to thank you all for this and write a few lines about what Notable's future could look like.

I think the goal we should strive for is having the best possible note-taking experience, on any platform and any device, while still remaining true to the reasons why I wrote Notable in the first place, basically your notes will never be locked into a walled garden and the app is never going to become something I won't personally like and use.

In order to achieve that we have to develop internationalized (#126) web app (#83), mobile apps (#23), have a rich plugin ecosystem (#128) and tackle all the issues and good feature suggestions you guys raised. As you can imagine all that requires considerable developer time.

I already spent more than a month working on this full-time, and I obviously need to make a living too. The only way we can afford one or multiple people working full-time on this is if Notable becomes profitable, the alternative is simply greatly slowing down development. 

I'm going to explore what acceptable ways are out there to fund the development, perhaps I could develop some powerful business-oriented and task-oriented features and sell support to companies. I'd be glad to hear your thoughts and suggestions on this.

Notable is here to stay.

**Comment by Philiphlop** [comment] 2018-12-31 07:15
I know it can be a touchy subject for some, but I don't have a problem with subscription to support active development, as long as it's done right. My concern with 

> I could develop some powerful business-oriented and task-oriented features and sell support to companies

Is that you'll end up spending time in these areas, which isn't really focused on your main objectives. So in the end we all suffer. As an end user I saw this with Evernote, adding features I never was interested in (Work Chat, "AI" suggested notes, Presentations) so my subscription was not going to advancements that helped me. I work at a large company with many thousands of employees, and there is no way I would get even my small team (10) to use the same notes app (even getting them to use Office365 spreadsheets is hard). 

A challenge I see with subscriptions is they go from £0 to £60 to £crazy very quickly. As a notes app with no server backend, I suspect running costs are fairly low. Evernote also did this, they changed pricing down the line and they went big (£0, £60, £130). 

`A cup of coffee a month isn't much`, but there are many cups for different things. I don't see many apps out there with a more granular pricing model (perhaps because it's a bad idea, or that everyone thinks it's a bad idea). 

I do think there should be a free tier, as this would help adoption and growth. StandardNotes have recently updated their stuff, but I cancelled my sub a while ago and hessitant to sign up again and regret it. But there are some apps that don't. 

StandardNotes.org tackled this by making extensions to the default a chargeable feature. And you really do want that extension pack, as it's where you get all the goodness. These extensions are more closely aligned to what I want as an end user, but it does feel like there are many overlapping, conflicting, strange mix of extensions to pad out the extensions pack (Rather than 1 customisable theme, there are 5 themes. Rather than 1 customisable editor, there are 5 editors). 

Bear.App tackled this with a low cost option of £15, which is only £1.50 a month, half a cup of coffee. This gives you sync features, which does require them to have a backend system, that has associated costs (as a non-Mac user I don't know much more about this. Though they have been speaking about a WebApp at some point). 

Inkdrop.app has no free tier. Their dev has been clear that for good quality apps there needs to be funding for development. I don't disagree. But if you have a baseline that is free, everyone can use without running costs to you, then paid tier above for more advanced users. Those free users can then progress to paid users in the future (or they will be locked into another app that has this model). 

You could also just sell license keys, one time purchases, but I don't see how these support active development. I see more apps going away from this model to subscription (YNAB). 

No ads please. If you want to have ads revenue, allow a subscription to not have them. 

Don't know if I'm just speaking gibberish, or food for thought, but I will stop here before things get messy.

**Comment by alecgeatches** [comment] 2018-12-31 08:09
In addition to @Philiphlop's great suggestions above, there's also an option for the [Sublime Text](https://www.sublimetext.com/3) model which allows unlimited "trial" usage but features a small nag header after a while. Adding a subscription-based license for a relatively low cost (~$25 a year) would be an effective licensing model for users like me who are happy to pay to get rid of a feeling of guilt.

**Comment by lukaskawerau** [comment] 2018-12-31 17:18
Maybe a combination of the Anki-Model and the Alfred-Model are worth consideration:
Anki's desktop app is free, but the iOS app costs money and seems to support the developer of Anki full time for years now.  
I also like Alfred's "PowerPack" model where you have vast capabilities for free but pay for being able to create your own workflows etc.  
I also recall that there's this website where you can pay for the implementation of issues on OS projects, I forgot what it's called. Maybe that would also be an additional stream of revenue? I'd pay 30€ on the spot for someone to implement the WikiLinks syntax issue (#56, email me, I'm serious!).

**Comment by CavalloneChen** [comment] 2019-01-01 04:11
Agenda has a novel pricing model, you may check that out.

**Comment by fabiospampinato** [comment] 2019-01-01 17:01
@lukaskawerau: 

> Anki's desktop app is free, but the iOS app costs money and seems to support the developer of Anki full time for years now.

That's probably a good option, thanks for suggesting it. Also as soon as there's a mobile app there should be a server for native synchronization, that definitely costs money to operate (and develop!).

> I also recall that there's this website where you can pay for the implementation of issues on OS projects, I forgot what it's called. Maybe that would also be an additional stream of revenue? I'd pay 30€ on the spot for someone to implement the WikiLinks syntax issue (#56, email me, I'm serious!).

I haven't used any of those personally. IMHO it may be a good way of incentive development on particular issues the user base cares about, but also I would prefer if bounties weren't a factor at all in my decisions of what issues/features to fix/implement next.

@CavalloneChen:

> Agenda has a novel pricing model, you may check this out.

IMHO this would be viable mostly only for some business-oriented features. The current set of features is pretty limited if you think about it, restricting access to any of those would probably severely limit the usefulness of the app.

**Comment by drupalshift** [comment] 2019-01-02 07:04
I think you have to have different models for different stages
for example, until it's in development simply put up fundraising which can be seen inside Notable UI that shows milestones and amount that needs to speed up the development with freedom

Notable success is you built something that you wanted to use If you change your priorities toward subscription models and premium features you have to invest a lot of time to build back-end, infrastructure, support, etc let it happen naturally 

I think Sublime model with a bar showing what's going on ( Wikipedia ) would be nice 
And high priority for plugin ecosystem which can lift some weight of your chest

**Comment by MatanRubin** [comment] 2019-01-02 07:57
> Maybe a combination of the Anki-Model and the Alfred-Model are worth consideration:

Many people (including myself) do not like the ever-growing number of subscriptions one has to manage. Both Anki's model and Alfred's model are superior IMO.

**Comment by Johjo** [comment] 2019-01-02 09:07
Hi @fabiospampinato !
Thank you for your work, it's very good.
I'm french and i'm sorry for my english writing, i can make mistake in the words i choose.

Your first business model should be very simple. Thanks to that, you will be able to choose a new business model when it will be necessary. Like i said to my student, do it step by step.

You use MIT license. Unless you change that, if your business model is not good, a fork of Notable could appear in the future. 

I have an another question, what do you want to do ?
- Do you want Notable become your main job ?
- Do you want to do marketing ?
- Do you want to have a lot of customer ?
- Do you want to have a lot of servers ?
- Do you want to stay in open source world ?

You tell us you want to make a mobile app. I suggest you to see if alternativ exists for mobile app. By example, [Joplin](https://joplin.cozic.net/) do that already and it has a a lot of similarities with Notable (But i prefer Notable, even if it is the beginning). 

IMHO, you should start with a simple business model : 
* bounty (@lukaskawerau)
* crowfounding
* milestone with amount (@drupalshift suggestion) (i like this idea because it is you who choose the milestone and you can continue to make feature you want.

and when Notable will be ready, you can choose another business model more restrictive (it's hard to change a business model like subscription).

If you want to stay in open source world, i suggest you to contact association in this domain (in France, you can contact [Framasoft](https://framasoft.org/)).

Good luck in your thinking !

**Comment by Strongaloff** [comment] 2019-01-02 14:42
You could perhaps use [IssueHunt](https://issuehunt.io/) to gain some funds at the moment, until you find a better solution.

**Comment by ulab** [comment] 2019-01-03 12:10
I have never been a fan of subscriptions or nagging people.

One thing I have seen and really liked was the option to purchase / fund a software and only have a minor change that makes me proud to be a supporter. This can be a different logo that has a "banner" mentioning "thanks" or "supporter" or similar.

**Comment by fabiospampinato** [comment] 2019-01-03 13:12
@drupalshift:

> until it's in development simply put up fundraising

While I'd like if the project could be completely donations based, I think it's next to impossible to raise enough money via donations, also if the project could generate enough capital to fund my future projects that's something I'd be also very interested in. After all I wouldn't have been able to dedicate more than a month of my time to this project, and make it open source, if I had no revenue sources at all.

@MatanRubin @ulab:

> Many people (including myself) do not like the ever-growing number of subscriptions one has to manage. Both Anki's model and Alfred's model are superior IMO.

While I also try to avoid subscription-based apps, our costs once the infrastructure is up and running, will be recurrent, also a subscription revenue model will provide more stable funds and the ability to push new features to production immediately, without holding on them for the next major release or something. There will of course be a reasonable free-tier though.

@Johjo:

> You use MIT license. Unless you change that, if your business model is not good, a fork of Notable could appear in the future.

Maybe the license should be changed, I don't want to forbid forks but maybe other people shouldn't be allowed to sell slightly modified versions of Notable or something.

> I have an another question, what do you want to do ?

This is the right question to ask I think, what I want is making the best possible note-taking environment out of this, make Notable profitable enough that pays for at least 1 person working full-time on it (which may not be me in the long run) and possibly generate enough revenue to fund my future projects.

Answering your other sub-questions: I don't see myself working on this full-time for the rest of my life, but I would happily try to build up a team of people that takes care of it in the long run. I'm not that interested in marketing, I'd rather the app be so good that it spreads with word of mouth. The more costumers the better probably, both for me and for the product. The easier the backend infrastructure the better, I'm planning on writing that myself so it should be simple enough that 1 person can reason about it, but powerful enough that it can handle potentially 1 million users. I want the app to remain open source.

> IMHO, you should start with a simple business model : bounty, crowfounding, milestone with amount.

IMHO those options won't provide enough capital, I think that in the long run having a subscription based model (there will be a free tier as well, we can host a few thousands of notes if they have no attachments in just a few megabytes) will be better. I'd rather fund the project myself until it's profitable.

@ulab:

> One thing I have seen and really liked was the option to purchase / fund a software and only have a minor change that makes me proud to be a supporter. This can be a different logo that has a "banner" mentioning "thanks" or "supporter" or similar.

That's an idea, but for the time being I'm focusing on "core" features missing and bug fixing, later that could very well be an option to  consider.

**Comment by MatanRubin** [comment] 2019-01-03 14:58
>  our costs once the infrastructure is up and running, will be recurrent

Can you give more details on this? Assuming sync can continue to work using iCloud/Dropbox etc., what backend do you plan to have?

**Comment by fabiospampinato** [comment] 2019-01-03 15:08
@MatanRubin there's nothing set in stone yet, but I was thinking about providing native synchronization. Of course you will always be able to put the data directory inside Dropbox and do anything you can do today, but in order to provide a more convenient service and in order to implement some possible future features (think about collaborative editing or git versioned notes) I think it would be better not to rely on third-party services like Dropbox for storage and synchronization. It would be weird if in order to use the web-app you'll have to register to Dropbox and link the web-app to it, or if the synchronization doesn't work because you don't have enough free space on Dropbox.

**Comment by gamato** [comment] 2019-01-06 20:18
Hi. First, I've been considering Notable (among other options) specifically because it is free (and being open-source is a nice bonus too). I wouldn't mind a small one-time payment, but I definitely wouldn't pay for subscription. That's one thing that drove me off Evernote (the other being restriction on number of devices). There is ever going number of services people use and subscription payments are getting too high cumulatively. Also, apart from a few small features and improvements I don't really need anything new. I'd be more concerned that the app might get bloated.

Second, I prefer having an independent sync option. Implementing your own synchronisation may allow you to add some new features, of course, but I want to be free to switch sync methods/providers as I want. That also means I could keep using old app without being forced to update or getting cut off. This is actually a common issue on old devices.

Third, since you opensourced the app you risk that someone may just fork your app. Of course we might not get new features, but for many users the app is quite usable already, imho. So you'd need to come up with new features that users would be willing to pay for, instead of just crippling an already good app (as Evernote and others do with their restrictions).

To be honest, I think this is a rather difficult position and there are so many other options that you would really have to shine to make it a sustainable business model. Good luck with that!

PS: Compared to Joplin I consider Notable to be more polished and it feels more native (tested on macOS). Still I prefer fully native apps instead of bloated and resource heavy web frameworks / solutions.

PPS: One example of a working business model might be Enpass password management app. It does not provide its own sync, rather rely on 3rd party (Dropbox, WebDAV, etc). And users pay one time fee for a mobile app (per platform) while all desktop apps are free.

**Comment by fabiospampinato** [comment] 2019-01-06 20:30
@gamato what you can do today you will always be able to do, for instance you could put your data directory in dropbox and have it synched that way. No need to buy a subscription in the future for this.

The web-app will bring convenience, and perhaps in the future some features we can't implement without a server infrastructure. Continuing development of the app and building/operating the server infrastructure costs money, a one-time fee I'm afraid is not going to cut it, if you won't need all this then there's no reason to pay for it.

**Comment by fabiospampinato** [comment] 2019-01-08 15:33
If anyone here works in a team/company that could be interested in switching from their current solution to a Notable-as-a-service solution (basically Notable desktop + a web app) I'd be very interested in hearing what features you'd need and in general what's important for you.

_Whatever perhaps more business-oriented features we might implement are never going to cripple the experience for normal users like other apps are doing_

**Comment by divyanshu013** [comment] 2019-01-15 12:02
How about something like starting a patreon @fabiospampinato? Would be happy to support you.

**Comment by fabiospampinato** [comment] 2019-01-15 14:16
@divyanshu013 unfortunately I don't think donations can provide enough money for this, also I would prefer a more stable and substantial income source.

**Comment by bendem** [comment] 2019-01-16 11:59
If I was to propose this as a tool we use at work, I'd need notable to support ACL-based note sharing to users and groups as well as url based sharing (generate a public unlisted url to view a note).
If the synchronisation-server was self-hostable, I'd want it to support LDAP users.
Pretty sure we'd consider paying per seat / per month for something like notable.

**Comment by fabiospampinato** [comment] 2019-01-16 13:39
@bendem Interesting, thank you. Could you contact me at spampinabio@gmail.com? I'd like to ask you a few more questions.

**Comment by chewy94** [comment] 2019-01-16 23:02
@fabiospampinato it cannot hurt to open up a Patreon or something similar once you decide to start accepting forms of funding. I know and currently work with @johnleider who has a very successful Patreon and might even be able to offer some insight into the donation based funding options. Even if people pledge $300/month it is still passive revenue for you and people really do love to support open source 😄

**Comment by fabiospampinato** [comment] 2019-01-17 02:57
@chewy94 Some people have suggested asking for donations, others have suggested allowing people to add bounties to issues via things like IssueHunt. I think both might be somewhat helpful in the short term, but I think in the long term they may just be a distraction 🤔 I'll think about it, thanks for the suggestion.

**Comment by ymjonline** [comment] 2019-01-18 13:56
>  our costs once the infrastructure is up and running, will be recurrent, also a subscription revenue model 

I think one of the key reasons why most of us are interested is Notable, is the ability to **take back control** of our data and not be forced into syncing our data to someone else's hosting/cloud.

Otherwise it defeats the purpose of Notable in the first place and would be contradictory to one of your key values which is to leave notes independent from this piece of software in the first place: plain markdown files.

Otherwise, how different is it from Evernote ?

I'm not against paying or a subscription model.
However subscription model are typically tied to the underlying sync features, as a way to ensure people keep paying (as opposed to cracking the sw if it was purely "offline")

And I do believe that
- this sync should be optional. I would want to be able to sync my notes the way i feel like e.g. Dropbox-like syncing e.g. NextCloud.
Regardless of the super-duper encryption feature you might come up with

- I'd rather not pay for the hassle of running servers that you will want to charge back to us somehow.

How about a 2-tier mode

1. e.g. 1€ / month for the license of running the software or even Free / donations. No web app.  Self-hosted.
1.1 files remain plain MD files and I can "open folder" from the desktop or mobile app and I handle on my own where this folder is and how it's synced.

2. e.g. 2€ / month will full fledged sync all managed by you
2.1 this includes web app. I imagine you would not be able to run the web app consistently without your own syncing.

**Comment by fabiospampinato** [comment] 2019-01-18 14:16
@ymjonline everything that you can do today you will be able to do in the future, including syncing your notes by putting the data directory in dropbox and whatnot. I haven't decided prices yet, but I want to also include a free tier that provides most of the features, but limited space, to everyone for free.

**Comment by fabiospampinato** [comment] 2019-01-18 16:39
@ymjonline if you'd like to take care of the synchronization yourself and not use the "native" one there's nothing to "control".

**Comment by ymjonline** [comment] 2019-01-18 16:47
> Also as soon as there's a mobile app there should be a server for native synchronization, that definitely costs money to operate (and develop!).
> 

i don't think there should.
this statement scares me a little. Was hopeful that *finally* Notable would be *the* app we were all looking for.
- on Android especially, relying on files from a folder, itself sync'd via NextCloud / Dropbox etc is definitely an option
- or you can "link" the app to native Dropbox, Google Drive or WebDav connectors.
- or to your own Notable-Cloud 

I feel that you should make the app a little bit robust with key features we have reported here (tag management, todo management, UI improvement, mobile app, encryption) before going heads down on a complex cloud infrastructure to manage... and secure.

I understand you see the monetary potential here but probably wise to build upon strong foundations.

I think we all wish you success because I guess I'm not the only one who literally obsessed with finding a good tool.

If you give up on what makes it successful, then I don't see any reason not to go back to things like e.g. Joplin or other (semi-)proprietary tools e.g. Boostnote
- plain markdown files
- nice UI with lots of potential
- tag management using standard YAML

**Comment by fabiospampinato** [comment] 2019-01-18 17:01
@ymjonline as I said: 

> everything that you can do today you will be able to do in the future, including syncing your notes by putting the data directory in dropbox and whatnot. 

You want a mobile app and other people want other features, the only way all this is going to get developed, and developed **well**, is if I can pay one or multiple people to work full-time on this, and in order to do that and not go broke very quickly the project need to be profitable and self-sustaining.

**Comment by mkpaz** [comment] 2019-02-01 17:12
Clearly, none of the companies will ever use Notable, because Notable is a wikipad aka PIM (personal information manager) and companies mostly use multi-user wiki engines. Edit history, user privileges, web ui... all that stuff. There are many options already, both paid (Confluence, Notion) and free (Dokuwiki, XWiki). Your target audience are desktop users only, so if you want to sell your app you have to propose what they ready to pay for. The problem is that your wish to have constant income by selling Notable somewhat contradicts with your another wish about making Notable most-popular extendable and plugin-based app.

I'd say that if you wanna sell your app you have the following choices:

1. Leave desktop version free, sell mobile version. It's more simple to sell software via Google Paly/Apple Store and mobile users are much more willing to pay.

2. Maintain two versions: commercial and free. Commercial version should have unique features that free version haven't. Here is some ideas:
    * using Notable for writing a book or documentation (like git-book)
    * using Notable for writing a blog (integrate with Jekyll)
    * Github Gist integration
    * import/export to proprietary formats (e.g. docx) 
    * web clipper
    * OwnCloud/NextCloud integration

Let's be honest, though. Writing Electron-based note-taking app with tags is [relatively simple](http://electronjs.org/apps?q=note). If you just make the whole app or any of the essential features paid you'll lose your community. Implement plugin system and unique features first then sell it. Right now Boostnote and QOwnNotes as good as Notable and they are both free.

IMO, you don't earn much for sync because:
* you have to pay for hosting too;
* you really have to protect user data and care about privacy. Google, MS, Dropbox have all kinds of professionals. Do you?
* nowadays almost anyone already has cloud storage for free. Why buy another one?

**Comment by fabiospampinato** [comment] 2019-02-01 19:09
@mkpaz 

> Clearly, none of the companies will ever use Notable

Thanks for your feedback, but I think you're being overly pessimistic here, Notable is barely 2 months old (!), in a year or two the product will be radically better.

> The problem is that your wish to have constant income by selling Notable somewhat contradicts with your another wish about making Notable most-popular extendable and plugin-based app.

I don't see the conflict. Clearly the thing people will buy won't be something easily implementable via a plugin.

> Let's be honest, though. Writing Electron-based note-taking app with tags is relatively simple. 

If you don't have any expectations, sure, you can make an app where you can write something in an afternoon. But half of the linked apps don't even seem to tackle the same problem honestly, most of them feel either abandoned or never really developed for an extended period of time, the remaining ones, even established and popular ones like Boostnote I would never use, for example Boostnote has made some terrible design decisions (my notes would have been stored in `.cson` for one) and things paramount _to me_, like attachments, aren't even supported. If you need a comparison about some of the other note-taking apps check [this](https://github.com/fabiospampinato/notable#comparison).

> you have to pay for hosting too;

Clearly paying costumers will have to pay enough for this, I don't see the problem.

> you really have to protect user data and care about privacy. Google, MS, Dropbox have all kinds of professionals. Do you?

All these kinds of professionals didn't help Google with Google+, did they? I don't think this is an insurmountable problem I can't tackle.

> nowadays almost anyone already has cloud storage for free. Why buy another one?

If you only need storage you can absolutely put your Notable data directory inside Dropbox and call it a day, I'm not sure what your point is here. I think most people pay for multiple features, not just storage.

**Comment by mkpaz** [comment] 2019-02-01 20:37
> for example Boostnote has made some terrible design decisions (my notes would have been stored in .cson for one) 

When I installed Boostnote for the first time I thought the same. For now I think this is not really a problem, because data format is [documented ](https://github.com/BoostIO/Boostnote/wiki/Data-format) and I can write a script to export my data in 10 minutes.

Besides, your choice to store notes as plain MD files isn't much better. Notable already have a kind of problem. If two notes shares the same name they will be stored as `name` and `name (2)` which is way uglier than UUID. Because UUID is unique and what is `name` and `name (2)`? Also you'll get performance issues sooner or later. Imagine that user wants to rename its notebook that contain 1000 files. You have to overwrite all these files just to change tag name. What about 10.000? In Boostnote edit a single value in `boostnote.json` is enough. 

> attachments, aren't even supported.

Boostnote supports attachments.

> If you need a comparison about some of the other note-taking apps check this.

I've seen it. It contains many apps that I never heard of. Have to say though, that you operate unobjective terms like "no bloat" or "pretty ui". Both are just a matter of taste.

Ok I've got your point. For now I think that Boostnote is more mature, still I don't like it, but alternatives are worse. If you really can create smth like VSCode for note-taking purposes it'll be really-really great. I even ready to pay for it. Good luck.

**Comment by fabiospampinato** [comment] 2019-02-01 20:51
> When I installed Boostnote for the first time I thought the same. For now I think this is not really a problem, because data format is documented and I can write a script to export my data in 10 minutes.

Not everyone can write that script, but most importantly this has other important (at least for me) downsides, say I want to write a Markdown table and have it formatted properly, what would you do with Boostnote? I guess copying the table manually, pasting it in an editor, setting the language to markdown, running the fancy plugin you already have to formatting tables, copying everything from the editor and finally pasting everything to Boostnote. This isn't great, I can do the same with Notable in 2 shortcuts.

> attachments, aren't even supported.

Actually you're right here, I wasn't aware that you had to drag & drop them inside the note, I'll have to update the comparison table.

> If two notes shares the same name they will be stored as name and name (2) which is way uglier than UUID

I don't think so, would you prefer to look at a wall of UUID instead?

>  Also you'll get performance issues sooner or later

This is a good point. I think there's some big room for optimization, I'd be surprised if once fully optimized the app didn't scale well enough to 100k notes for instance.

>  Have to say though, that you operate unobjective terms like "no bloat" or "pretty ui". Both are just a matter of taste.

Definitely, in fact right below the table I say: "Part of this comparison is personal opinion: you may disagree on the UI front, things I consider bloat may be considered features by somebody else etc. but hopefully this comparison did a good job at illustrating the main differences."

> Ok I've got your point. For now I think that Boostnote is more mature, still I don't like it, but alternatives are worse. If you really can create smth like VSCode for note-taking purposes it'll be really-really great. I even ready to pay for it. Good luck.

Thanks, hopefully I could get something usable in a reasonable amount of time.

**Comment by fabiospampinato** [comment] 2019-02-02 12:56
> Right now you have a bug. If I'll name my note smth like My cool note \m/ it'll be stored as m/.md.

I'm not sure that's strictily a bug, blackslashes (and other characters) are removed, and forward slashes are replaced with something similar.

>  You can easily avoid this problem by storing each note in separate notebook directory.

Except you can't do that because in Notable you can put a note in multiple notebooks, in which folder should you store it then?

> Also I think UUID is better if one wants to store its notes in a git repository (sync + history for free), because file-updating rather than renaming keeps history more consistent.

Maybe, I don't think this will be much of a problem but will see.

**Comment by lukaskawerau** [comment] 2019-02-04 10:49
> > If two notes shares the same name they will be stored as name and name (2) which is way uglier than UUID
> 
> I don't think so, would you prefer to look at a wall of UUIDs instead?

The one thing I would like to see concerning this is the option (!) to make the title of the note (i.e. the first H1 tag) different from the filename.   
What I do is that when I extract quotes from a book, for example, every quote gets its own note. But since I often have tens of quotes from one book, naming them becomes a hassle. I therefore use the citekey of the book (`aurelius2002meditations`) as the first part of the filename and then some unique thing about the quote: `aurelius2002meditations - something.md`
However, that means that the H1 tag in the note has to be also `aurelius2002meditations - something` and I can't have the note say as it's "internal" title `Marcus Aurelius - Meditations: Quote on Something`, if that makes sense.  
Using the H1 as the filename by default is the absolutely right choice and Noteable should keep that, but I would love to optionally set a different internal H1, which I think would also make the UUID vs filename problem less binary.

**Comment by dballance** [comment] 2019-02-04 16:17
Just now taking a look at Notable and excited about the possibilities!

I've been searching for a developer focused notetaking / snippet app for quite a while. I tried all the "Markdown" note apps out there. I'm a current paid subscriber to [Inkdrop](https://inkdrop.app/), and I self host my couchDB instance. Inkdrop is great, but it is also closed source - which in my opinion will be the death of the app long term. It limits the ability to build a community and limits the speed at which bugs can be fixed and features added (only a single developer currently - same with Notable but atleast Notable can take contributions). I have a few other gripes with the app, but I don't believe that they will be fixed as the developer has clearly stated that they're working towards their needs primarily.

Some features I would be interested in: 
- Revisioning - either via git or some other mechanism. Would prefer every time I save or drop focus on the app that the changes be commited so that they can be replayed. 
- Great editing capabilities. I saw in another post that you're looking to utilize Monaco for editing, which would be great! I miss multi-line edit and other VSCode features in Inkdrop. 
- Plugins - which again is in your stated goals!
- Mobile / web versions where appropriate. I know this comes with other problems (like sync / encryption / etc) but if it makes sense would love to see it happen.

I'd be interested in contributing - so I'll maybe try to tackle a bug or two over the next week.

**Comment by bendem** [comment] 2019-02-04 16:21
All those points have their related issues if you wish to discuss them specifically / weight in before it's implemented.
* #116 
* #203 
* #128 
* #7

**Comment by dballance** [comment] 2019-02-04 16:23
@bendem - Yep, I knew some were already planned. Will try to add some thoughts to those. Thanks!

**Comment by Xananax** [comment] 2019-02-05 18:32
I do not know which part of the population I represent, but when I use a free app I like for any modicum of time, specially open source, my reflex is to go to Patreon and look for the author there, and pay between $1 and $10 per month, depending on how much I rely on said app (or how much I think it should exist, even if I don't personally use it). I wish more people would do that, it'd make it easier for devs to do what they do best. You shouldn't be thinking of monetisation schemes. That's now what we enjoy doing!

It's only when writing this comment that I noticed there *is* a Patreon: https://www.patreon.com/fabiospampinato

(I wish there was a $7 subscription like Evernote)

For me, if Notable supported `todo.txt` format, it would be a great companion to [Markor](https://github.com/gsantner/markor), which I use on mobile, and would cover 90% of my note taking/organisational needs. I don't think a lot of people need this, but maybe I'll open an enhancement PR all the same.

As for the commenter who's saying it's "easy" to build something like Notable; obviously not. It's easy to build an MVP in a couple of hours, yes. But bringing a quality app to life is not in any way easy, or else, all of us here, who are all developers, and who can all use Electron, wouldn't be thinking of using a 3rd party app. There's value in a finished, polished product that isn't found in the sum of its parts.

**Comment by fosslinux** [comment] 2019-02-06 07:09
Notable is a great app. One of my favourite things about it is that it's open source. I recommend that re $$$:

keep it open source.

have a hosted version online or something, for convenience, and allow people to build it themselve,. locally.

my 2 cents

**Comment by zelienka** [comment] 2019-02-11 16:38
Someone might have said it already, but I kinda like the model they have in Bear. You can basically whatever you want, and if you want more customization, you can pay either monthly or yearly, where yearly payment is about $15 if I'm not mistaken.

**Comment by fabiospampinato** [comment] 2019-02-11 16:40
@zelienka IMHO customization, mainly in the form of plugins #128, could be one of Notable's main advantages, I'd rather not restrict that to anyone.

**Comment by zelienka** [comment] 2019-02-11 17:25
@fabiospampinato My bad I mean more of graphical customization, like different backgrounds, fonts etc.

**Comment by ntessore** [comment] 2019-02-14 09:36
FWIW, I would gladly pay a one-time fee <= £50 for this. I like licenses (even with payable upgrades) a lot more than subscriptions: if the publisher stops supporting the app, I still have my license, but not my subscription.

**Comment by fabiospampinato** [comment] 2019-02-14 13:25
@ntessore one-time payments aren't sustainable for this business model, with £50 we just can't provide you hosting for your notes and attachments for the rest of your life, and we can't charge a one-time payment of £1000 or whatever either. Plus I'd like to hire somebody at some point to work on this full-time, we need a more stable income source for that. IMHO the best option is to make a subscription-based service for those who need this, while still keeping the app completely free for use in case you don't need any server-side services provided.

**Comment by lukaskawerau** [comment] 2019-02-14 13:40
I would still suggest checking with [Setapp](https://setapp.com/developers) if you can release Notable there in addition to here. As far as I know there are a bunch of apps released both on Setapp and elsewhere at the same time (such as Marked and Timing, for example), so I guess that would work here too.  
No additional work on your part, but steady income from all Setapp subscribers who use your app (such as myself). Again, I think you should definitely get in touch with them.

**Closed** 2019-02-22 00:06 UTC
Labels: announcement

**Comment by ajit555db** [comment] 2019-08-17 05:19
Notable can be a native GUI Frontend for markdown based static site generators like Hugo (https://gohugo.io/tools/frontends/). For non-programmers, managing the front end matter & md content via Notable can be valuable enough as a paid product.

**Comment by fabiospampinato** [comment] 2019-08-17 11:43
@ajit555db I've been thinking about this for a bit, I believe this will become possible once we implement a plugin architecture #128 and add the proper APIs for implementing something that takes all notes inside a tag/notebook and makes a website out of that.

**Comment by ajit555db** [comment] 2019-08-20 14:25
Read the plug-in thread and feel that it is the right direction for sustainable revenues:

Free tier:

- Core app on desktop OSs
- Free plug-ins

 Paid tier:

- Server-side functionalities e.g. sync across devices / multi-user editing / version management etc.
- Mobile app
- Paid plug-ins 
- As a white-label product that can be integrated with other server/desktop products for markdown documents editing.

**Comment by fabiospampinato** [comment] 2019-08-20 14:48
@ajit555db Yeah I feel mostly the same way.

> Paid plug-ins

As there are paid Chrome extensions I suppose eventually we could also add paid plugins, but the thing is if a paid plugin can be substituted with a free one I don't think many people are going to buy the paid one, and I don't want to cripple the plugin API to limit plugins.

> As a white-label product that can be integrated with other server/desktop products for markdown documents editing.

I don't have much experience in this area, but I suppose we can do something about this as well.

**Comment by AldieNightStar** [comment] 2019-12-06 12:07
I hope, that FREE notable will note became PAY-TO-USE stuff :/ ?

**Comment by fabiospampinato** [comment] 2019-12-11 15:42
Whatever is available today for free will be available in the future for free as well, with the exception of some link sharing features maybe.
