### ISSUE TITLE
"app" in heading seems to truncate remaining text

### ISSUE THREAD

**Issue by agorf** [notable/notable#586] opened 2019-03-27 08:49 UTC
- **OS Version**: Debian GNU/Linux Stretch
- **Notable Version**: 1.4.0

### Current behavior

Entering:

```
before

## app

after
```

Results in everything after "app" not showing, and also app is not properly styled (missing bottom border).

Same happens for `# app` or `## .app`

### Expected behavior

All text should be visible.

**Comment by jeff9315** [comment] 2019-03-27 10:30
I thought I had noticed something similar in 1.3.0 but I can't duplicate it in 1.4.0 so I'm not sure if it went away or is just in certain situations. When it occurred for me, it didn't occur for the phrase _app_, it occurred for any Heading. However, as I tested this out, I also noticed that if the level 1 heading ends in _#_ (or any number of  _###_), then  the trailiong _#" signs  go into the tile and the filename and I don't think it should.

Also, the ending _#_ signs should NOT show up in the view ONLY be kept in the editor. That's working the way it should ... I just don't want anyone to think I want the viewer to be changed.

**Comment by fabiospampinato** [comment] 2019-03-27 14:59
Duplicate of #509, I'll address this by not using ids. Even though that not the "proper" solution it will avoid all these kinds of incidents in the future.

>  I can't duplicate it in 1.4.0

@jeff9315 you can replicate it with the text provided by @agorf?

> I also noticed that if the level 1 heading ends in # (or any number of ###), then the trailiong _#" signs go into the tile and the filename and I don't think it should.

We strip out any Markdown from titles and filenames and also sanitize the latter. Since trailing `#`s aren't special Markdown characters I think they should be included in the title, why wouldn't they? 🤔 With regard to filenames I'll check if they may cause some issues on some systems, but since we are sanitizing those filenames already they probably don't cause issues, so I would keep them there.

**Closed by fabiospampinato** 2019-03-27 14:59 UTC

**Comment by jeff9315** [comment] 2019-03-27 20:30
I actually thought that trailing `#` in H1-H6 headings were legal Markdown ... not parsed but used as an optional visual indicator. Any other Markdown editor I've used has stripped them out of the Preview.

**Comment by fabiospampinato** [comment] 2019-03-27 20:32
@jeff9315  That's interesting 🤔 I've just tested this here on GitHub and it seems to work as you say, could you open a separate issue about this?

**Comment by fabiospampinato** [comment] 2019-05-04 18:01
@jeff9315 the issue you encountered with ending `#`s has now been fixed: https://github.com/notable/notable/commit/d338f3c327bfb2a0b421aeecff37500e3e35dfe0
