### ISSUE TITLE
Inline Equation problem

### ISSUE THREAD

**Issue by whimian** [notable/notable#628] opened 2019-04-25 03:38 UTC
- **OS Version**: Windows 10
- **Notable Version**: 1.4.0

### Current behavior

This Inline equation:

```
$\mathbf{{Q}_{2}}$
```

is shown as:

![image](https://user-images.githubusercontent.com/3821278/56708102-1d685e80-674e-11e9-87a4-f44bbfaad20f.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/3821278/56708134-353fe280-674e-11e9-9d5b-c7f476f1390e.png)

On KaTeX website, It displays the expected result:
![image](https://user-images.githubusercontent.com/3821278/56708213-7506ca00-674e-11e9-8424-d67621c1e6d6.png)

So, this may not be a KaTex problem.

**Comment by fabiospampinato** [comment] 2019-04-25 14:13
It seems this is a duplicate of #448, it should get fixed by passing the text through KaTeX before rendering all the rest from Markdown #460.

**Closed by fabiospampinato** 2019-04-25 14:13 UTC
