### ISSUE TITLE
Do not show Notes in whole tag hierarchy.

### ISSUE THREAD

**Issue by exislow** [notable/notable#1276] opened 2020-07-22 16:00 UTC
I like the idea of nested tags. But currently the notes in the very last nested tag of a hierarchy are shown in every level of the hierarchy which makes it messy and does not really comply with the idea of nested tags IMHO.

## Example

I have a note `b.md` which has the tag `car/engine/service`.

If I browse to `car` I will see `b.md`. If I browse to `car/engine` I will see `b.md`. But I do not want to see it there.

I simply want to see `b.md` in the middle column of Notable only if I browse to `car/engine/service`. Is this somehow possible to configure / implement?

**Comment by fabiospampinato** [comment] 2020-07-22 16:04
Duplicate of https://github.com/notable/notable/issues/625

**Closed by fabiospampinato** 2020-07-22 16:04 UTC
