### ISSUE TITLE
copy button for code sections

### ISSUE THREAD

**Issue by Adrian-Grimm** [notable/notable#517] opened 2019-03-06 12:38 UTC
### Feature description

A copy Button at the top right corner of each code-section redered in markdown.
If clicked the whole code of that section should be copied to the clipboard.

### Feature motivation

To be able to quickly copy a code snippet.
This would be easier than select and copy manualy

**Comment by fabiospampinato** [comment] 2019-03-06 18:13
Duplicate of #436

**Closed by fabiospampinato** 2019-03-06 18:13 UTC
