### ISSUE TITLE
Organize Tagged Notes

### ISSUE THREAD

**Issue by benjaminwolkchen** [notable/notable#1122] opened 2020-04-17 15:00 UTC
### Feature description

Organize Tagged Notes in specific subdirectorys. e.g. a note tagged "to-do" will go in <NOTEDIRECTORY>/to-do/notename.md

### Feature motivation

I want this, because my notes folder gets cluttered quickly and i often need to search through it by tags.

**Comment by fabiospampinato** [comment] 2020-04-17 22:19
Duplicate of #54

**Closed by fabiospampinato** 2020-04-17 22:19 UTC
