### ISSUE TITLE
Error report: e.name.trim is not a function

### ISSUE THREAD

**Issue by guyeu** [notable/notable#1373] opened 2020-11-20 09:18 UTC
- **OS Version**: darwin 10.16.0
- **Notable Version**: v1.8.4

```
TypeError: e.name.trim is not a function
    at EnexAttachment.sanitizeMetadata (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:5173)
    at file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:4913
    at Array.map (<anonymous>)
    at EnexAttachment.get (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:4901)
    at async Promise.all (index 1)
    at async EnexNote.getMetadata (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:185659)
    at async EnexNote.get (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:3578)
    at async EnexProvider.dump (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:3469)
    at async Object.dump (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:201681)
    at async import_Import.import (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.js:2:24287)
```

**Comment by fabiospampinato** [comment] 2020-11-20 17:05
Duplicate of https://github.com/notable/dumper/issues/32

**Closed by fabiospampinato** 2020-11-20 17:05 UTC
