### ISSUE TITLE
Using the word 'app' in a heading breaks rest of view

### ISSUE THREAD

**Issue by keithdadkins** [notable/notable#572] opened 2019-03-21 18:37 UTC
- **OS Version**: MacOS 10.14.3 
- **Notable Version**: 1.4.0

### Current behavior
When you add a markdown heading using the word 'app', the rest of the note fails to render.

`# app`, `## app`, `### app`

### Expected behavior

Any word should be usable for a heading title.

<img width="632" alt="Screen Shot 2019-03-21 at 1 35 21 PM" src="https://user-images.githubusercontent.com/539260/54776468-34131700-4bde-11e9-850b-8408d11728be.png">

<img width="629" alt="Screen Shot 2019-03-21 at 1 36 11 PM" src="https://user-images.githubusercontent.com/539260/54776521-51e07c00-4bde-11e9-9e49-bb67397dc4c7.png">

**Comment by fabiospampinato** [comment] 2019-03-21 18:39
Duplicate of https://github.com/notable/notable/issues/509. This is happening because the style applied to the whole app gets also applied to the note.

**Closed by fabiospampinato** 2019-03-21 18:39 UTC
