### ISSUE TITLE
Pause during selection of long/complex note

### ISSUE THREAD

**Issue by lmihalkovic** [notable/notable#450] opened 2019-02-12 19:49 UTC
I made a long note, with multiple mermaid diagrams and linked images. Selecting the note in the sidebar leads to a temporarily frozen UI right after clicking. 

It might be worth exploring letting the selection complete in the sidebar (meaning activating the highlight) and then aynchroneously firing the actual load and render. This would give a better feel, even if the user still has to wait a little. Selection of a new note would have to be guarded until loading is complete

A possible enhancement would be the cancellation token pattern used in vscode. But i have to admit that i have not thought through the details of how to do that one. But this is not unlike the pattern typically  used in ios code to support switching selection around while a background load operation is completing.

**Comment by fabiospampinato** [comment] 2019-02-12 19:51
Duplicate of #113.

**Closed by fabiospampinato** 2019-02-12 19:51 UTC
