### ISSUE TITLE
Create new note prompt dialogue appear twice

### ISSUE THREAD

**Issue by ericaxu** [notable/notable#997] opened 2020-01-17 00:40 UTC
- **OS Version**: Windows 10
- **Notable Version**: 1.8.2

### Current behavior

Use the `[[note name]]` syntax to link to a non-existent note. Click on that link after exiting edit mode. The warning dialogue appears again after clicking either "Yes" or "Cancel".

### Expected behavior

The dialogue should not appear again after clicking on either option.

**Comment by fabiospampinato** [comment] 2020-01-17 18:02
I'm pretty sure this is actually a duplicate of #779, which got fixed and the fix will be available soon in v1.8.3.

**Closed by fabiospampinato** 2020-01-17 18:02 UTC
