### ISSUE TITLE
TeX parser to improve: specific example

### ISSUE THREAD

**Issue by gcfer** [notable/notable#581] opened 2019-03-24 13:26 UTC
- **OS Version**: macOS 10.14.3
- **Notable Version**: 1.4.0

### Current behavior

Write ($i$). For some reason it does not parse it correctly and it shows it verbatim.

### Expected behavior

It should give a math i inside parentheses like in TeX.

**Comment by fabiospampinato** [comment] 2019-03-24 18:32
@gcfer can you paste a full note that shows this problem? I've tried reproducing it but I get it rendered properly.

**Comment by gcfer** [comment] 2019-03-24 19:10
Unfortunately I cannot reproduce the issue always, but in the attached file I could (I had to change the extension to txt to upload it, but it was an md file created with Notable). I don't know if there are hidden characters or what is happening behind.
[Example.txt](https://github.com/notable/notable/files/3000741/Example.txt)
Thanks for your help! Notable is really beautiful and it's improving :)

**Comment by OnyxDelta** [comment] 2019-03-25 13:49
I have noticed this issue as well.  It appears to occur when one uses more than a single inline TeX expression.  For example:
[Image](https://user-images.githubusercontent.com/12561892/54923655-b0587380-4ed8-11e9-8358-0c69f6024051.png)
This is caused by the attached markdown:
[Example.txt](https://github.com/notable/notable/files/3003469/Example.txt)

**Comment by fabiospampinato** [comment] 2019-07-08 23:45
Fixed in v1.6.

**Closed by fabiospampinato** 2019-07-08 23:45 UTC
Labels: bug, katex
