### ISSUE TITLE
I have two suggestions for the label feature.

### ISSUE THREAD

**Issue by chaowise** [notable/notable#1096] opened 2020-03-26 02:02 UTC
I want the label to be modified directly.

I want to search for existing tags when I add them for selection. Of course, the ability to add new labels is also preserved.
For example.Already has the label" b/a".When I add a label, I enter a.Then I have two options, select b/a, or create a.
Did I make myself clear? Do you think my idea works?

**Comment by fabiospampinato** [comment] 2020-03-26 11:39
Assuming by "label" you mean "tag".

> I want the label to be modified directly.

Duplicate of #480 

> I want to search for existing tags when I add them for selection.

Duplicate of #20

**Closed by fabiospampinato** 2020-03-26 11:39 UTC
