### ISSUE TITLE
Notes deleting when switching between notes in edit mode

### ISSUE THREAD

**Issue by jasonwhat** [notable/notable#575] opened 2019-03-22 15:36 UTC
- **Linux/ChromeOS*:
- **Notable Version: 1.4**:

### Current behavior

I'm still trying to figure out when this happens, but when I switch quickly between notes in edit mode, one note overwrites the other. 

Example:
1. Note called "Notable is Awesome
2. Create a new note "Love Notable"
3. Switch to Notable is Awesome while in edit mode
4. "Notable is Awesome" is now called "Love Notable" and has all the notes text.
5. I can't recover the old note in my director

Oh, and the only thing the original note retains is any attachments or tags.

### Expected behaviour

Notes do not get overwritten.

**Comment by fabiospampinato** [comment] 2019-03-22 15:41
It sounds like a duplicate of #574 maybe? Does this happen also if you don't actually edit those notes but are just in edit mode?

**Comment by jasonwhat** [comment] 2019-03-22 16:09
Yes, sorry I missed that bug before. This seems to be the same.

**Closed** 2019-03-22 16:11 UTC
Labels: needs more info

**Comment by konantian** [comment] 2019-03-26 17:16
This is a bug when I switching between two notes, especially when I working on my current notes which is in edit mode. If I click other notes, the then content of another note will be overridden by current note.

**Comment by fabiospampinato** [comment] 2019-03-26 17:35
@konantian I think is has been reported here: #574, let's track its resolution there.
