### ISSUE TITLE
broken on mac

### ISSUE THREAD

**Issue by freder** [notable/notable#723] opened 2019-07-09 13:09 UTC
- **OS Version**: macos 10.14.5
- **Notable Version**: 1.6.0

### Current behavior
I get this on first launch
<img width="1643" alt="Screenshot 2019-07-09 at 15 08 20" src="https://user-images.githubusercontent.com/724844/60890386-77f85d80-a25b-11e9-84d9-1fea48b0a0a7.png">

+ app has to be force quit.

**Comment by fabiospampinato** [comment] 2019-07-09 13:14
Duplicate of #720

**Closed by fabiospampinato** 2019-07-09 13:14 UTC
