### ISSUE TITLE
Startup issue with Notable 1.6.0

### ISSUE THREAD

**Issue by franek** [notable/notable#722] opened 2019-07-09 11:29 UTC
- **OS Version**: Ubuntu 19.04
- **Notable Version**: 1.6.0

### Current behavior

I have updated Notable to the last version (1.6.0) and Notable does not work anymore.
It starts but it does not show my notes.

In developer tools, I have this error : 

```
Uncaught (in promise) TypeError: Cannot read property 'title' of undefined
    at note_Note.sanitize (renderer.js:1)
    at note_Note.read (renderer.js:1)
    at /opt/Notable/resourc…asar/renderer.js:34
    at async Promise.all (/opt/Notable/resources/app.asar/index 1)
    at async Notes.refresh (renderer.js:34)
    at async Notes.reset (renderer.js:34)
    at async ComposedStore.API.reset (renderer.js:1)
    at async ComposedStore.API.init (renderer.js:1)
```

![image](https://user-images.githubusercontent.com/417716/60884613-99524d00-a24d-11e9-8610-02206025205e.png)

### Expected behavior

I expect that all notes are correctly loaded and that I can edit or create new notes.

**Comment by fabiospampinato** [comment] 2019-07-09 12:06
Duplicate of #720

**Closed by fabiospampinato** 2019-07-09 12:06 UTC
