### ISSUE TITLE
File dissapear after add an emoji as Tag

### ISSUE THREAD

**Issue by esturniolo** [notable/notable#847] opened 2019-10-02 20:43 UTC
- **Kubuntu 18.04**:
- **1.7.3**:

### Current behavior
I don't know what really happens here. The current behavior are from Linux and no from Notable, but as you can edit a note everywhere, I think that you should know this.

As you can see, the "Test" notebook starts with 2 notes.Bbut when I add an emoji in the Tag section and save the note, automagically the note dissapear from the system, and of course, from Notable too.

This is a Vodoo thing...

![notableBug](https://user-images.githubusercontent.com/5169045/66080060-b1c7c000-e53b-11e9-92f6-9846a597de2a.gif)

### Expected behavior

Add an emoji on Title Notebook and keep the file.

**Comment by fabiospampinato** [comment] 2019-10-02 20:58
That... strange! Is any other program doing something with the data directory? (i.e. Dropbox, Google Drive or others)

I've just tried this in my system and it just causes the note's metadata to not be parsed correctly, that's to be expected because that's no longer valid YAML actually.

**Comment by fabiospampinato** [comment] 2019-10-02 20:58
Also can you reproduce even if Notable is closed?

**Comment by esturniolo** [comment] 2019-10-02 21:27
> Also can you reproduce even if Notable is closed?

Nope.
The behavior is only when Notable is running, so it's not a Linux issue.
I tried again without Notable running and with the same pCloud configuration (where the notes are stored).
For a strange reason, Notable deletes the note.

**Comment by esturniolo** [comment] 2019-10-02 21:28
> That's... strange! Is any other program doing something with the data directory? (i.e. Dropbox, Google Drive or others)
> 
> I've just tried this in my system and it just causes the note's metadata to not be parsed correctly, that's to be expected because that's no longer valid YAML actually.

I can't test it on those services... Sorry.

**Comment by fabiospampinato** [comment] 2019-10-02 21:28
That's weird. Can you reproduce also if the data directory is outside of pCloud's folder?

**Comment by esturniolo** [comment] 2019-10-02 21:31
> > Also can you reproduce even if Notable is closed?
> 
> Nope.
> The behavior is only when Notable is running, so it's not a Linux issue.
> I tried again without Notable running and with the same pCloud configuration (where the notes are stored).
> For a strange reason, Notable deletes the note.

**UPDATE:** if I modify the md file without Notable running, and then open it, the note shows as "Untagged" note.

![imagen](https://user-images.githubusercontent.com/5169045/66083464-bf347880-e542-11e9-9302-023ab862de21.png)

**Comment by fabiospampinato** [comment] 2019-10-02 21:34
> UPDATE: if I modify the md file without Notable running, and then open it, the note shows as "Untagged" note.

Which is the expected behavior.

> I've just tried this in my system and it just causes the note's metadata to not be parsed correctly, that's to be expected because that's no longer valid YAML actually.

Can you see what happens when putting the data directory outside of pCloud and having Notable running?

**Comment by esturniolo** [comment] 2019-10-02 21:34
> That's weird. Can you reproduce also if the data directory is outside of pCloud's folder?

Still as untagged...
So it's a issue that involve pCloud...

More mistery.

**Comment by esturniolo** [comment] 2019-10-02 21:39
I'll cry...
Now, even with the pCloud sync running (I mean with the same setup as the beggingin of the reported issue), the file moves to Untagged state.

I don't know what happen really.

**Comment by fabiospampinato** [comment] 2019-10-02 21:48
I think this issue may be related to others like https://github.com/notable/notable/issues/515.

I'm not sure what is going on, and this seems to be dependent on each cloud provider's behavior, but I have a theory:

- As of v1.7.3 Notable isn't writing files atomically (🤦‍♂)
- I've noticed in some of my tests that Notable might detect that a note has been changed, but its content will be completely empty.
- I'm not sure why that's happening but I guess since we are not writing files atomically the OS is kind of emptying the current file and then writing the updated content in, or something of the same effect.
- Then I guess some cloud providers delete files with completely empty content or that get emptied. I wouldn't expect this, but I wouldn't expect Notable itself deleting notes either 🤔 

I'll try to get this fixed in a new patch release, I'll probably attach here a preview build so that you can check if the issue is fixed on your system. What package format do you prefer, AppImage?

In the meantime you might want to put your data directory outside of pCloud.

**Comment by esturniolo** [comment] 2019-10-03 13:13
Hi again.
An AppImage it's ok for me.

**Comment by fabiospampinato** [comment] 2019-11-04 22:13
- The note is showing as untagged because the metadata you're generating isn't valid YAML actually. Also Markdown isn't supported outside of the actual note content, so `:dog:` won't be replaced the actual emoji.

- I'm pretty sure this is a duplicate of #515, and I think I've found the issue, an update fixing this is coming soon.

**Closed by fabiospampinato** 2019-11-04 22:13 UTC
Labels: bug, critical
