### ISSUE TITLE
most dangerous bug

### ISSUE THREAD

**Issue by CaoZhenggg** [notable/notable#512] opened 2019-03-05 07:21 UTC
Hi,

While editing a note，then click another note（before click “Stop Editing” bar），the “another note“ will be disappear and was substituted to the newer unaccomplished note.

**Comment by CaoZhenggg** [comment] 2019-03-05 07:22
version：1.3.0

**Comment by fabiospampinato** [comment] 2019-03-05 12:54
Duplicate of https://github.com/notable/notable/issues/425#issuecomment-461461126.

I can't reproduce this anymore on the master branch, it'd be great if you could test that too.

**Closed by fabiospampinato** 2019-03-05 12:54 UTC
