### ISSUE TITLE
Cropped text in Mermaid

### ISSUE THREAD

**Issue by dobomode** [notable/notable#1418] opened 2020-12-26 12:09 UTC
- **OS Version**: Mac OS Catalina
- **Notable Version**: 10.15.5

### Current behavior

Rendering simple graphs in Mermaid produces cropped text within nodes. See example:
```
graph TB
  node1[Node] --> node2[Client] -->  node3[Gateway] -->  node4[Text is cropped]
```

![image](https://user-images.githubusercontent.com/8964150/103151124-b1e15a80-4794-11eb-8208-783d16a17591.png)

### Expected behavior

All text should fit within nodes.

**Comment by fabiospampinato** [comment] 2021-04-01 20:18
Duplicate of https://github.com/notable/notable/issues/1027

**Closed by fabiospampinato** 2021-04-01 20:18 UTC
