### ISSUE TITLE
Vi-mode option

### ISSUE THREAD

**Issue by s1dh** [notable/notable#849] opened 2019-10-03 10:59 UTC
Would it be possible to add an optional Vi-mode for editing/managing notes, like the one added in Sublimetext e.g 

A modal editor adds *LOTS* of functionalities that are keyboard centric.

Precious screen space would be gained and one could use splits and self tunable macros etc.

What do you think of it ?

**Comment by johnletey** [comment] 2019-10-03 11:03
Duplicate of #52

**Closed** 2019-10-03 11:19 UTC
