### ISSUE TITLE
Another data corruption bug

### ISSUE THREAD

**Issue by gramster** [notable/notable#604] opened 2019-04-08 21:41 UTC
- **OS Version**: 10.14.4
- **Notable Version**: 1.4.0

### Current behavior

I edited a note that had just a title, to add some content. Switched out of editing mode, and all the content disappeared, but the title remained.

I have one more issue to report but sadly this is now one too many and I am going to abandon Notable. Going back to MWeb as it can handle arbitrarily named .md files as well.

### Expected behavior

Don't erase my work.

**Comment by fabiospampinato** [comment] 2019-04-09 12:10
I'm sorry you're experiencing all these issues.

I still want to get all those fixed though, so let me see if I'm understanding this issue correctly:

1. You're editing a note, which contained just its title
2. You switched back to preview mode after having added some content
3. Basically the note wasn't saved and all the edits you made disappeared

Is that correct?

**Comment by gramster** [comment] 2019-04-09 13:11
Yes. Exactly what happened.

**Comment by gramster** [comment] 2019-04-09 14:17
No.

**Comment by invad0r** [comment] 2019-09-03 13:11
Can confirm behavior on:

- OS Version: 10.13.6
- Notable Version: 1.7.3


I sometimes add a note by creating a notable-reference  e.g.`[[some Note]]`, click on it, confirm prompt with yes and start typing/pasting, when I hit `cmd+s` for preview I only see Untitled, no headline "some Note" and content is gone. Unfortunately can't reproduce reliably.

**Comment by fabiospampinato** [comment] 2020-01-14 19:12
I think this was a duplicate of https://github.com/notable/notable/issues/966, which is now (mostly) fixed, there's still a deeper issue that may cause, in rare occasions, this to happen again but I think I need to significantly rewrite our state management library to get rid of it, which I'm going to do during the v1.9 iteration.

If anybody can still reproduce this after v1.8.3, or without having an active search query in the app, I'd be happy to reopen and take a closer look at this.

**Closed by fabiospampinato** 2020-01-14 19:12 UTC
Labels: bug, critical, help wanted
