### ISSUE TITLE
Create note from link

### ISSUE THREAD

**Issue by Fastidious** [notable/notable#381] opened 2019-01-30 20:45 UTC
### Feature description

When linking to another note, if such note doesn't exist, present a new empty one on edit mode, upon following the link.

### Feature motivation

Make it easier to create a flow of information, which is perfect for brain dumps, personal knowledge bases, etc.

**Comment by fabiospampinato** [comment] 2019-02-22 00:17
Closing as duplicate of #262

**Closed by fabiospampinato** 2019-02-22 00:17 UTC
Labels: enhancement
