### ISSUE TITLE
Accidentally closing the app causes documents to become empty files

### ISSUE THREAD

**Issue by ndri** [notable/notable#542] opened 2019-03-14 11:27 UTC
- **OS Version**: Debian buster
- **Notable Version**: 1.3.0

### Current behavior
When in the middle of writing something and accidentally pressing ctrl + W (missing ctrl + E), the app closes and upon reopen, the file is empty. 

### Expected behavior
First of all ctrl + W should not close the app at all (at least without prompt) and even if the app is closed while typing something, the file should not be destroyed. I've lost many documents to this already.

**Comment by fabiospampinato** [comment] 2019-03-14 12:23
Closing as duplicate of #464, I'm addressing this issue right now.

Could you perhaps open a separate issue about the ctrl+w/ctrl+e problem?

**Closed by fabiospampinato** 2019-03-14 12:23 UTC
