### ISSUE TITLE
mermaid -Rendering Error

### ISSUE THREAD

**Issue by quotengrote** [notable/notable#1050] opened 2020-02-05 18:04 UTC
with mermaid there is a rendering error

```mermaid
graph TD
	tray1-->hdd2["4TB 2,5#quot;" HDD<br>ID:ata-ST4000LM024-2AN17V_WCK3KK9P<br>Label:HDD4<br>Port:scsi4<br>Position:unten links]
```

is showing as:

<a href="https://ibb.co/vQTV8yJ"><img src="https://i.ibb.co/vQTV8yJ/Unbenannt.png" alt="Unbenannt" border="0"></a>

the last line isnt showing properly

**Comment by fabiospampinato** [comment] 2020-02-05 23:26
Duplicate of #1027.

With your code I can reproduce the issue!

**Closed by fabiospampinato** 2020-02-05 23:26 UTC
