### ISSUE TITLE
Get list of currently available tags when adding a tag to a note

### ISSUE THREAD

**Issue by KraxelHuber** [notable/notable#1023] opened 2020-01-21 22:39 UTC
I would like to see a list of tags, which already exist, when adding a new tag to a note. When typing the tag's name, the list should shrink. I should then be able to select an existing tag via tab key.

Just think of using the search bar ;-)

This would help not to create a new tag by accident due to typos.

**Comment by fabiospampinato** [comment] 2020-01-21 22:51
Duplicate of #20

**Closed by fabiospampinato** 2020-01-21 22:51 UTC
