### ISSUE TITLE
Emoji not rendered on titles

### ISSUE THREAD

**Issue by Fastidious** [notable/notable#670] opened 2019-05-21 15:02 UTC
- **OS Version**: `macOS 10.14.4`
- **Notable Version**: `1.5.1`

<img width="1115" alt="Screenshot 2019-05-21 at 10 59 44" src="https://user-images.githubusercontent.com/8352292/58107423-cec8ab80-7bb7-11e9-996f-82c9be635e2f.png">

Emoji are not rendering on notes titles list. See above.

**Comment by fabiospampinato** [comment] 2019-05-24 00:56
I can't reproduce this in v1.5.1. 

At some points emojis stopped being rendered in titles because we stopped rendering markdown in titles at all, but then I decided to render emojis again, as that we actually want to always render and it's safe to do so.

The problem might be that those notes' titles didn't actually get updated, since unless they are manually changed we aren't refreshing them (I'll probably add an option for this at some point).

Can you try changing the title of the `Wrapping up :tada:` note? Even something like `Wrap :tada:` should work, if the emojis isn't rendered again then this is some weird bug I suppose.

**Comment by Fastidious** [comment] 2019-05-25 23:20
I am travelling. I just downloaded the latest, and saw that on the documents that come with it.

**Comment by fabiospampinato** [comment] 2019-05-30 12:11
Maybe the default tutorial notes needed to be updated, I've taken care of that now.

I'm closing this as the issue seems resolved, but feel free to reopen it if you'll still experience the same issue after v1.6.

**Closed by fabiospampinato** 2019-05-30 12:11 UTC
Labels: needs more info
