### ISSUE TITLE
Nested folder for Notebooks

### ISSUE THREAD

**Issue by AbhishekTripathi** [notable/notable#752] opened 2019-07-24 17:58 UTC
### Feature description

Ability to organize the Notebooks using folder structure.

### Feature motivation

At the moment the way Notebooks are implemented is by having tags added which goes to the top of the file as meta information. I have my notes organized in the folder level hierarchy which would be the most intuitive way to organize your files. I would like that as an alternate way to create Notebooks. At the moment I have to manually add the tags to the files which is extremely inconvenient and to the point that it makes me stop using the application.

**Comment by fabiospampinato** [comment] 2019-07-24 17:59
Duplicate of #54

**Closed by fabiospampinato** 2019-07-24 17:59 UTC
