### ISSUE TITLE
Cursor does not stay in same place when switching between view and edit mode

### ISSUE THREAD

**Issue by andrejonathan** [notable/notable#519] opened 2019-03-07 12:22 UTC
- macOS: High Sierra 10.13.6:
- Notable: 1.3.0:

### Current behavior
When switching between view and edit mode the cursor moves to the bottom of the page. Not a big deal on small notes but on multi-page notes can become very frustrating

### Expected behavior
When switching between view and edit mode the cursor should stay in the same place as that is probably where you want to edit.

**Comment by fabiospampinato** [comment] 2019-03-07 12:31
I can't reproduce this from the master branch, were we changed the editor. Let me know if you can still reproduce it in v1.4.0 (not released yet, I'm working on it).

**Comment by andrejonathan** [comment] 2019-03-07 13:42
Will do, please ping me when it is released, thanks

**Comment by andrejonathan** [comment] 2019-03-07 13:44
Sorry how rude of me. Great app by the way. Well done

**Comment by fabiospampinato** [comment] 2019-03-07 13:56
Don't worry I didn't think that was rude at all! You can get notified by GitHub about releases by clicking the `Unwatch -> Releases Only` button at the top right of the page.

**Comment by jeff9315** [comment] 2019-03-23 14:58
@fabiospampinato ... I'm not sure whether this is what @andrejonathan meant or not ... 

When I'm in the View mode and see an issue with my document, I go in to Edit mode. At that point, the cursor is where it was the **previous** time I was in Edit mode. I think what makes more sense is that it be placed where it was in the View mode. Or at least the Edit screen should scroll to the point that I was looking at in View mode (which is probably the place I want to edit).

**Comment by fabiospampinato** [comment] 2019-03-23 15:09
@jeff9315 that is intentional, we are trying to restore the state of the preview/editor component. There's an issue tracking already the synchronization of the scroll position #311 and I think there's already another one which propose to interpret a "ctrl+click", or something like that, in preview mode as a way to add a cursor in edit mode in that position. What you want is a bit different than that though, perhaps feel free to open a separate issue about that.

**Comment by fabiospampinato** [comment] 2019-03-23 15:10
Btw @andrejonathan v1.4 has been released!

**Comment by fabiospampinato** [comment] 2019-07-08 23:19
I think this probably got fixed in v1.6.

**Closed by fabiospampinato** 2019-07-08 23:19 UTC
Labels: needs more info
