### ISSUE TITLE
Attachment path completion

### ISSUE THREAD

**Issue by zygfrydw** [notable/notable#1063] opened 2020-02-19 15:06 UTC
It would be great to have path completion tool for inserting images to notes - something like code completion in the programing IDE or auto-completion in terminal.
This feature would greatly improve image insertion experience. Typing an exact path for attachment is highly prone to type errors and time-consuming.

**Comment by fabiospampinato** [comment] 2020-02-19 15:53
Duplicate of https://github.com/notable/notable/issues/20

**Closed by fabiospampinato** 2020-02-19 15:53 UTC
