### ISSUE TITLE
auto-detect persian and arabic language for supporting RTL

### ISSUE THREAD

**Issue by taha-github** [notable/notable#1102] opened 2020-03-29 22:05 UTC

**Comment by fabiospampinato** [comment] 2020-03-29 22:37
Duplicate of #248

**Closed by fabiospampinato** 2020-03-29 22:37 UTC

**Comment by taha-github** [comment] 2020-03-30 08:50
> Duplicate of #248

I didn't understand how to fix the problem.

**Comment by fabiospampinato** [comment] 2020-03-30 12:02
@taha-github There's nothing you can do right now, this is just not implemented today, that's the issue we are using for tracking this.
