### ISSUE TITLE
New notes are duplicates of currently open note

### ISSUE THREAD

**Issue by YohananDiamond** [notable/notable#469] opened 2019-02-19 23:53 UTC
- **OS Version**: Ubuntu 18.04
- **Notable Version**: 1.3.0

### Current behavior

Just open a note and click on the "add" button. I don't know when exactly this happens, but I've already restarted the app.

### Expected behavior

A new note will be added, but the edit screen will still be the previous one. With this, the new "Untitled" file syncs with the currently open file and it will have its contents and name.

**Comment by CavalloneChen** [comment] 2019-02-20 03:30
Yeah, the same here on Macos with 1.3.0. To make things worse, after clicking the new created note and deleting its content and clicking another old note, the old note is replaced by the empty new note. This behavior doesn't occur every time but is rather frequent, and has caused me losing some of my notes ☹️

**Comment by MykeMcG** [comment] 2019-02-20 17:52
I'm having the issue on Windows 10 with Notable v1.3.0. I've had to stop using the application after this issue lost me several pages of notes.

**Comment by krainboltgreene** [comment] 2019-02-20 19:50
This bug just deleted some very valuable information and will likely cost me hours.

**Comment by aaron-harvey** [comment] 2019-02-22 14:18
I had this issue on first run and lost some notes when I first ran the app but I haven't run into it since.  I have been about toggling edit and reving notes when I make changes though.

**Comment by lsascha** [comment] 2019-02-24 14:55
I just started and wanted to switch from Boostnote to Notable and think i encountered the same bug.

I entered notes and used the button to create new notes. After i noticed this i switched to different notes to see that Notable displays the same content for all notes.

I closed the app and reopened it just to see that all notes became the exact same note just with different tags. :( So all was lost.

After that i started using [CTRL + N] to start a new note and [CTRL + S] after i finished to save.
With that it worked and i was able to enter all notes with all tags etc.

But since this can delete all your notes i think this is a really important bug to fix.

**Comment by mikelu92** [comment] 2019-02-26 14:59
Hi I've also run into this issue.

This bug will also happen if you do the following steps:
1. Open a note in edit mode
2. Click on and switch to a different note.

The contents of the note in editting mode will stay the same, and if you save or toggle between viewing mode then the note that you switched to will be saved to the contents of the previous note.

Once I restarted the app it wasn't doing this anymore, but I did leave it open for a long time (probably a day?) and this behavior started happening.

**Comment by jonasstr** [comment] 2019-02-26 15:28
Same issue here. Notably just became unusable because of this. Please fix this asap!

**Comment by fabiospampinato** [comment] 2019-02-26 23:24
This is the next issue I'm working on right now, unfortunately one way I've found to reproduce the issue involves a bug in CodeMirror, or maybe a bug in `react-codemirror2`. So I'm solving the root problem and switching to Monaco #203, which is something I was planning on doing anyway, but this takes a bit of time as there's a theme for Monaco to rewrite, shortcuts to configure etc.

**Comment by krainboltgreene** [comment] 2019-02-26 23:37
Let me know if I can help

**Comment by fabiospampinato** [comment] 2019-02-26 23:48
@krainboltgreene Once I can no longer reproduce the issue I'll ask if you guys can still reproduce it from the master branch.

Also I'd like to say a few words about the future: I think pretty much all bugs are forgivable for this kind of app except those that cause data loss, so in the future if other such bugs are found I'll work on them right away and issue a patch release as soon as possible. Also I'd like to implement the first half of the [Future](https://github.com/notable/notable/milestone/2) milestone in the next few releases and then spend quite some time reorganizing and testing the codebase, right now things are not well separated and there aren't any automatic tests at all, I want to split the codebase into more modularized components that are easier to reason about, while also paving the way for future third-party components basically (#128), and have a much more reliable and tested storage implementation.

**Comment by santi-h** [comment] 2019-03-01 03:30
Same issue. When I edit one the other one changes as well. If I delete one, the other one gets deleted as well! I can't use notable right now because of this issue.

* **OS Version**: macOS Mojave 10.14.2
* **Notable Version**: 1.3.0


![issue](https://media.giphy.com/media/jHn4oXdXOHbdLVUoFC/giphy.gif)

**Comment by fchabouis** [comment] 2019-03-08 13:10
What I see is that the issue only occurs when you are in edit mode, and add a new note. Then the new note is a duplicate of the previous one. But if you switch to preview mode (ctrl+s), you can create the new note without any duplicate problem.

So a workaround for the moment is to switch to the preview mode before creating a new note.
It's also maybe a possible quick and dirty fix for you @fabiospampinato ?

I'm using ubuntu.

**Comment by fabiospampinato** [comment] 2019-03-08 14:44
> It's also maybe a possible quick and dirty fix for you @fabiospampinato ?

It's more of a workaround than a fix. I'm working on a fix for this right now, unfortunately I could reproduce this in 2 ways, one of which was caused by CodeMirror or react-codemirror, so since I was planning on switching to Monaco (#203) anyway, and since CodeMirror itself was the cause of a few other bugs, I've decided to bite the bullet and switch to Monaco, which turned out to be a way more time consuming endeavor than anticipated because Monaco is basically undocumented.

**Comment by ahmetsevki** [comment] 2019-03-11 14:39
> I'm having the issue on Windows 10 with Notable v1.3.0. I've had to stop using the application after this issue lost me several pages of notes.

I lost a whole bunch of notes like this due to this bug. 
Repro:
1. Create a new note, start typing on header like: "# Some New Note"
2. While in editing mode (do not do Option-S) Hit the '+' to create another note
3. This new note is a duplicate of the one you were editing

**Comment by krainboltgreene** [comment] 2019-03-11 14:49
Maybe a future edition should have a changelog ala pouchdb so that any bugs
can still be rolled back to a good state.

**Comment by fabiospampinato** [comment] 2019-03-11 15:20
@krainboltgreene I'm not quite sure what you mean, especially regarding rolling back bugs 🤔

**Comment by krainboltgreene** [comment] 2019-03-11 15:24
Every state change regarding documents should also write state to a
separate store, where the key is time. That way if something wipes out the
document state you have a log of previous states to rollback to.

**Comment by fabiospampinato** [comment] 2019-03-11 15:35
@krainboltgreene I see, basically you want version control #116 implemented I think. That's definitely going to get implemented, but I'm still trying to figure out what's the best way to piece all these things together (synchronization, version control, getting ~everything also working in a browser etc.).

**Comment by fabiospampinato** [comment] 2019-03-12 15:54
I can reproduce this quite reliably from the v1.3 commit (https://github.com/notable/notable/commit/7e969ce7498eceba090551eef075dfaa517b085d) but I can no longer reproduce this from the latest commit, so I'm calling this fixed.

Now the editor itself is more reliable, and we are interacting with it in a more reliable way. It'd be super helpful if somebody else could try reproducing this from the master branch too, otherwise let me know if the problem resurfaces on the v1.4 release (I'll probably make a release tomorrow, it depends on what roadblocks I stumble upon).

**Closed by fabiospampinato** 2019-03-12 15:54 UTC
Labels: bug

**Comment by krainboltgreene** [comment] 2019-03-12 16:06
Fantastic thanks so much.

**Comment by dvergeylen** [comment] 2019-03-14 08:23
I've tried to reproduce but couldn't build:

```
$ cd /tmp
$ git clone https://github.com/notable/notable/
$ npm install
$ nvm run svelto:dev
No .nvmrc file found
Running node v10.15.1 (npm v6.4.1)
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/tmp/notable/svelto:dev'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

anything I am doing wrong? Running node 10.15

**Comment by fabiospampinato** [comment] 2019-03-14 12:25
@dvergeylen just copy-paste [these](https://github.com/notable/notable/blob/master/.github/CONTRIBUTING.md#submit-a-pull-request) commands. You're executing `nmv run svelto:dev` which is probably a typo, and I'm not sure you're executing those commands from within Notable's repo.

**Comment by dvergeylen** [comment] 2019-03-14 12:34
I did these but typed a typo indeed. :unamused: 

Could build successfully and launch it. I couldn't reproduce the problem on my side 👍! LGTM

**Comment by fabiospampinato** [comment] 2019-03-14 12:39
Great, thanks for testing this!

**Comment by mikelu92** [comment] 2019-03-14 17:22
I also tried to reproduce the bug from master and couldn't. Thanks for your hard work!

**Comment by fabiospampinato** [comment] 2019-03-14 17:24
@mikelu92 thanks for checking this!
