### ISSUE TITLE
KaTeX and Markdown Interference

### ISSUE THREAD

**Issue by ibrahimkakbar** [notable/notable#701] opened 2019-06-19 21:35 UTC
- **OS Version**: Linux 16.04
- **Notable Version**: 1.5.1

### Current behavior
When using multiple subscripts in KaTeX the italicizing operator for Markdown overrides the subscripts causing weird behavior.

For example: $$V_i = \sum_{t=0}^\infty$$ causing the rendering of the summation to be different from $$\sum_{t=0}^\infty$$ which is the correct behavior.

I'm not sure if this is a simple fix but it's current functionality does not allow for subscripts to be longer than 1 character which is a bit of hinderance when trying to make something well-defined.

**Comment by fabiospampinato** [comment] 2019-06-19 21:42
I think the issue here is that the KaTeX processor should run before the Markdown processor, which is already the case in the current development version of the app.

--- 

Actually I've just checked this, and this is how those expressions are rendered in v1.5.1 for me:

<img width="132" alt="Screen Shot 2019-06-19 at 23 41 55" src="https://user-images.githubusercontent.com/1812093/59803477-d4ff9400-92eb-11e9-98bf-0867060c1202.png">

And this is how they are rendered in the dev version:

<img width="133" alt="Screen Shot 2019-06-19 at 23 42 12" src="https://user-images.githubusercontent.com/1812093/59803484-de88fc00-92eb-11e9-8cc6-c26301c52e0c.png">

I don't see any difference. How are they rendered for you?

**Comment by ibrahimkakbar** [comment] 2019-06-19 21:51
I guess I mis-attributed the error but

when I write:
$$V_i(x) = \sum_{t=0}^\infty$$
![Screenshot from 2019-06-19 14-47-28](https://user-images.githubusercontent.com/27082910/59803777-6695e400-92a1-11e9-9385-6e923c377131.png)

vs.
$$V_i^{\bm{\pi}}(x) = \sum_{t=0}^\infty$$
![Screenshot from 2019-06-19 14-47-49](https://user-images.githubusercontent.com/27082910/59803813-7f9e9500-92a1-11e9-9b80-70d5be053fa1.png)

**Comment by fabiospampinato** [comment] 2019-06-19 21:54
I still can't reproduce it on v1.5.1, can you post an entire note that reproduces the issue?

**Comment by ibrahimkakbar** [comment] 2019-06-19 21:57
# Mean Field Multi-Agent Reinforcement Learning Summary

#### Last Updated: 19.06.2019

## Introduction
Multi-agent reinforcement learning (MARL) concerns itself with a set of agents in a common environment. Since agents are interacting with each other and the environment, learning becomes fundamentally difficult. Independent Q-learning, where an agent treats the other agents as part of the environment, has been shown to make learning unstable since changes in one agent's policy will affect another agent's policy. Thus it is important to consider other agent's behavior through inference, leading to considering a joint policy over all agents while optimizing a single agent's policy. There is still a limitation, given current methods, on the number of agents in the environment. This paper considers the case where a large number of agents are present in the environment and each agent is interacting with a finite set of local agents. To avoid the exponential growth of the complexity based on number of agents the author's employ mean field theory to approximate all the interactions an agent interacting with it's local population's average behavior. Using this formulation the authors' develop a mean field Q-learning and mean field Actor-Critic algorithm and discuss convergence under some assumptions. The author's demonstrate that their formulation operates in settings where current state of art breaks down and performs overall well.

## Problem Formulation
A stochastic game, or N-agent MDP, $\Gamma$ is formalized as a tuple $\Gamma \triangleq (\mathcal{X}, \mathcal{U}_1, \ldots, \mathcal{U}_n, p_f, r_1, \ldots, r_n, \gamma)$, where $\mathcal{X}$ is the state space and $\mathcal{U}_i$ is the control space for agent $i \in \\{1, \ldots, n\\}$. The joint probabilistic motion model $p_f: \mathcal{X} \times \mathcal{U}_1 \times \ldots \times \mathcal{U}_n \mapsto \Omega(\mathcal{X})$ where $\Omega(\mathcal{X})$ is the space of probability distributions over the state space. The reward function $r_i: \mathcal{X} \times \mathcal{U}_1 \times \ldots \times \mathcal{U}_n \mapsto \mathbb{R}$ indicates immediate reward and $\gamma \in [0,1)$ is the discounting factor over time. In a stochastic game, all agents act simultaneously and receive reward $r_i$.

Agents determine their actions based on their policies $\pi_i: \mathcal{X} \mapsto \Omega(\mathcal{U}_i)$ and we denote the joint policy $\bm{\pi} \triangleq [\pi_1, \ldots, \pi_n]$ which is assumed to be stationary. Given an initial state $\{x}$ the value function of agent $\{i}$ following policy $\pi_i$ is given as the expected cumulative discounted reward with respect to the joint policy and motion model,
$$V_i^{\bm{\pi}}(x) = \sum_{t = 0}^\infty\gamma^t \mathbb{E}[r_j(x(t), u_1(t), \ldots, u_n(t)) | x_0 = x]$$

The $\{Q}$ function, $Q:\mathcal{X} \times \mathcal{U}_i \times \ldots \times \mathcal{U}_n \mapsto \mathbb{R}$ is obtained from the Bellman Equation of the value function,
$$Q_i^{\bm{\pi}} = r_i(x,\bm{u}) + \gamma \mathbb{E}[V_i^{\bm{\pi}}(x')]$$ where $x'$ is drawn from the motion model distribution $p_f$.

The stochastic game is discrete in time with a non-cooperative setting (i.e. no explicit factions). Furthermore the game is assumed to be incomplete but have perfect information (joint dynamics and reward function of other agents are unknown but previous actions and resulting immediate rewards are observable).

The objective of each agent is,
$$\pi_i^* =  \argmax_\bm{\pi} V^{\pi}(x) \hspace{2mm} \text{s.t.} \hspace{2mm} x_0 \in \mathcal{X}, \quad x \sim p_f, \quad \bm{u} \sim \bm{\pi}$$

Since optimization of an agent's policy depends on the joint policy $\bm{\pi}$ the concept of Nash equilibrium is important,

**Comment by ibrahimkakbar** [comment] 2019-06-19 21:59
# Mean Field Multi-Agent Reinforcement Learning Summary

#### Last Updated: 19.06.2019

## Introduction
Multi-agent reinforcement learning (MARL) concerns itself with a set of agents in a common environment. Since agents are interacting with each other and the environment, learning becomes fundamentally difficult. Independent Q-learning, where an agent treats the other agents as part of the environment, has been shown to make learning unstable since changes in one agent's policy will affect another agent's policy. Thus it is important to consider other agent's behavior through inference, leading to considering a joint policy over all agents while optimizing a single agent's policy. There is still a limitation, given current methods, on the number of agents in the environment. This paper considers the case where a large number of agents are present in the environment and each agent is interacting with a finite set of local agents. To avoid the exponential growth of the complexity based on number of agents the author's employ mean field theory to approximate all the interactions an agent interacting with it's local population's average behavior. Using this formulation the authors' develop a mean field Q-learning and mean field Actor-Critic algorithm and discuss convergence under some assumptions. The author's demonstrate that their formulation operates in settings where current state of art breaks down and performs overall well.

## Problem Formulation
A stochastic game, or N-agent MDP, $\Gamma$ is formalized as a tuple $\Gamma \triangleq (\mathcal{X}, \mathcal{U}_1, \ldots, \mathcal{U}_n, p_f, r_1, \ldots, r_n, \gamma)$, where $\mathcal{X}$ is the state space and $\mathcal{U}_i$ is the control space for agent $i \in \\{1, \ldots, n\\}$. The joint probabilistic motion model $p_f: \mathcal{X} \times \mathcal{U}_1 \times \ldots \times \mathcal{U}_n \mapsto \Omega(\mathcal{X})$ where $\Omega(\mathcal{X})$ is the space of probability distributions over the state space. The reward function $r_i: \mathcal{X} \times \mathcal{U}_1 \times \ldots \times \mathcal{U}_n \mapsto \mathbb{R}$ indicates immediate reward and $\gamma \in [0,1)$ is the discounting factor over time. In a stochastic game, all agents act simultaneously and receive reward $r_i$.

Agents determine their actions based on their policies $\pi_i: \mathcal{X} \mapsto \Omega(\mathcal{U}_i)$ and we denote the joint policy $\bm{\pi} \triangleq [\pi_1, \ldots, \pi_n]$ which is assumed to be stationary. Given an initial state $\{x}$ the value function of agent $\{i}$ following policy $\pi_i$ is given as the expected cumulative discounted reward with respect to the joint policy and motion model,
$$V_i^{\bm{\pi}}(x) = \sum_{t = 0}^\infty\gamma^t \mathbb{E}[r_j(x(t), u_1(t), \ldots, u_n(t)) | x_0 = x]$$

The $\{Q}$ function, $Q:\mathcal{X} \times \mathcal{U}_i \times \ldots \times \mathcal{U}_n \mapsto \mathbb{R}$ is obtained from the Bellman Equation of the value function,
$$Q_i^{\bm{\pi}} = r_i(x,\bm{u}) + \gamma \mathbb{E}[V_i^{\bm{\pi}}(x')]$$ where $x'$ is drawn from the motion model distribution $p_f$.

The stochastic game is discrete in time with a non-cooperative setting (i.e. no explicit factions). Furthermore the game is assumed to be incomplete but have perfect information (joint dynamics and reward function of other agents are unknown but previous actions and resulting immediate rewards are observable).

The objective of each agent is,
$$\pi_i^* =  \argmax_\bm{\pi} V^{\pi}(x) \hspace{2mm} \text{s.t.} \hspace{2mm} x_0 \in \mathcal{X}, \quad x \sim p_f, \quad \bm{u} \sim \bm{\pi}$$

Since optimization of an agent's policy depends on the joint policy $\bm{\pi}$ the concept of Nash equilibrium is important,

**Comment by ibrahimkakbar** [comment] 2019-06-19 22:00
There should be an underscore where it becomes italic after the U as well as after the \sum

**Comment by ibrahimkakbar** [comment] 2019-06-19 22:03
$\pi_i: \mathcal{X} \mapsto \Omega(\mathcal{U}_i)$ and we denote the joint policy $\bm{\pi} \triangleq [\pi_1, \ldots, \pi_n]$ which is assumed to be stationary. Given an initial state $\{x}$ the value function of agent $\{i}$ following policy $\pi_i$ is given as the expected cumulative discounted reward with respect to the joint policy and motion model,
$$V_i^{\bm{\pi}}(x) = \sum_{t= 0}^\infty\gamma^t \mathbb{E}[r_j(x(t), u_1(t), \ldots, u_n(t)) | x_0 = x]$$

**Comment by fabiospampinato** [comment] 2019-06-19 22:08
Now I can reproduce the issue.

> I think the issue here is that the KaTeX processor should run before the Markdown processor, which is already the case in the current development version of the app.

Actually I see KaTeX still runs after the Markdown gets rendered, I'll try to get this fixed before the next release.

Thanks for reporting the issue.

**Comment by ibrahimkakbar** [comment] 2019-06-19 22:11
Thank you for the awesome assistance and application!

**Comment by ibrahimkakbar** [comment] 2019-06-20 19:46
I just noticed that the backslash acts as an escape operator so applying it before an underscore or asterisk solves the issue!

**Comment by fabiospampinato** [comment] 2019-06-30 22:19
Now KaTeX is run before the Markdown gets processed, the snippet you posted [earlier](https://github.com/notable/notable/issues/701#issuecomment-503763545) is now rendered like so:

<img width="546" alt="Screen Shot 2019-07-01 at 00 16 17" src="https://user-images.githubusercontent.com/1812093/60402868-a314ea00-9b95-11e9-93cc-c65cbb93ea0f.png">

Does that look alright? I've checked how each expression gets rendered on https://katex.org and the result is the same for each of them.

The only think that looks off to me is the summation, perhaps it hasn't been written properly.

**Comment by fabiospampinato** [comment] 2019-07-09 00:14
I'm closing this as I think this got fixed in v1.6.

**Closed by fabiospampinato** 2019-07-09 00:14 UTC
Labels: bug
