### ISSUE TITLE
Tag bar fuzzy font

### ISSUE THREAD

**Issue by CaoZhenggg** [notable/notable#568] opened 2019-03-19 02:35 UTC
- **OS Version**: win10
- **Notable Version**: 1.4.0

### Current behavior

when click Tag bar， font become fuzzy

![Notable-BUG01](https://user-images.githubusercontent.com/23628206/54576343-ae9f3380-4a32-11e9-9850-6e0afaa0b536.jpg)

### Expected behavior

not fuzzy

**Comment by tbkrtz** [comment] 2019-03-19 08:57
Also in Notable 1.4.0 on Linux Mint 19.1. 
Its fuzzy only when edit-mode is active. (Windows and Linux)

**Comment by fabiospampinato** [comment] 2019-03-19 13:39
It sounds like a duplicate of #33, I suspect our editor might be using the problematic `will-change: transform` 🤔

**Comment by fabiospampinato** [comment] 2019-04-30 19:18
This should be fixed now, let me know if it happens again in the future 👍

**Closed** 2019-04-30 19:18 UTC
Labels: bug
